#!/usr/bin/env python3
"""E0: Layer 0 against FIDE on the 2025 US Championship; prints docs/evidence/E0_l0-validation.md.

Runs the Layer-0 engine (src/layer0, SPEC-L0 v1.0) on the committed fixture
tests/fixtures/validation/us_championship_2025.json and compares, game by game and
player by player, with FIDE's published calculation, and the November 2025 list
with the players' periods. The whole evidence page is this script's output, so
that check (a) reruns every number in it. Python standard library only.

Usage: python3 analysis/e0_l0_validation.py > docs/evidence/E0_l0-validation.md
"""
from __future__ import annotations

import json
import sys
from datetime import date
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
import layer0  # noqa: E402

FIXTURE = ROOT / "tests" / "fixtures" / "validation" / "us_championship_2025.json"


def main() -> int:
    fx = json.loads(FIXTURE.read_text(encoding="utf-8"))
    ev = fx["event"]
    players = {p["fide_id"]: p for p in fx["players"]}
    october = {pid: p["list_2025_10"]["rating"] for pid, p in players.items()}
    lists = {"2025-10": {pid: layer0.ListEntry(rating=p["list_2025_10"]["rating"], k=p["list_2025_10"]["k"])
                         for pid, p in players.items()}}
    tid = str(ev["event_id"])
    start = date.fromisoformat(ev["start"])
    t = layer0.Tournament(tid, start, date.fromisoformat(ev["end"]), ev["rating_period"], ev["chapter"])
    games = [layer0.Game(tid, g["round"], g["white"], g["black"], g["result"]) for g in fx["games"]]
    res = layer0.next_list(ev["rating_period"], lists, [t], games)

    sides_equal = sides = 0
    for g in fx["games"]:
        for me, opp, side in ((g["white"], g["black"], "fide_white"), (g["black"], g["white"], "fide_black")):
            row = next(r for r in res.players[me].games if r.round == g["round"])
            sides += 1
            sides_equal += row.delta == Decimal(g[side]["chg"]) and row.opponent_rating == g[side]["opponent_rating_used"]
    max_gap = max(abs(october[g["white"]] - october[g["black"]]) for g in fx["games"])

    print("# E0 — Layer 0 against FIDE: the 2025 US Championship\n")
    print("Status: REVIEW — evidence for SPEC-L0 §6.4 (session ELO-3, Phase 3). Generated by "
          "`analysis/e0_l0_validation.py` from `tests/fixtures/validation/us_championship_2025.json`; do not edit by "
          "hand. Licence: CC BY 4.0 (`docs/LICENSE-docs.md`).\n")
    print("## Event and sources\n")
    print(f"- {ev['event']}, {ev['place']}, {ev['start']} to {ev['end']}, {ev['system']}; FIDE event {ev['event_id']}, "
          f"rated on the {ev['rating_period']} standard list.")
    print("- Players, colours and results: FIDE's tournament report and the twelve players' published calculations "
          "(fetched 2026-10-09; the fixture's README says why the Lichess broadcast archive could not be used: the "
          "event is not in it). Ratings: FIDE's October 2025 standard list, the list in force at the start (R-11a).")
    print(f"- {len(players)} players, {len(fx['games'])} games, {len({g['round'] for g in fx['games']})} rounds; the "
          f"largest rating gap in any game is {max_gap} points, so the 400-point rule (R-14) is not exercised.\n")
    print("## Method\n")
    print("The Layer-0 engine (`src/layer0`, SPEC-L0 v1.0, ratified in D-0006) rates the event with `next_list`, "
          "the October 2025 list serving as both the list in force and the previous list. Each game's Delta R is "
          "compared with the change FIDE prints for that game, each player's sum, K and K x sum with FIDE's "
          "calculation for the event, and the new rating with the November 2025 list. Two players also played the "
          "2025 Grand Chess Tour Finals in the same period; for them FIDE's figures for that event are added before "
          "the period's change is rounded once (R-25), and the alternative of rounding each event's change is shown "
          "beside it.\n")
    print("## Results\n")
    print(f"- Games: Delta R and the opponent's rating equal FIDE's on {sides_equal} of {sides} player-games.\n")
    print("| FIDE ID | October | K | score | sum of Delta R, Layer 0 | FIDE | K x sum, Layer 0 | FIDE | match | other "
          "events (FIDE) | period change | November, rounded once | per event | published | match |")
    print("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    n_event = n_list = n_alt = 0
    for pid in sorted(players, key=lambda p: (-october[p], p)):
        p = players[pid]
        mine = res.players[pid]
        fide = p["fide_tournament"]
        tc = mine.tournaments[0]
        ok_event = (tc.sum_delta == Decimal(fide["chg"]) and mine.k == int(fide["K"])
                    and tc.change == Decimal(fide["K_chg"]))
        other = [Decimal(e["K_chg"]) for e in p["fide_other_events_in_period"]]
        total = tc.change + sum(other, Decimal(0))
        once = october[pid] + layer0.round_change(total)
        per_event = october[pid] + layer0.round_change(tc.change) + sum(layer0.round_change(x) for x in other)
        published = p["list_2025_11"]["rating"]
        n_event += ok_event
        n_list += once == published
        n_alt += per_event == published
        score = sum((r.score for r in mine.games), Decimal(0))
        print(f"| {pid} | {october[pid]} | {mine.k} | {score} / {mine.n} | {tc.sum_delta} | {fide['chg']} | "
              f"{tc.change} | {fide['K_chg']} | {'yes' if ok_event else 'NO'} | "
              f"{', '.join(str(x) for x in other) or '-'} | {total} | {once} | {per_event} | {published} | "
              f"{'yes' if once == published else 'NO'} |")
    print(f"\n- Event calculation: Layer 0 equals FIDE's for {n_event} of {len(players)} players (sum of Delta R, K "
          f"and K x sum, to the hundredth).")
    print(f"- November 2025 list: rounding the period's change once, as §8.3.4 is written, reproduces "
          f"{n_list} of {len(players)} published ratings; rounding each event's change separately would reproduce "
          f"{n_alt} of {len(players)}.")
    print(f"- Base corrections (R-11b): FIDE's starting rating equals the October list for "
          f"{sum(int(p['fide_tournament']['Ro']) == october[pid] for pid, p in players.items())} of {len(players)} "
          f"players.\n")
    print("## Limits\n")
    print("- One standard event of strong players: the 400-point rule, newcomers, juniors' K, the floor and the "
          "rapid and blitz branches are tested by the fixtures and unit tests of SPEC-L0 §7, not by this event.")
    print("- The rounding question of SPEC-L0 §8 Q-1 stays open: this event adds one player reproduced only by "
          "rounding once per period; fixture F-P02 is reproduced only by rounding per event.")
    print("- FIDE's official changes for this event are those of the November 2025 list, which the table reproduces.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
