#!/usr/bin/env python3
"""E10 report: turns analysis/aggregates/E10_guard.json into docs/evidence/E10_farming-guard.md.

Reads committed aggregates only (E10, and E2 for rung 2 without the guard and for Layer 0) and the 2026
championship event files (tools/events/); no data/ needed. Applies E2's decision rules (annex T8.2:
calibration rule (a) by 50-point bins with Holm–Bonferroni, slope (b), the do-no-harm check and the paired
moving-block bootstrap by month) with the functions of analysis/e2_broadcast_report.py imported unchanged,
and reports the farming region as E6 §6 does.

Usage: python3 analysis/e10_guard_report.py > docs/evidence/E10_farming-guard.md
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
sys.path.insert(0, str(ROOT / "src"))
import e2_broadcast_report as r2  # noqa: E402  (E2's decision rules, unchanged)
import e6_rungs_report as r6  # noqa: E402
from layer2 import guard  # noqa: E402

AGG = ROOT / "analysis" / "aggregates"
TCS = ("standard", "rapid", "blitz")
EVENTS = (("U.S. Championship", "tools/events/us_championship_2026.json"),
          ("U.S. Women's Championship", "tools/events/us_womens_championship_2026.json"))
WHO = {"layer0": "Layer 0 (table 8.1.2, 400-point rule)", "rung2": "rung 2 (fitted table)", "guarded": "rung 2 with the guard"}


def pct(a: int, b: int) -> str:
    return f"{100 * a / b:.1f} %"


def gate(cal: dict, harm_hi: float, ma: float, ma0: float, better_hi: float) -> tuple[bool, list[str]]:
    """E2's stage-1 rule for rung 2: (a), (b), do no harm (log-loss and calibration), log-loss better than Layer 0."""
    b_ok = cal["b"] == "pass"
    parts = [f"(a) {'pass' if cal['a_pass'] else 'fail'}", f"(b) {cal['b']}",
             f"do no harm {'pass' if harm_hi <= 0.002 and ma <= ma0 + 0.005 else 'fail'}",
             f"better than Layer 0 {'yes' if better_hi < 0 else 'no'}"]
    return cal["a_pass"] and b_ok and harm_hi <= 0.002 and ma <= ma0 + 0.005 and better_hi < 0, parts


def main() -> None:
    d = json.loads((AGG / "E10_guard.json").read_text(encoding="utf-8"))
    e2 = json.loads((AGG / "E2_broadcast.json").read_text(encoding="utf-8"))
    P: list[str] = []
    p = P.append
    res = {}
    for tc in TCS:
        t = d[tc]
        pm, months = t["per_month"], t["test_months"]
        n = sum(pm[m]["n"] for m in months)
        for m in months:
            pm[m]["d20"] = pm[m]["ll2"] - pm[m]["ll0"]
            pm[m]["dg0"] = pm[m]["ll2g"] - pm[m]["ll0"]
            pm[m]["dg2"] = pm[m]["ll2g"] - pm[m]["ll2"]
        iv = {k: (sum(pm[m][k] for m in months) / n, *r2.block_bootstrap(months, pm, k)) for k in ("d20", "dg0", "dg2")}
        bins2, binsg = e2["rolling"][tc]["bins"], t["bins_guarded"]
        c2, cg = r2.calibration(bins2, 0), r2.calibration(binsg, 0)
        ma0, ma2, mag = r2.all_bins_mean_abs(bins2, 1), r2.all_bins_mean_abs(bins2, 0), r2.all_bins_mean_abs(binsg, 0)
        ok2, parts2 = gate(c2, iv["d20"][2], ma2, ma0, iv["d20"][2])
        okg, partsg = gate(cg, iv["dg0"][2], mag, ma0, iv["dg0"][2])
        res[tc] = {"n": n, "iv": iv, "c2": c2, "cg": cg, "ma0": ma0, "ma2": ma2, "mag": mag, "ok2": ok2, "okg": okg,
                   "parts2": parts2, "partsg": partsg}
    farm = {tc: d[tc]["regions"]["farming"] for tc in TCS}

    # ---------------------------------------------------------------- the championship fields (R17, Phase 2)
    champs = []
    for name, path in EVENTS:
        ev = json.loads((ROOT / path).read_text(encoding="utf-8"))
        r = {pl["fide_id"]: pl["rating"] for pl in ev["players"]}
        gaps = [abs(r[g["white"]] - r[g["black"]]) for g in ev["games"]]
        inside = [g for g in ev["games"] if guard.in_region(max(r[g["white"]], r[g["black"]]), min(r[g["white"]], r[g["black"]]))]
        champs.append((name, ev["event"]["list_in_force"], len(ev["games"]), max(gaps), len(inside)))
    none_in = all(c[4] == 0 for c in champs)

    p("# E10 — The farming guard (R17) on rung 2: E2's and E6's checks rerun")
    p("")
    p("Status: REVIEW — evidence for the proposal (§5, §9, §12) and annex (T3, T4.2, T5 P4, T8.1, T8.10, T11), session ELO-5, "
      "Phase 2. Generated by `analysis/e10_guard_report.py` from `analysis/aggregates/E10_guard.json`, which "
      "`analysis/e10_guard_extract.py` computes from the Lichess broadcast archive (https://database.lichess.org/broadcast/, "
      "CC BY-SA 4.0, attributed; aggregates only) [V 4] and FIDE's monthly lists (analysed, never committed or redistributed) "
      "[V 3]; the guard is `src/layer2/guard.py`, Layer 0 is `src/layer0/`. Do not edit by hand. Licence: CC BY 4.0 "
      "(`docs/LICENSE-docs.md`). The table's parameters are PROVISIONAL-FITTED [E2]; the guard is temporary by ruling.")
    p("")
    s, rp, bz = res["standard"], res["rapid"], res["blitz"]
    p("**In brief.** Ruling R17 (`docs/decisions/D-0009_architect-rulings-elo-5.md`) guards rung 2 where farming pays: when "
      "the gap is 400 or more and the favourite is rated 2300 or more, the favourite's expectation is the larger of the "
      "fitted table and table 8.1.2 read without its 400-point cap. On E2's 21 test months the fitted value is the smaller "
      "in every game of that region, so the guard always binds there; the region holds "
      + ", ".join(f"{tc} {d[tc]['counts']['r17_games']:,} of {d[tc]['counts']['games']:,} games "
                  f"({pct(d[tc]['counts']['r17_games'], d[tc]['counts']['games'])})" for tc in TCS) + ". "
      f"In the farming region of E6 (gap 400 or more at level 2300 or more) the favourite's residual moves from "
      + ", ".join(f"{farm[tc]['rung2']['mean']:+.3f} to {farm[tc]['guarded']['mean']:+.3f} in {tc}" for tc in TCS)
      + ": the farming gain becomes a loss. Rung 2 with the guard still forecasts better than Layer 0 overall in all three "
      "time controls and passes the do-no-harm check, at a cost against rung 2 without it of "
      + ", ".join(f"{res[tc]['iv']['dg2'][0]:+.4f}" for tc in TCS) + " nats a game (standard, rapid, blitz). Its full "
      "stage-1 rule (calibration (a) and (b), do no harm, better than Layer 0): "
      + "; ".join(f"{tc} {'passes' if res[tc]['okg'] else 'fails'} ({', '.join(res[tc]['partsg'])})" for tc in TCS)
      + ". Neither 2026 championship field has a pairing in the guard's region "
      + ("(largest gaps " + " and ".join(f"{c[3]}" for c in champs) + "), so Freeze 1 stands for the comparison (E3)."
         if none_in else "; the comparison therefore uses the guarded tool frozen in Freeze 2 (E3)."))
    p("")

    # ---------------------------------------------------------------- 1
    p("## 1 The guard and how it is tested")
    p("")
    p(f"- **The rule** (R17; D-0009, reading 4). Region: the favourite's published rating at least {guard.FAV_MIN} and the gap "
      f"at least {guard.GAP_MIN}, the gap being the published difference without the colour term. There, the favourite's "
      "expectation is max(fitted value, table 8.1.2's H entry at the full difference) and the underdog's is one minus it; "
      "each player's expectation is guarded on the gap it uses. All three time controls. It lapses only when FIDE's game "
      "data calibrate the region.")
    p("- **The sample and the months** are E2's: its sample is rebuilt with E2's own functions, imported unchanged, and each "
      "of the 21 test months (2025-01 to 2026-09) is forecast with the parameters E2 fitted on the 36 months before it. "
      "Before the guard is applied the script reproduces E2's monthly sums for Layer 0 and rung 2 and E2's calibration bins: "
      + "; ".join(f"{tc} largest difference {d[tc]['reproduces_e2']['max_abs_difference_of_monthly_sums']:.1e}, bins "
                  f"{'equal' if d[tc]['reproduces_e2']['bins_equal'] else 'different'}" for tc in TCS) + ".")
    p("- **Three-outcome forecasts.** Where the guard binds, the fitted draw probability is kept and the win and loss "
      "probabilities move to the guarded expectation (E6's three-outcome split); elsewhere the forecast is rung 2's.")
    p("- **Decision rules** are E2's (annex T8.2), applied with E2's report functions; the regions use E6's month-block "
      "bootstrap (blocks of 3, 2,000 resamples, seed 20261009) and its bootstrap over the favourites (players).")
    p(f"- **Data cutoff.** No broadcast file after 2026-09 is opened; games dated after 2026-09-30: "
      f"{d['cutoff'].get('dropped_after_cutoff', 0)} dropped.")
    p("")

    # ---------------------------------------------------------------- 2
    p("## 2 The farming region and the guard's region")
    p("")
    p("The favourite's residual S − E (negative: the favourite scores below the expectation, so playing far weaker opponents "
      "costs points), month-block interval:")
    p("")
    p("| time control | region | games | " + " | ".join(WHO.values()) + " |")
    p("|---|---|---|---|---|---|")
    names = {"farming": "farming region of E6: gap ≥ 400, level ≥ 2300", "r17": "guard's region: gap ≥ 400, favourite ≥ 2300",
             "r17_level_below_2300": "of which level below 2300"}
    for tc in TCS:
        for key, label in names.items():
            reg = d[tc]["regions"][key]
            p(f"| {tc} | {label} | {r6.n0(reg['layer0']['n'])} | " + " | ".join(r6.ci(reg[w]) for w in WHO) + " |")
    p("")
    p("The same with the bootstrap over the favourites (players):")
    p("")
    p("| time control | region | favourites | " + " | ".join(WHO.values()) + " |")
    p("|---|---|---|---|---|---|")
    for tc in TCS:
        for key, label in names.items():
            reg = d[tc]["regions_players"][key]
            p(f"| {tc} | {label} | {r6.n0(reg['layer0']['clusters'])} | " + " | ".join(r6.ci(reg[w]) for w in WHO) + " |")
    p("")
    p("- **The farmer's yield** at K = 10, the K of every player rated 2400 or more today [V 1], is ten times the residual a "
      "game: in E6's farming region " + "; ".join(
          f"{tc} {10 * farm[tc]['rung2']['mean']:+.2f} points a game without the guard and "
          f"{10 * farm[tc]['guarded']['mean']:+.2f} with it (Layer 0 {10 * farm[tc]['layer0']['mean']:+.2f})" for tc in TCS) + ".")
    p("- **Below level 2300.** Most of the guard's region lies below the farming region's level (a favourite of 2300 to 2499 "
      "meeting an opponent 400 or more below): there rung 2 without the guard is "
      + ", ".join(f"{d[tc]['regions']['r17_level_below_2300']['rung2']['mean']:+.3f} in {tc}" for tc in TCS)
      + ", and the guard takes the favourite's residual to "
      + ", ".join(f"{d[tc]['regions']['r17_level_below_2300']['guarded']['mean']:+.3f}" for tc in TCS) + ".")
    p("")

    # ---------------------------------------------------------------- 3
    p("## 3 Do no harm and calibration, with and without the guard (E2's rules)")
    p("")
    p("| time control | test games | log-loss, rung 2 − Layer 0 | rung 2 with the guard − Layer 0 | the guard's cost: guarded − rung 2 | mean \\|residual\\| over all bins: Layer 0 / rung 2 / guarded |")
    p("|---|---|---|---|---|---|")
    for tc in TCS:
        r = res[tc]
        f = lambda k: f"{r['iv'][k][0]:+.4f} ({r['iv'][k][1]:+.4f} to {r['iv'][k][2]:+.4f})"  # noqa: E731
        p(f"| {tc} | {r['n']:,} | {f('d20')} | {f('dg0')} | {f('dg2')} | {r['ma0']:.4f} / {r['ma2']:.4f} / {r['mag']:.4f} |")
    p("")
    p("| time control | rule (a): bins outside ±0.01, rung 2 / guarded | slope (b), rung 2 | slope (b), guarded | stage-1 rule, rung 2 | stage-1 rule, guarded |")
    p("|---|---|---|---|---|---|")
    for tc in TCS:
        r = res[tc]
        o2 = sum(x["outside"] for x in r["c2"]["rows"])
        og = sum(x["outside"] for x in r["cg"]["rows"])
        p(f"| {tc} | {o2} of {r['c2']['m']} / {og} of {r['cg']['m']} | {r['c2']['slope']:.3f} ({r['c2']['b']}) | "
          f"{r['cg']['slope']:.3f} ({r['cg']['b']}) | {'pass' if r['ok2'] else 'fail'} | {'pass' if r['okg'] else 'fail'} |")
    p("")
    p("Calibration bins of the guard's gaps, the favourite's side (bins with at least 1,000 test games; \"outside\" after "
      "Holm–Bonferroni):")
    p("")
    p("| time control | gap | games | residual, rung 2 | residual, guarded | outside, guarded |")
    p("|---|---|---|---|---|---|")
    for tc in TCS:
        rows2 = {x["bin"]: x for x in res[tc]["c2"]["rows"]}
        for x in res[tc]["cg"]["rows"]:
            if x["bin"] >= 350:
                p(f"| {tc} | {x['bin']}–{x['bin'] + 49} | {x['n']:,} | {rows2[x['bin']]['r']:+.4f} | {x['r']:+.4f} | "
                  f"{'yes' if x['outside'] else 'no'} |")
    p("")

    # ---------------------------------------------------------------- 4
    p("## 4 The 2026 U.S. Championships against the guard's region")
    p("")
    p("| event | list in force | games | largest gap | pairings in the guard's region |")
    p("|---|---|---|---|---|")
    for name, lst, ng, mx, nin in champs:
        p(f"| {name} | {lst} | {ng} | {mx} | {nin} |")
    p("")
    p("The official pairings of all eleven rounds, with the ratings of FIDE's October 2026 list, as recorded in the event "
      "files (`tools/events/`). " + ("No pairing falls in the guard's region, so the guard cannot change any expectation in "
                                    "either event: Freeze 1's rung-2 column stands for the comparison, and E3 says so."
                                    if none_in else "Pairings fall in the guard's region: the comparison uses the guarded "
                                    "tool frozen in Freeze 2, and E3 says so."))
    p("")

    # ---------------------------------------------------------------- 5
    p("## 5 Reading")
    p("")
    p("- **The guard does what R17 asks.** Where the fitted table under-predicted big favourites, the guard replaces it by "
      "today's table read in full, so a strong player who seeks out far weaker opponents loses points on average instead of "
      "gaining them, in all three time controls.")
    p("- **Its price is calibration in its region.** Table 8.1.2 read without the cap expects more of the favourite than the "
      "favourite scores, and more than today's capped reading does for players below 2650; the guard therefore over-predicts "
      "favourites throughout its region, most in rapid, whose fitted curve is the flattest. Overall the guarded table still "
      "forecasts far better than Layer 0 in all three time controls; by E2's full stage-1 rule it "
      + ", ".join(f"{'passes' if res[tc]['okg'] else 'fails'} in {tc}" for tc in TCS) + ".")
    p("- **What lifts it.** FIDE's game archive, with enough games in the region for the formal test of annex T8.2 (bins of "
      "1,000 games), which the broadcast archive cannot supply (R12).")
    p("")

    # ---------------------------------------------------------------- 6
    p("## 6 Limits")
    p("")
    p("- The broadcast games are stronger and more international than the rated pool [E2]; the region's results hold for them.")
    p("- The three-outcome forecast where the guard binds keeps the fitted draw probability, a choice for scoring only: the "
      "guard defines the expected score, not the three probabilities.")
    p("- E2's parameters for each month are used as fitted; the guard is applied after the fit and does not refit the table.")
    sys.stdout.write("\n".join(P) + "\n")


if __name__ == "__main__":
    main()
