#!/usr/bin/env python3
"""E13 under Freeze 3a: the 2026 U.S. Championships; prints docs/evidence/E13_us-championship-2026-freeze-3.md.

Freeze 3a (docs/decisions/D-0012_pre-results-amendments.md) amends Freeze 3 (D-0011, part B) before any result is read:
a marker for a game not played and the completion rule (R43), and a new column (b′), "v2 table and narrowed guard at
today's K", §10's main column (R44, R45). This script runs tools/compare_event_v3a.py on the committed event files: per
player (a) Layer 0, (b′), (b) rung 2 v2 with K x m as Freeze 3 pre-registered it, (b0) rung 2 as Freeze 2 pre-registered
it, and, labelled PILOT, rung 5 on top of (b). By the operator's decision of 2026-10-09 the comparison runs once, after
the event ends: an event's tables are printed only when it is complete, every game of rounds 1-11 having a result or the
marker for a game not played. The page prints the blanks of the proposal's §10 as D-0012 redefines them (their values
once both events are complete) and the SHA-256 of every file the comparison depends on with their manifest, which check
(a) compares with the one D-0012 records. Freeze 3's page script, analysis/e13_us_championships_freeze3.py, stays
unchanged and is used here as a module. Python standard library only.

Usage: python3 analysis/e13_us_championships_freeze3a.py > docs/evidence/E13_us-championship-2026-freeze-3.md
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(ROOT / "src"))
import compare_event_v3a as v3a  # noqa: E402
import e13_us_championships_freeze3 as e13  # noqa: E402  (Freeze 3's page script, unchanged: its list and hashes)
import set_results as sr  # noqa: E402
from layer2 import guard_v2 as gv2  # noqa: E402

OPEN, WOMEN, Y2025 = e13.OPEN, e13.WOMEN, e13.Y2025
PAGE = e13.PAGE
PENDING = e13.PENDING
FREEZE_RECORD = "docs/decisions/D-0012_pre-results-amendments.md"
FREEZE3_MANIFEST = "e84f0564153579dcd394381e96fd55d046a2fe9f903b2806e758008230463ff5"   # D-0011, part B
# Freeze 3a (D-0012): Freeze 3's files, with the results-entry tool and the check as D-0012 changes them, and the two new
# files that compute and print column (b′) and the completion rule.
NEW_IN_3A = ["analysis/e13_us_championships_freeze3a.py", "tools/compare_event_v3a.py"]
FREEZE3A = sorted(e13.FREEZE3 + NEW_IN_3A)
CHANGED_BY_3A = ["tools/checks/check_outputs.py", "tools/set_results.py"]


def freeze3a_lines() -> list[tuple[str, str]]:
    """(file, SHA-256) for every file Freeze 3a freezes, and the 2026 event files with their results removed."""
    return [(f, e13.sha(f)) for f in FREEZE3A] + [(f + " (without results)", e13.e3.event_sha_without_results(f))
                                                  for f in (OPEN, WOMEN)]


def freeze3a_manifest(lines: list[tuple[str, str]] | None = None) -> str:
    """SHA-256 of the lines "hash  file", one per frozen file: the value D-0012 records."""
    lines = freeze3a_lines() if lines is None else lines
    return hashlib.sha256("".join(f"{h}  {f}\n" for f, h in lines).encode("utf-8")).hexdigest()


def summary_table(c: v3a.Comparison) -> None:
    """The three blanks of each rung-2 column on one complete event, as §10 states them."""
    b = v3a.blanks(c)
    print("| against (a) | (b′) v2 table and narrowed guard at today's K | (b) Freeze 3, K × m | (b0) first "
          "pre-registration, superseded |")
    print("|---|---|---|---|")
    print(f"| mean of \\|x − (a)\\| over the players, unrounded, points | {b['MEAN_ABS_DIFF']} | {b['B_MEAN_ABS_DIFF']} | "
          f"{b['B0_MEAN_ABS_DIFF']} |")
    print(f"| x − (a) of largest absolute value, signed, unrounded | {b['MAX_DIFF']} | {b['B_MAX_DIFF']} | "
          f"{b['B0_MAX_DIFF']} |")
    print(f"| players whose rounded change differs from (a) | {b['N_DIFFER']} | {b['B_N_DIFFER']} | {b['B0_N_DIFFER']} |")


def main() -> int:
    y = v3a.run(Y2025)
    o, w = v3a.run(OPEN), v3a.run(WOMEN)
    P = print
    P("# E13 — The 2026 U.S. Championships under Freeze 3a: columns (a), (b′), (b), (b0) and the PILOT table\n")
    P("Status: DRAFT — not for publication; the events are in progress (Freeze 3 recorded in session ELO-6, Phase 4, "
      "`docs/decisions/D-0011_rulings-and-freeze-3.md`, part B; amended by Freeze 3a in session ELO-7, Phase 0, "
      f"`{FREEZE_RECORD}`). Generated by `analysis/e13_us_championships_freeze3a.py` with `tools/compare_event_v3a.py`, "
      "which runs `tools/compare_event_v3.py` unchanged, from the event files in `tools/events/`, "
      "`params/table_fit_2026-10b.yaml`, `params/guard_2026-10b.yaml`, `params/table_fit_2026-10.yaml` and "
      "`params/rung5_us2026.json`; do not edit by hand. Licence: CC BY 4.0 (`docs/LICENSE-docs.md`). For the comparison "
      "it supersedes the tables that `docs/evidence/E3_us-championship-2026.md` prints under Freeze 2.\n")
    P("## What is compared (D-0011, part B, as D-0012 amends it)\n")
    P("- **(a)** the event's change under FIDE's rules, computed by the ratified Layer-0 engine (`src/layer0/`, Freeze 1).")
    P("- **(b′)** rung 2 at today's K, \"v2 table and narrowed guard at today's K\", **§10's main column** (R44, R45): "
      "the table calibrated by level (`params/table_fit_2026-10b.yaml`, [E11]), the narrowed guard "
      "(`params/guard_2026-10b.yaml`, R24, [E12]) and K from the list in force, reduced under K × n ≤ 700, as Layer 0 "
      "computes it; computed only from Freeze 3's frozen table and guard and Layer 0's K, with no new parameter.")
    P("- **(b)** rung 2 v2 exactly as Freeze 3 pre-registered it (D-0011, part B): the same table and guard with each "
      "game's K multiplied by the table's printed slope ratio m(L) (R32, withdrawn by R44); reported as pre-registered "
      "and labelled.")
    P("- **(b0)** rung 2 exactly as Freeze 2 pre-registered it (`tools/compare_event.py` with "
      "`params/table_fit_2026-10.yaml`, Freeze 1): the **first pre-registration, superseded**.")
    P("- **PILOT**, printed separately: rung 5 on top of (b), with the frozen rung-5 inputs (`params/rung5_us2026.json`, "
      "D-0010), as Freeze 3 pre-registered it.")
    P(f"- **A game not played** (a forfeit, a withdrawal, a bye) is entered with the marker `{sr.UNPLAYED}` (R43) and "
      "excluded from every column, as FIDE does not rate it (§5.1 [V 1]); an event is complete when every game of rounds "
      "1–11 has a result or that marker, and §10 counts played games only.")
    P("- Nothing else: rungs 3, 4, 6 and 7, and any other column, statistic, subset or event, are not computed on the "
      "event.\n")
    P("## The check: the 2025 U.S. Championship\n")
    P(f"Column (a) must equal FIDE's per-event calculation (SPEC-COMPARE §4): `tests/test_compare_event_v3.py` asserts it "
      f"for all {len(y.rows)} players against `tests/fixtures/validation/us_championship_2025.json`, the fixture of E0, and "
      "that (b0) equals Freeze 2's column (b); `tests/test_compare_event_v3a.py` asserts that (b′) is column (b) without "
      "m and that the other columns are Freeze 3's.\n")
    P(v3a.to_markdown(y))
    d = {k: [r[k] - r["a"] for r in y.rows] for k in ("bp", "b", "b0")}
    P(f"In 2025, with the same results, rung 2 at today's K (b′) would have changed the twelve players' gains by "
      f"{min(d['bp']):+.2f} to {max(d['bp']):+.2f} points against FIDE's rules, Freeze 3's column (b) by "
      f"{min(d['b']):+.2f} to {max(d['b']):+.2f}, and Freeze 2's (b0) by {min(d['b0']):+.2f} to {max(d['b0']):+.2f}. "
      "The blanks of §10, computed on 2025's results as they will be on 2026's:\n")
    summary_table(y)
    P("")
    P("## 2026 U.S. Championship and U.S. Women's Championship\n")
    P(f"**{PENDING}.**\n")
    P("By the operator's decision of 2026-10-09, no game of either 2026 championship is processed while the event runs. "
      "The comparison runs once, after the last round (21 October; the playoff of 22 October is not part of it), on all "
      "games at once.\n")
    for name, c in (("U.S. Championship", o), ("U.S. Women's Championship", w)):
        if c.complete:
            P(f"### {name}\n")
            P(v3a.to_markdown(c))
            P(f"### {name}, PILOT\n")
            P(v3a.pilot_markdown(c))
        else:
            P(f"- {name}: {c.counted} of {c.scheduled} games have a result, {c.unplayed} marked not played; {PENDING}.")
    P("\n## The blanks of the proposal's §10 (D-0012)\n")
    if not (o.complete and w.complete):
        P(f"**{PENDING}.** Each blank is computed here, from the tables above, once both events are complete, over played "
          "games only: `{{US26_*_GAMES}}`, the games counted; for (b′), the main column, `{{US26_*_MEAN_ABS_DIFF}}`, "
          "`{{US26_*_MAX_DIFF}}`, `{{US26_*_N_DIFFER}}`; for (b), Freeze 3's column, `{{US26_*_B_MEAN_ABS_DIFF}}`, "
          "`{{US26_*_B_MAX_DIFF}}`, `{{US26_*_B_N_DIFFER}}`; for (b0), `{{US26_*_B0_MEAN_ABS_DIFF}}`, "
          "`{{US26_*_B0_MAX_DIFF}}`, `{{US26_*_B0_N_DIFFER}}`; for the PILOT, `{{US26_*_R5_GAMES}}` and "
          "`{{US26_*_R5_DIFF}}`. `{{US26_*_L0_MATCH}}` follows the 1 November 2026 list, from FIDE's published "
          "calculations, and `{{US26_READING}}` is written by hand; D-0012 defines each.\n")
    else:
        vals = {"OPEN": v3a.blanks(o), "WOMEN": v3a.blanks(w)}
        P("| blank | U.S. Championship | U.S. Women's Championship |")
        P("|---|---|---|")
        for k in v3a.BLANKS:
            P(f"| `{{{{US26_*_{k}}}}}` | {vals['OPEN'][k]} | {vals['WOMEN'][k]} |")
        P("\n`{{US26_*_L0_MATCH}}` waits for FIDE's published calculations after the 1 November 2026 list; "
          "`{{US26_READING}}` is written by hand (D-0012).\n")
    P("## The guard and the two fields\n")
    P("| event | games | largest gap | lowest game level | pairings in the narrowed guard's region | guard binds in (b′) "
      "and (b) |")
    P("|---|---|---|---|---|---|")
    for name, c in (("U.S. Championship", o), ("U.S. Women's Championship", w)):
        r = {pl["fide_id"]: pl["rating"] for pl in c.event["players"]}
        gaps = [abs(r[g["white"]] - r[g["black"]]) for g in c.event["games"]]
        lv = [(r[g["white"]] + r[g["black"]]) / 2 for g in c.event["games"]]
        inside = sum(1 for g in c.event["games"] if gv2.in_region(r[g["white"]], r[g["black"]]))
        P(f"| {name} | {len(c.event['games'])} | {max(gaps)} | {min(lv):g} | {inside} | {c.base.guard_games} |")
    P("\nThe official pairings of all eleven rounds with the ratings of FIDE's October 2026 list, as the event files "
      "record them; no result is read. No pairing lies in the region of the guard, so in both events (b′) differs from "
      "(b0) through the v2 table only, and (b) from (b′) through m only.\n")
    P("## Freeze 3a (D-0012), amending Freeze 3 (D-0011, part B)\n")
    P(f"Recorded in `{FREEZE_RECORD}` before any result of either event was read, and tagged `freeze-3a`. Every fit "
      "behind these numbers uses games up to 30 September 2026, a cutoff enforced in code (`analysis/e10_guard_extract.py`, "
      "`src/layer1/data.py`, `src/layer1/fit.py`); no game of either event was read. SHA-256 of every file the comparison "
      f"depends on: Freeze 3's {len(e13.FREEZE3)} files, of which D-0012 changed {len(CHANGED_BY_3A)} "
      f"({', '.join(f'`{f}`' for f in CHANGED_BY_3A)}), the {len(NEW_IN_3A)} files Freeze 3a adds "
      f"({', '.join(f'`{f}`' for f in NEW_IN_3A)}), and the two event files with their results removed:\n")
    P("| File | SHA-256 |")
    P("|---|---|")
    lines = freeze3a_lines()
    for f, h in lines:
        tail = " (without results)" if f.endswith("(without results)") else ""
        P(f"| `{f.replace(' (without results)', '')}`{tail} | `{h}` |")
    P(f"\nManifest (SHA-256 of the {len(lines)} lines \"hash  file\" above): `{freeze3a_manifest(lines)}`.\n")
    P("Check (a) reruns this page on every pull request and compares this manifest with the one D-0012 records, so a "
      "change to any of these files, or to the pairings, ratings or K of either event file, fails the check until a new "
      "decision record supersedes D-0012. Entering the results, or the marker for a game not played, changes no value "
      f"here. Freeze 3's manifest, `{FREEZE3_MANIFEST}` (D-0011, part B, tag `freeze-3`), is superseded by this one; "
      "Freeze 3's page script is kept unchanged and listed above. Proposal numbers drawn from history and the simulator "
      "may still change until submission, provided no event game is read (D-0011, part B).\n")
    P("## Running the comparison after the event\n")
    P(f"Enter each round's results from the official page ({PAGE}), board by board: `1-0`, `1/2-1/2` or `0-1`; "
      f"`{sr.UNPLAYED}` for a game not played (a forfeit, a withdrawal, a bye); `-` for no result yet. Boards 7–12 go into "
      "the women's event file. Then regenerate this page and E3 once (`tools/README.md`):\n")
    P("```")
    P("python3 tools/set_results.py tools/events/us_championship_2026.json ROUND R1 R2 R3 R4 R5 R6")
    P("python3 analysis/e13_us_championships_freeze3a.py > docs/evidence/E13_us-championship-2026-freeze-3.md")
    P("python3 analysis/e3_freeze2_record.py > docs/evidence/E3_us-championship-2026.md")
    P("```")
    return 0


if __name__ == "__main__":
    sys.exit(main())
