#!/usr/bin/env python3
"""E15 report: Layer 1's hyperparameter grids widened (ruling R41; session ELO-6, Phase 5).

Reads only the committed aggregate analysis/aggregates/E15_l1_grid.json (no data/ needed): the first search of
SPEC-L1 §4.6, as analysis/aggregates/L1_history.json records it, beside the widened search of
analysis/e15_l1_grid_extract.py, and what R41 then requires.

Usage: python3 analysis/e15_l1_grid_report.py > docs/evidence/E15_l1-grid.md
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def key(g: dict) -> tuple:
    return (g["c_theta"], g["omega"])


def main() -> None:
    d = json.loads((ROOT / "analysis" / "aggregates" / "E15_l1_grid.json").read_text(encoding="utf-8"))
    prev, grid, chosen = d["previous"], d["grid"], d["chosen"]
    rows = {key(g): ("first search", g) for g in prev["grid"]}
    for g in grid:
        rows[key(g)] = ("both searches" if key(g) in rows else "widened search", g)
    moved = key(chosen) != key(prev["chosen"])
    c0, w0 = chosen["c_theta"], chosen["omega"]
    ll0 = chosen["log_loss"]
    below_c = [g for g in prev["grid"] + grid if g["c_theta"] < c0]
    above_c = [g for g in prev["grid"] + grid if g["c_theta"] > c0]
    below_w = [g for g in prev["grid"] + grid if g["c_theta"] == c0 and g["omega"] < w0]
    above_w = [g for g in prev["grid"] + grid if g["c_theta"] == c0 and g["omega"] > w0]
    P = []
    p = P.append
    p("# E15 — Layer 1's hyperparameter grids widened (R41)")
    p("")
    p("Status: REVIEW — evidence for the proposal and annex (T2.3a, T4.6, T8.10), session ELO-6, Phase 5, after Freeze 3. "
      "Generated by `analysis/e15_l1_grid_report.py` from `analysis/aggregates/E15_l1_grid.json`, which "
      "`analysis/e15_l1_grid_extract.py` computes with Layer 1 (`docs/specs/SPEC-L1_v1_0.md`, `src/layer1/`) from the "
      "Lichess broadcast archive (CC BY-SA 4.0, attributed; aggregates only) [V 4] and FIDE's lists (analysed, never "
      "redistributed) [V 3], with the fits, data and protocol of `analysis/l1_history_extract.py` and the data cutoff of "
      "30 September 2026 enforced in `src/layer1/`. Do not edit by hand. Licence: CC BY 4.0 (`docs/LICENSE-docs.md`). "
      "Every value is PROVISIONAL-FITTED on broadcast games, which are stronger and more international than the rated "
      "pool [E2].")
    p("")
    p("## 1 What R41 asks")
    p("")
    p("Layer 1's two hyperparameters, c_θ (the scale of the monthly random walk of a player's strength) and ω (the "
      "innovation SD of the time-control offsets), both SPEC-L1 §3.7, were chosen on held-out games (§4.6): first c_θ at "
      "a fixed ω, then ω at the chosen c_θ. Both choices sat at "
      "an end of their grids (`analysis/OUTPUT_L1_history.md`). R41 (`docs/decisions/D-0011_rulings-and-freeze-3.md`, "
      "reading 15) widens each grid by two of its own steps beyond that end and searches again in the same way; if the "
      "optimum moves inside the wider grid, E6's rung 5 test is rerun with it and rung 5's history figures restated, and "
      "if it stays at an edge, the documents say so. The championship's frozen rung-5 inputs stay as frozen either way.")
    p("")
    pr = d["protocol"]
    p(f"Protocol: fit {pr['fit'][0]} to {pr['fit'][1]}, held-out score {pr['score'][0]} to {pr['score'][1]}, three-outcome "
      f"log-loss; the widened search takes c_θ in {{{', '.join(str(x) for x in pr['c_theta'])}}} at ω = {prev['chosen']['omega']}, "
      f"then ω in {{{', '.join(str(x) for x in pr['omega'])}}} at the chosen c_θ.")
    p("")
    p("## 2 Both searches")
    p("")
    p("| c_θ | ω | held-out log-loss (nats a game) | minus the chosen | held-out games | sweeps | search |")
    p("|---|---|---|---|---|---|---|")
    for k in sorted(rows):
        src, g = rows[k]
        mark = " (chosen)" if k == key(chosen) else ""
        p(f"| {g['c_theta']} | {g['omega']} | {g['log_loss']:.6f}{mark} | {g['log_loss'] - ll0:+.6f} | {g['games']:,} | "
          f"{g['sweeps']} | {src} |")
    p("")
    p(f"- **Reproduction.** The point ({prev['chosen']['c_theta']}, {prev['chosen']['omega']}), refitted, gives "
      f"{next(g for g in grid if key(g) == key(prev['chosen']))['log_loss']:.6f}, "
      f"{'equal to' if d['reproduces_previous_point'] else 'different from'} the first search's "
      f"{prev['chosen']['log_loss']:.6f}.")
    if moved:
        p(f"- **The optimum moves** from ({prev['chosen']['c_theta']}, {prev['chosen']['omega']}) to ({c0}, {w0}).")
    else:
        p(f"- **The optimum does not move:** ({c0}, {w0}) again has the lowest held-out log-loss.")
    edge_c = not below_c or not above_c
    edge_w = not below_w or not above_w
    p(f"- **c_θ.** {c0} is lower than " + ", ".join(f"{g['c_theta']} (at ω = {g['omega']}, {g['log_loss'] - ll0:+.6f})" for g in sorted(above_c, key=key))
      + " and than " + ", ".join(f"{g['c_theta']} (at ω = {g['omega']}, {g['log_loss'] - ll0:+.6f})" for g in sorted(below_c, key=key))
      + f": {'still at an edge' if edge_c else 'no longer at an edge'}. The values below {c0} were searched at "
      f"ω = {sorted({g['omega'] for g in below_c})[0] if below_c else '—'} and those above at ω = "
      f"{sorted({g['omega'] for g in above_c})[0] if above_c else '—'}, as the coordinate search of §4.6 runs.")
    gap = min(g["log_loss"] for g in below_w + above_w) - ll0 if below_w + above_w else None
    p(f"- **ω.** At c_θ = {c0}, {w0} is lower than " + ", ".join(f"{g['omega']} ({g['log_loss'] - ll0:+.6f})" for g in sorted(below_w + above_w, key=key))
      + f": {'still at an edge' if edge_w else 'no longer at an edge'}. The nearest value is worse by {gap:.6f} nats a "
      "game, so the held-out log-loss is flat in ω near the optimum: ω is weakly identified by these games.")
    p("")
    p("## 3 What R41 then requires")
    p("")
    if moved:
        p("The optimum moved inside the wider grid: E6's rung 5 test is rerun with it and rung 5's history figures are "
          "restated, each document saying which fit each figure uses; the championship's frozen rung-5 inputs stay.")
    elif edge_c or edge_w:
        p("The optimum stays at an edge of the widened grid; the documents say so, and the fit is unchanged.")
    else:
        p(f"The optimum stays at ({c0}, {w0}), now inside both widened grids, so Layer 1's history fit "
          "(`analysis/OUTPUT_L1_history.md`), E6's rung 5 test and the championship's frozen rung-5 inputs "
          "(`params/rung5_us2026.json`), each of which reads its hyperparameters from `analysis/aggregates/L1_history.json`, "
          "use the values the widened search confirms: nothing is rerun, and rung 5's history figures stand as E6 reports "
          "them [E6].")
    print("\n".join(P))


if __name__ == "__main__":
    main()
