#!/usr/bin/env python3
"""E16 report: rung 2 v2 under review (session ELO-6, Phase 5, after Freeze 3).

The red-team review of rung 2 v2, the narrowed guard and the proposal's section 10 (docs/review/REDTEAM_v1_0.md,
addendum of session ELO-6) found claims the evidence reports did not measure. This page measures them, so that the
documents cite numbers a committed script prints. It reads the frozen aggregates of E2, E11 and E12 without changing
them, the refit after the March 2024 compression (analysis/aggregates/E16_post_compression.json, written by
analysis/e16_post_compression_extract.py), the frozen parameter file params/table_fit_2026-10b.yaml, and runs
tools/compare_event_v3.py, unchanged, on the 2025 U.S. Championship; it also simulates title thresholds with the v2
table as the truth. Restated in session ELO-7 after ruling R44 withdrew R32 (docs/decisions/D-0012_pre-results-amendments.md):
every rung-2 figure is at today's K, and R32's K x m appears only where this page records what it did (sections 3, 7
and 8) and in section 9, which restates E12's figures at today's K. No 2026 championship result is read. Python
standard library only; deterministic.

Usage: python3 analysis/e16_rung2_review_report.py > docs/evidence/E16_rung2-under-review.md
"""
from __future__ import annotations

import dataclasses
import json
import math
import random
import sys
from decimal import Decimal
from pathlib import Path
from statistics import NormalDist

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(ROOT / "src"))
import compare_event as ce  # noqa: E402  (Freeze 1's tool, unchanged)
import compare_event_v3 as v3  # noqa: E402  (Freeze 3's tool, unchanged)
import compare_pilot as cp  # noqa: E402
import e11_table_by_level_report as r11  # noqa: E402  (E11's cell rule and Holm's procedure, unchanged)
from layer2 import table_v2 as t2  # noqa: E402

AGG = ROOT / "analysis" / "aggregates"
E2 = json.loads((AGG / "E2_broadcast.json").read_text(encoding="utf-8"))
E11 = json.loads((AGG / "E11_table_by_level.json").read_text(encoding="utf-8"))
E12 = json.loads((AGG / "E12_guard_v2.json").read_text(encoding="utf-8"))
E16 = json.loads((AGG / "E16_post_compression.json").read_text(encoding="utf-8"))
TEXT = (ROOT / "params" / "table_fit_2026-10b.yaml").read_text(encoding="utf-8")
V2 = {tc: t2.load(TEXT, tc) for tc in ("standard", "rapid", "blitz")}
TCS = ("standard", "rapid", "blitz")
BAND, ALPHA, POWER = 0.01, 0.05, 0.80
Z = NormalDist()
Z_POWER = Z.inv_cdf(POWER)
Y2025 = "tools/events/us_championship_2025.json"
P: list[str] = []
p = P.append


def model(tc: str) -> str:
    return "tail" if "tail" in E11["rolling"][tc] else "lambda"


def cells(tc: str, who: str) -> dict:
    return E11["rolling"][tc][model(tc)]["cells"][who]


def m_of(tc: str, mid: int) -> float:
    return float(V2[tc]["k_scale"][mid]) if V2[tc]["k_scale_applies"] else 1.0


def pooled(cs: dict, mids, gaps) -> dict:
    """Games-weighted mean of the cells' favourite residuals, its standard error with the cells taken as independent,
    and the K-free part of the yield, the games-weighted mean of m(L) times the residual."""
    rows = [(mid, gap, cs[f"{mid}|{gap}"]) for mid in mids for gap in gaps if f"{mid}|{gap}" in cs]
    rows = [(mid, gap, c) for mid, gap, c in rows if c.get("n")]
    n = sum(c["n"] for _, _, c in rows)
    if not n:
        return {"n": 0}
    mean = sum(c["n"] * c["mean"] for _, _, c in rows) / n
    se = math.sqrt(sum((c["n"] * c["se"]) ** 2 for _, _, c in rows if c.get("se"))) / n
    return {"n": n, "mean": mean, "se": se, "rows": rows}


def band_label(mid: int) -> str:
    return r11.band_label(mid)


# ------------------------------------------------------------------------------------------------ header
p("# E16 — Rung 2 v2 under review: playing down, colour, the tests' power, the compression, §10 and title thresholds")
p("")
p("Status: REVIEW — evidence for the proposal and annex (T3, T8, T10, T11; proposal §5, §8, §10, §14), session ELO-6, "
  "Phase 5, after Freeze 3, written in answer to the review of rung 2 v2, the narrowed guard and §10 "
  "(`docs/review/REDTEAM_v1_0.md`, addendum). Generated by `analysis/e16_rung2_review_report.py` from the aggregates of "
  "E2, E11 and E12 (frozen in Freeze 3 and read unchanged), from `analysis/aggregates/E16_post_compression.json` "
  "(written by `analysis/e16_post_compression_extract.py`, which refits the v2 table on games after the March 2024 "
  "compression), from `params/table_fit_2026-10b.yaml`, and with `tools/compare_event_v3.py` run unchanged on the 2025 "
  "U.S. Championship; do not edit by hand. Licence: CC BY 4.0 (`docs/LICENSE-docs.md`). Game data: the Lichess "
  "broadcast archive, CC BY-SA 4.0, attributed; aggregates only. No result of either 2026 championship is read. Nothing "
  "here changes a frozen file or the table: the refit of section 5 is shown beside Freeze 3, not in it. Restated in "
  "session ELO-7 after ruling R44 withdrew R32's K × m (`docs/decisions/D-0012_pre-results-amendments.md`): every "
  "rung-2 figure is at today's K; K × m appears only where the page records what it did (sections 3, 7 and 8), and "
  "section 9 restates E12's figures at today's K.")
p("")

# ------------------------------------------------------------------------------------------------ 1 playing down
p("## 1 Playing down outside the guard's region (standard)")
p("")
p("The favourite's residual S − E at published gaps of 100 to 399, below the guard's 400 (E2's 21 held-out months, "
  "E11's cells of level band × 50-point gap pooled by the games, the cells' cluster-robust standard errors combined as "
  "if independent), and what it is worth to a player who chooses such opponents: the expected points a game, K times "
  "the residual, at today's K (R44):")
p("")
GROUPS = (("1500–1999", (1550, 1650, 1750, 1850, 1950)), ("2000–2299", (2050, 2150, 2250)),
          ("2300–2799", (2350, 2450, 2550, 2650, 2750)), ("2400–2499 alone", (2450,)))
GAPS = (100, 150, 200, 250, 300, 350)
p("| level | games | residual: Layer 0 | Freeze 1's table | the v2 table | yield a game at K = 10: Layer 0 / Freeze 1 / v2 | at K = 20 | at K = 40 |")
p("|---|---|---|---|---|---|---|---|")
yields = {}
for lab, mids in GROUPS:
    res = {who: pooled(cells("standard", who), mids, GAPS) for who in ("l0", "v1", "v2")}
    v2m = res["v2"]["mean"]                                    # today's K: no factor m (R44)
    yields[lab] = (res, v2m)
    cols = []
    for k in (10, 20, 40):
        cols.append(f"{k * res['l0']['mean']:+.2f} / {k * res['v1']['mean']:+.2f} / {k * v2m:+.2f}")
    p(f"| {lab} | {res['v2']['n']:,} | {res['l0']['mean']:+.4f} | {res['v1']['mean']:+.4f} | "
      f"{res['v2']['mean']:+.4f} (SE {res['v2']['se']:.4f}) | " + " | ".join(cols) + " |")
p("")
top, bottom = yields["2300–2799"], yields["1500–1999"]
p(f"- **At the top** the v2 table cuts the residual from {top[0]['v1']['mean']:+.4f} to {top[0]['v2']['mean']:+.4f}: at "
  f"K = 10 the yield falls from {10 * top[0]['v1']['mean']:+.2f} to {10 * top[1]:+.2f} points a game; in band 2400–2499 "
  f"alone it is {10 * yields['2400–2499 alone'][1]:+.2f}.")
p(f"- **Below 2000** the v2 table creates an incentive Freeze 1's table did not have: the residual moves from "
  f"{bottom[0]['v1']['mean']:+.4f} to {bottom[0]['v2']['mean']:+.4f}, worth {20 * bottom[1]:+.2f} a game at K = 20 and "
  f"{40 * bottom[1]:+.2f} at K = 40 (Layer 0: {20 * bottom[0]['l0']['mean']:+.2f} and {40 * bottom[0]['l0']['mean']:+.2f}).")
p("- These are expected gains for a player who plays such fields on purpose; they are the residuals E11 tests, read in "
  "points. The simulator cannot show them: its true model is the v2 table itself (E14).")
p("")

# ------------------------------------------------------------------------------------------------ 2 colour
p("## 2 White's edge by level (standard)")
p("")
p("E2's descriptive table (all months 2023 to 2026-09, not held out): White's score in games between players at most 25 "
  "points apart, by 200-point level band, against the v2 table's White expectation at equal ratings (x = η = "
  f"{t2.eta_whole(V2['standard']['par'][2])}) averaged over the band's 100-point bands; the worth of a game with White "
  "beyond what the table prices is K × (score − expectation), at today's K (R44):")
p("")
LEVELS = (("1400", "below 1600", (1450, 1550)), ("1600", "1600–1799", (1650, 1750)), ("1800", "1800–1999", (1850, 1950)),
          ("2000", "2000–2199", (2050, 2150)), ("2200", "2200–2399", (2250, 2350)), ("2400", "2400–2599", (2450, 2550)),
          ("2600", "2600 or more", (2650, 2750, 2850)))
par = V2["standard"]["par"]
eta = t2.eta_whole(par[2])
p("| level | games within 25 points | White's score (SE) | the v2 table's White expectation | residual | worth at K = 10 | at K = 20 |")
p("|---|---|---|---|---|---|---|")
colour = {}
for key, lab, mids in LEVELS:
    allg, alld, n, ssum, d25 = E2["descriptive"]["standard"]["by_level_200"][key]
    sc = ssum / n
    wins = ssum - d25 / 2.0
    var = (wins + d25 / 4.0) / n - sc * sc
    se = math.sqrt(var / n)
    ev = sum(t2.expected_effective(eta, mid, par) for mid in mids) / len(mids)
    colour[lab] = (sc - ev, se)
    p(f"| {lab} | {n:,} | {sc:.3f} ({se:.3f}) | {ev:.3f} | {sc - ev:+.3f} | {10 * (sc - ev):+.2f} | {20 * (sc - ev):+.2f} |")
p("")
p("A level-dependent colour term is not part of SPEC-TABLE-FIT v1.1; on these games White's edge rises with the level "
  "while the fitted η is one number for every level. SPEC-TABLE-FIT v1.2 adds one at the next yearly fit if it improves "
  "held-out log-loss (R50).")
p("")

# ------------------------------------------------------------------------------------------------ 3 tolerance
p("## 3 T8.2's tolerance in points, at today's K and under the withdrawn K × m")
p("")
ms = [float(v) for v in V2["standard"]["k_scale"].values()]
p(f"A residual at the edge of the ±{BAND} tolerance is worth K × {BAND} points a game at today's K: {10 * BAND:.2f} at "
  f"K = 10, {20 * BAND:.2f} at K = 20 and {40 * BAND:.2f} at K = 40, so T8.2's tolerance is unchanged (R48). Under R32's "
  f"K × m, with standard's m from {min(ms):.2f} to {max(ms):.2f}, it was worth {10 * min(ms) * BAND:.2f} to "
  f"{10 * max(ms) * BAND:.2f} at K = 10, {20 * min(ms) * BAND:.2f} to {20 * max(ms) * BAND:.2f} at K = 20 and "
  f"{40 * min(ms) * BAND:.2f} to {40 * max(ms) * BAND:.2f} at K = 40: m raised K by {100 * (min(ms) - 1):.0f} % to "
  f"{100 * (max(ms) - 1):.0f} % in standard ({100 * (min(float(v) for tc in TCS for v in V2[tc]['k_scale'].values()) - 1):.0f} % to "
  f"{100 * (max(float(v) for tc in TCS for v in V2[tc]['k_scale'].values()) - 1):.0f} % over the three time controls), "
  "one of the reasons R44 withdrew it.")
p("")

# ------------------------------------------------------------------------------------------------ 4 power
p("## 4 Rule (a) by level band × gap: what the test can detect")
p("")
p(f"E11's rule (a) by cell tests every cell with at least {r11.MIN_CELL:,} test games against ±{BAND} (one-sided, "
  "cluster-robust standard error, Holm–Bonferroni at a familywise 5 %). The smallest deviation it detects with "
  f"{POWER:.0%} power is {BAND} + (z + {Z_POWER:.3f}) × SE, with z = {Z.inv_cdf(1 - ALPHA):.3f} for a single cell and "
  "z of Holm's first threshold, 0.05 divided by the number of cells, when every cell is tested together:")
p("")
p("| time control | cells tested | outside | SE of a cell | smallest detectable deviation, one cell | at Holm's first step | the closest cell: p against its Holm threshold |")
p("|---|---|---|---|---|---|---|")
for tc in TCS:
    rule = r11.cell_rule(cells(tc, "v2"))
    rows = rule["rows"]
    ses = [r["se"] for r in rows]
    z1 = Z.inv_cdf(1 - ALPHA)
    zh = Z.inv_cdf(1 - ALPHA / len(rows))
    best = min(rows, key=lambda r: r["p"])
    p(f"| {tc} | {len(rows)} | {len(rule['outside'])} | {min(ses):.4f} to {max(ses):.4f} | "
      f"{BAND + (z1 + Z_POWER) * min(ses):.3f} to {BAND + (z1 + Z_POWER) * max(ses):.3f} | "
      f"{BAND + (zh + Z_POWER) * min(ses):.3f} to {BAND + (zh + Z_POWER) * max(ses):.3f} | "
      f"{band_label(best['band'])} × {best['gap']}–{best['gap'] + 49}: {best['mean']:+.4f} (SE {best['se']:.4f}, "
      f"{best['n']:,} games), p = {best['p']:.6f} against {ALPHA / len(rows):.6f} |")
p("")
p("The largest residuals in cells too small to test (standard, 400 to 999 games):")
p("")
small = [(k, c) for k, c in cells("standard", "v2").items() if 400 <= c.get("n", 0) < r11.MIN_CELL]
small.sort(key=lambda kc: -abs(kc[1]["mean"]))
p("| cell | games | v2 residual (SE) |")
p("|---|---|---|")
for k, c in small[:5]:
    mid, gap = (int(v) for v in k.split("|"))
    p(f"| {band_label(mid)} × {gap}–{gap + 49} | {c['n']:,} | {c['mean']:+.4f} ({c['se']:.4f}) |")
p("")
p("By level band, pooled over gaps (E11 §6), the bands where the v2 table misses ±0.01 by more than Freeze 1's table "
  "did, standard:")
p("")
p("| band | games | Freeze 1's table | the v2 table (SE) |")
p("|---|---|---|---|")
b1 = E11["rolling"]["standard"][model("standard")]["bands"]
for mid in sorted(int(k) for k in b1["v2"]):
    a, b = b1["v1"][str(mid)], b1["v2"][str(mid)]
    if abs(b["mean"]) > BAND and abs(b["mean"]) > abs(a["mean"]):
        p(f"| {band_label(mid)} | {b['n']:,} | {a['mean']:+.4f} | {b['mean']:+.4f} ({b['se']:.4f}) |")
p("")

# ------------------------------------------------------------------------------------------------ 5 compression
p("## 5 The table refitted after the March 2024 compression")
p("")
p("On the March 2024 lists FIDE raised every rating below 2000 by round(0.4 × (2000 − R)) in all three time controls "
  "[E5]. E11's windows reach back before it: the published fit (2023-10 to 2026-09) holds five months on the old scale, "
  "the rolling fits up to 26. E16's extraction repeats E11's fits and evaluation with every window cut at 2024-03 (the "
  "rolling fits on max(t − 36, 2024-03) to t − 1; a fit on 2024-03 to 2026-09 in place of the published one), each with "
  "the model E11 published.")
p("")
p("| time control | fit | κ | λ | η | α | β | γ | μ | κ(L) at 1700–1799 / 2300–2399 / 2700–2799 |")
p("|---|---|---|---|---|---|---|---|---|---|")
for tc in TCS:
    f_pub = E11["final_fit"][tc][model(tc)]
    f_new = E16["fit"][tc]["params"]
    for lab, f in (("published, 2023-10 to 2026-09 (Freeze 3)", f_pub), ("after the compression, 2024-03 to 2026-09", f_new)):
        pr = tuple(f[k] for k in t2.NAMES)
        kl = " / ".join(f"{t2.kappa_at(pr, mid):.3f}" for mid in (1750, 2350, 2750))
        p(f"| {tc} | {lab} | {f['kappa']:.4f} | {f['lambda']:.4f} | {f['eta']:.2f} | {f['alpha']:.4f} | {f['beta']:.4f} | "
          f"{f['gamma']:.4f} | {f.get('mu', 0.0):.4f} | {kl} |")
p("")
p("The published fit's parameters against the range of E11's 21 rolling refits (standard):")
p("")
pm = E11["rolling"]["standard"][model("standard")]["per_month"]
fp = E11["final_fit"]["standard"][model("standard")]
for k in ("kappa", "lambda", "eta"):
    vals = [pm[m]["params_v2"][k] for m in pm]
    p(f"- {k}: published {fp[k]:.4f}; rolling refits {min(vals):.4f} to {max(vals):.4f}"
      f"{' (outside)' if not min(vals) <= fp[k] <= max(vals) else ''}.")
p("")
p("On the same 21 test months, the rolling fits cut at the compression against E11's:")
p("")
p("| time control | log-loss, refit minus E11's v2, nats a game | rule (a) by cell: cells outside | level bands outside ±0.01 (pooled over gaps) |")
p("|---|---|---|---|")
for tc in TCS:
    ev = E16["rolling"][tc]["evaluation"]
    old = E11["rolling"][tc][model(tc)]
    n = sum(ev["per_month"][m]["n"] for m in ev["per_month"])
    d = (sum(ev["per_month"][m]["ll_v2"] for m in ev["per_month"]) - sum(old["per_month"][m]["ll_v2"] for m in old["per_month"])) / n
    rule_new, rule_old = r11.cell_rule(ev["cells"]["v2"]), r11.cell_rule(old["cells"]["v2"])
    lp_new, lp_old = ev["level_pattern"], old["level_pattern"]
    n_new = sum(1 for b in lp_new["bands_tested"] if b["outside"])
    n_old = sum(1 for b in lp_old["bands_tested"] if b["outside"])
    p(f"| {tc} | {d:+.5f} | {len(rule_new['outside'])} of {rule_new['m']} (E11: {len(rule_old['outside'])} of {rule_old['m']}) | "
      f"{n_new} of {len(lp_new['bands_tested'])} (E11: {n_old} of {len(lp_old['bands_tested'])}) |")
p("")
for tc in TCS:
    lpn = E16["rolling"][tc]["evaluation"]["level_pattern"]["bands_tested"]
    lpo = E11["rolling"][tc][model(tc)]["level_pattern"]["bands_tested"]
    names = lambda bs: ", ".join(band_label(b["band"]) for b in bs if b["outside"]) or "none"  # noqa: E731
    p(f"- {tc}: level bands significantly outside ±0.01 (E11's level-pattern test): E11's v2 table {names(lpo)}; the refit "
      f"{names(lpn)}.")
p("")
p("By level band, standard (the favourite's residual pooled over gaps; Freeze 1's table, E11's v2 table, the refit):")
p("")
p("| band | games | Freeze 1's table | E11's v2 table | refit after the compression |")
p("|---|---|---|---|---|")
bn = E16["rolling"]["standard"]["evaluation"]["bands"]
for mid in sorted(int(k) for k in bn["v2"]):
    a, b, c = b1["v1"][str(mid)], b1["v2"][str(mid)], bn["v2"][str(mid)]
    p(f"| {band_label(mid)} | {c['n']:,} | {a['mean']:+.4f} | {b['mean']:+.4f} | {c['mean']:+.4f} ({c['se']:.4f}) |")
p("")

# ------------------------------------------------------------------------------------------------ 6 R24 (i)
p("## 6 R24's rule (i) and the guard's reach")
p("")
p("Rule (i), read strictly (D-0011, reading 4), keeps no guard only if the 95 % interval of the favourite's residual in "
  "the farming region lies inside ±0.01. The interval's width depends on the games, not on the residual: with the "
  "region's per-game spread s (its cluster-robust standard error times √n), the interval fits only from n = "
  "(1.96 s / (0.01 − |r|))² games, r the residual:")
p("")
p("| time control | games in the region | cluster-robust SE | s | interval width now | games needed, r = 0 | at the observed r | with the guard: players' interval, inside ±0.01? |")
p("|---|---|---|---|---|---|---|---|")
for tc in TCS:
    reg = E12["static"][tc]["region"]
    v2r = reg["v2"]
    s = v2r["se"] * math.sqrt(v2r["n"])
    r = v2r["mean"]
    need0 = (1.96 * s / BAND) ** 2
    needr = (1.96 * s / (BAND - abs(r))) ** 2 if abs(r) < BAND else None
    g = reg["guarded"]["players"]
    verdict = "significantly below" if g["hi"] < -BAND else "significantly above" if g["lo"] > BAND else "not significantly outside"
    p(f"| {tc} | {v2r['n']:,} | {v2r['se']:.5f} | {s:.3f} | {2 * 1.96 * v2r['se']:.3f} | {need0:,.0f} | "
      f"{'never (|r| ≥ 0.01)' if needr is None else f'{needr:,.0f} (r = {r:+.4f})'} | "
      f"{reg['guarded']['mean']:+.4f} ({g['lo']:+.4f} to {g['hi']:+.4f}): {verdict} |")
p("")
cnt = E12["static"]["standard"]["counts"]
p(f"- **Reach.** The region needs a level of 2300 or more and a gap of 400 or more, so a favourite rated 2500 or more; "
  f"full weight needs 2575 (a gap of 450 at a level of 2350). In standard {cnt['region_full_weight']:,} of the "
  f"{cnt['region']:,} region games carry full weight, and the guard binds in {cnt['region_binds']:,} [E12].")
p("")

# ------------------------------------------------------------------------------------------------ 7 2025
p("## 7 Section 10's columns on the 2025 U.S. Championship")
p("")
event = ce.load_event(Y2025)
chapter = event["event"]["chapter"]
r2 = v3.load_rung2(v3.DEFAULT_TABLE, v3.DEFAULT_GUARD, chapter)
v1 = ce.load_params(ce.DEFAULT_PARAMS, chapter)
rung5 = cp.load_rung5(v3.DEFAULT_RUNG5, Y2025)
cm = v3.compare(event, r2, v1, rung5)
cn = v3.compare(event, dataclasses.replace(r2, scaled=False), v1, rung5)
by_n = {r["fide_id"]: r for r in cn.rows}
cols = (("(b): the v2 table, the guard and K × m (the column as frozen)", lambda r: r["b"], lambda r: r["b_rounded"]),
        ("(b′): the v2 table and the narrowed guard at today's K (Freeze 3a, D-0012: §10's main column)",
         lambda r: by_n[r["fide_id"]]["b"], lambda r: by_n[r["fide_id"]]["b_rounded"]),
        ("(b0): Freeze 2's column (first pre-registration, superseded)", lambda r: r["b0"], lambda r: r["b0_rounded"]))
p(f"With 2025's results ({cm.counted} games), per player against column (a) (FIDE's rules by Layer 0):")
p("")
p("| column | mean of \\|x − (a)\\| | x − (a) of largest absolute value | players whose rounded change differs from (a) |")
p("|---|---|---|---|")
for lab, fx, fr in cols:
    d = [fx(r) - r["a"] for r in cm.rows]
    big = max(d, key=abs)
    p(f"| {lab} | {sum(abs(x) for x in d) / len(d):.2f} | {big:+.2f} | {sum(1 for r in cm.rows if fr(r) != r['a_rounded'])} of {len(cm.rows)} |")
p("")
p("The same 2025 event with the four columns of §10 side by side (D-0012), (a) among them, and the size of each column's "
  "changes:")
p("")
four = (("(a) FIDE's rules", lambda r: r["a"], lambda r: r["a_rounded"]), ("(b′), the main column", cols[1][1], cols[1][2]),
        ("(b), Freeze 3, K × m", cols[0][1], cols[0][2]), ("(b0)", cols[2][1], cols[2][2]))
p("| 2025 U.S. Championship | " + " | ".join(lab for lab, _f, _r in four) + " |")
p("|---|---|---|---|---|")
p("| mean of \\|x\\| over the players, unrounded, points | " + " | ".join(
    f"{sum(abs(fx(r)) for r in cm.rows) / len(cm.rows):.2f}" for _l, fx, _r in four) + " |")
p("| mean of \\|x − (a)\\| over the players, unrounded, points | — | " + " | ".join(
    f"{sum(abs(fx(r) - r['a']) for r in cm.rows) / len(cm.rows):.2f}" for _l, fx, _r in four[1:]) + " |")
p("| x − (a) of largest absolute value, signed, unrounded | — | " + " | ".join(
    f"{max((fx(r) - r['a'] for r in cm.rows), key=abs):+.2f}" for _l, fx, _r in four[1:]) + " |")
p("| players whose rounded change differs from (a) | — | " + " | ".join(
    f"{sum(1 for r in cm.rows if fr(r) != r['a_rounded'])} of {len(cm.rows)}" for _l, _f, fr in four[1:]) + " |")
p("")
lead = max(cm.rows, key=lambda r: abs(r["b"] - r["a"]))
tab = by_n[lead["fide_id"]]["b"] - lead["a"]
p(f"The largest (b) − (a), {lead['b'] - lead['a']:+.2f}, splits into {tab:+.2f} from the table at today's K and "
  f"{lead['b'] - lead['a'] - tab:+.2f} from m; over the twelve players m alone accounts for "
  f"{sum(abs(r['b'] - by_n[r['fide_id']]['b']) for r in cm.rows) / len(cm.rows):.2f} of the mean "
  f"{sum(abs(r['b'] - r['a']) for r in cm.rows) / len(cm.rows):.2f} (mean of |(b) − the table at today's K|). Column (b) "
  "would therefore have read mostly as R32's factor m, and (b) against (b0) as m against Freeze 1's table; before any "
  "2026 result was read, D-0012 withdrew R32 (R44) and added (b′), the v2 table and the narrowed guard at today's K, as "
  "§10's main column (R45), which E13 prints beside (b) and (b0).")
p("")

# ------------------------------------------------------------------------------------------------ 8 titles
p("## 8 Title thresholds: today's K and the withdrawn K × m")
p("")
RUNS, GAMES_A_MONTH, MONTHS = 40000, 9, 3
p(f"A title needs a rating achieved at some time, which may be obtained in the middle of a rating period or of a "
  f"tournament (Title Regulations §1.5.3 a) [VT 1]). Simulated: a player whose strength equals the rating plays "
  f"{GAMES_A_MONTH} games a month for {MONTHS} months against opponents of the same rating and strength, colours "
  "alternating; results drawn from the v2 table (the truth), the expectation read from the published v2 table, the "
  "interim rating the published rating plus the period's game terms so far, the period's change rounded once (§8.3.4 "
  f"[V 1]); the share of {RUNS:,} runs in which the interim or the published rating reaches the threshold, at today's K "
  "and with R32's K × m (the same results for both):")
p("")


def touch(r0: int, k: int, threshold: int, seed: int) -> tuple[float, float, float]:
    rnd = random.Random(seed)
    mid0 = t2.band_mid(r0)
    pw, pd, _pl = t2.probs(par, 0, mid0)                      # White's probabilities at equal strength (η inside)
    cache: dict = {}

    def expect(x: int, mid: int) -> float:
        key = (x, mid)
        if key not in cache:
            cache[key] = float(t2.published(x, mid, par))
        return cache[key]
    hits = [0, 0]
    for _ in range(RUNS):
        draws = [rnd.random() for _ in range(GAMES_A_MONTH * MONTHS)]
        for j, scaled in enumerate((False, True)):
            rating, reached, i = r0, False, 0
            for _month in range(MONTHS):
                acc = 0.0
                for _g in range(GAMES_A_MONTH):
                    white = i % 2 == 0
                    u = draws[i]
                    i += 1
                    if white:
                        s = 1.0 if u < pw else 0.5 if u < pw + pd else 0.0
                    else:
                        s = 0.0 if u < pw else 0.5 if u < pw + pd else 1.0
                    mid = t2.band_mid((rating + r0) // 2)
                    x = rating - r0 + (eta if white else -eta)
                    m = m_of("standard", mid) if scaled else 1.0
                    acc += k * m * (s - expect(x, mid))
                    if rating + acc >= threshold:
                        reached = True
                change = math.floor(abs(acc) + 0.5) * (1 if acc >= 0 else -1)
                rating += change
                if rating >= threshold:
                    reached = True
            hits[j] += reached
    return hits[0] / RUNS, hits[1] / RUNS, m_of("standard", mid0)


p("| starting rating (= strength) | K | threshold | rung 2 at today's K (R48) | rung 2 with K × m (R32, withdrawn) | m of the band |")
p("|---|---|---|---|---|---|")
for r0, k, thr, seed in ((2470, 10, 2500, 20261010), (2480, 10, 2500, 20261011), (2370, 20, 2400, 20261012)):
    a, b, m = touch(r0, k, thr, seed)
    p(f"| {r0} | {k} | {thr} | {a:.3f} | {b:.3f} | {m:.2f} |")
p("")
p(f"Each share has a standard error of at most {0.5 / math.sqrt(RUNS):.4f}. Under R32's K × m the interim rating moved by "
  "K × m a game, so thresholds were touched more often without playing better; R44 withdrew it, and under R48 an "
  "interim rating under rung 2 uses today's K.")

# ------------------------------------------------------------------------------------------------ 9 E12 at today's K
p("")
p("## 9 E12's figures at today's K (R44)")
p("")
p("E12, frozen in Freeze 3, printed the farmer's yield in the farming region with R32's K × m. At today's K the yield a "
  "game is K times the favourite's residual in the region (E12 §3; players' intervals in brackets), at K = 10, the K of "
  "every player rated 2400 or more today [V 1]:")
p("")
p("| time control | games in the region | v2 table: residual, yield at K = 10 | with the narrowed guard: residual, yield at K = 10 | E12's yield with K × m, v2 / guarded |")
p("|---|---|---|---|---|")
for tc in TCS:
    reg = E12["static"][tc]["region"]
    v, g = reg["v2"], reg["guarded"]
    m24 = m_of(tc, 2450)
    p(f"| {tc} | {v['n']:,} | {v['mean']:+.4f} ({v['players']['lo']:+.4f} to {v['players']['hi']:+.4f}), {10 * v['mean']:+.2f} | "
      f"{g['mean']:+.4f} ({g['players']['lo']:+.4f} to {g['players']['hi']:+.4f}), {10 * g['mean']:+.2f} | "
      f"{10 * m24 * v['mean']:+.2f} / {10 * m24 * g['mean']:+.2f} (m = {m24:.2f}) |")
p("")
r32 = E12["r32"]
p("E12 §6 also tested R32's scaling with ratings carried forward on broadcast games (scaled minus unscaled log-loss, "
  "nats a game, month-block interval): " + "; ".join(
      f"{tc} {r32[tc]['log_loss_difference']['mean']:+.5f} ({r32[tc]['log_loss_difference']['lo']:+.5f} to "
      f"{r32[tc]['log_loss_difference']['hi']:+.5f})" for tc in TCS)
  + ". Worse in standard and blitz with the interval above zero, it is one of the reasons R44 withdrew R32; rung 2 now "
  "uses the unscaled K, which is today's.")
print("\n".join(P))
