#!/usr/bin/env python3
"""E1 report: prints docs/evidence/E1_fide-lists.md from the committed list aggregates.

Reads analysis/aggregates/E1_standard.json, E1_rapid.json and E1_blitz.json (written
by analysis/e1_fide_lists_extract.py from FIDE's monthly lists, which are never
committed) and prints the evidence page; check (a) reruns it on every pull request.
Python standard library only.

Usage: python3 analysis/e1_fide_lists_report.py > docs/evidence/E1_fide-lists.md
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TCS = ("standard", "rapid", "blitz")
BEFORE = [f"{y}-02" for y in range(2016, 2024)]           # February to February, ending by February 2024
AFTER = ["2024-03", "2025-03", "2025-10"]                  # from the first list after the March 2024 change


def load(tc: str) -> dict:
    return json.loads((ROOT / "analysis" / "aggregates" / f"E1_{tc}.json").read_text(encoding="utf-8"))


def frat(v) -> str:
    """A rating or a median rating: no thousands separator."""
    if v is None:
        return "-"
    return f"{v:g}" if isinstance(v, float) else str(v)


def fmt(v) -> str:
    if v is None:
        return "-"
    if isinstance(v, float):
        return f"{v:g}"
    return f"{v:,}" if isinstance(v, int) else str(v)


def main() -> int:
    d = {tc: load(tc) for tc in TCS}
    std = d["standard"]
    drift = {tc: {x["start"]: x for x in d[tc]["anchor_drift"]} for tc in TCS}
    print("# E1 — FIDE's monthly lists, February 2015 to October 2026\n")
    print("Status: REVIEW — evidence for the proposal (§1, §2) and annex T8 (session ELO-3, Phase 4.1). Generated by "
          "`analysis/e1_fide_lists_report.py` from `analysis/aggregates/E1_standard.json`, `E1_rapid.json` and "
          "`E1_blitz.json`, which `analysis/e1_fide_lists_extract.py` computes from FIDE's lists; the lists are "
          "analysed and never committed or redistributed [V 3]. Do not edit by hand. Licence: CC BY 4.0 "
          "(`docs/LICENSE-docs.md`).\n")
    print("## Source and definitions\n")
    print(f"- FIDE's monthly standard, rapid and blitz lists, {std['first_list']} to {std['last_list']}: "
          f"{std['n_lists']} lists each, with {fmt(d['standard']['n_ids'])}, {fmt(d['rapid']['n_ids'])} and "
          f"{fmt(d['blitz']['n_ids'])} distinct FIDE IDs rated at least once [V 3].")
    print(f"- Anchor cohort (PROVISIONAL), for a 12-month window from list s to list s + 12: aged 25 to 45 in the "
          f"calendar year of s, rated and not flagged inactive on both lists, with at least {std['min_games']} rated "
          f"games in the window and at least {std['min_games']} in the 12 lists up to s. Drift is the median of "
          "R(s + 12) − R(s), also split at a rating of 2000 on list s.")
    print("- Windows that contain the March 2024 list are left out: on that list FIDE raised every rating below 2000 "
          "once, by 0.40 × (2000 − R), and moved the floor from 1000 to 1400 [R §2].")
    print("- Newcomer: an ID on a list and on no earlier list since February 2015, counted from February 2016. "
          "Exit: an ID on one list and absent from the next.\n")

    print("## (i) Anchor-cohort drift\n")
    print("Median annual change of the anchor cohort's published ratings, points per year (cohort size in brackets):\n")
    print("| window | standard | below 2000 | from 2000 | rapid | blitz |")
    print("|---|---|---|---|---|---|")
    for s in BEFORE + AFTER:
        row = drift["standard"].get(s)
        if not row:
            continue
        cells = [f"{frat(row['all']['median'])} ({fmt(row['all']['n'])})", frat(row["below_2000"]["median"]),
                 frat(row["from_2000"]["median"])]
        for tc in ("rapid", "blitz"):
            r = drift[tc].get(s)
            cells.append(f"{frat(r['all']['median'])} ({fmt(r['all']['n'])})" if r else "-")
        print(f"| {s} to {row['end']} | " + " | ".join(cells) + " |")
    pre = [drift["standard"][s]["all"]["median"] for s in BEFORE if s in drift["standard"]]
    post = [drift["standard"][s]["all"]["median"] for s in AFTER if s in drift["standard"]]
    print(f"\nStandard: the cohort's median change ranged from {frat(min(pre))} to {frat(max(pre))} points a year in "
          f"the eight windows before March 2024 and from {frat(min(post))} to {frat(max(post))} in the three windows "
          "after it. The research report cites an independent study of 954,805 games with a median loss of 26 points "
          "a year before the reform and 16 after it [R 5]; the populations and methods differ (that study follows "
          "active players' results, this follows the published ratings of a fixed adult cohort), so the figures are "
          "shown side by side, not reconciled.\n")

    print("## (ii) The 1400 floor\n")
    floor = {x["list"]: x for x in std["floor"]}
    lists = ["2024-03", "2024-10", "2025-10", "2026-10"]
    print("Standard list, players at each rating from 1400 to 1409 (the floor in force since March 2024 [V 1]):\n")
    print("| list | lowest rating | " + " | ".join(str(1400 + i) for i in range(10)) + " |")
    print("|---|---|" + "---|" * 10)
    for l in lists:
        f = floor[l]
        print(f"| {l} | {f['min_rating']} | " + " | ".join(fmt(v) for v in f["one_point_bins_from_floor_20"][:10]) + " |")
    print("\nPlayers per 10-point band from 1400 to 1599, October 2026 lists:\n")
    print("| list | " + " | ".join(f"{1400 + 10 * i}" for i in range(0, 20, 2)) + " |")
    print("|---|" + "---|" * 10)
    for tc in TCS:
        f = {x["list"]: x for x in d[tc]["floor"]}["2026-10"]
        print(f"| {tc} | " + " | ".join(fmt(f["bins_1400_1599"][i]) for i in range(0, 20, 2)) + " |")
    print("\nExits (players on a list and absent from the next), standard, summed by year of the later list:\n")
    print("| year | last rating below 1450 | 1450–1599 | 1600 or more |")
    print("|---|---|---|---|")
    by_year: dict[str, list[int]] = {}
    for e in std["exits"]:
        y = e["list"][:4]
        c = e["exits_by_last_rating"]
        acc = by_year.setdefault(y, [0, 0, 0])
        acc[0] += c["<1450"]
        acc[1] += c["1450-1599"]
        acc[2] += c["1600+"]
    for y in sorted(by_year):
        if y >= "2023":
            print(f"| {y} | {fmt(by_year[y][0])} | {fmt(by_year[y][1])} | {fmt(by_year[y][2])} |")
    apr = next(e for e in std["exits"] if e["list"] == "2026-04")
    apr_n = sum(apr["exits_by_last_rating"].values())
    mar_new = next(x for x in std["newcomers"] if x["list"] == "2026-03")["n_new"]
    usual = sorted(sum(e["exits_by_last_rating"].values()) for e in std["exits"] if "2025-04" <= e["list"] <= "2026-03")
    print(f"\nOne list stands out: {fmt(apr_n)} IDs left the standard list in April 2026 (the twelve lists before it "
          f"lost {fmt(usual[0])} to {fmt(usual[-1])} each). {fmt(apr['exits_first_listed_on_previous_list'])} of them had "
          f"first been listed in March 2026, when the list gained {fmt(mar_new)} newcomers. The regulations remove a "
          "rating when it falls below 1400 (§7.2.1 [V 1]), but "
          f"{fmt(apr['exits_by_last_rating']['1450-1599'] + apr['exits_by_last_rating']['1600+'])} of these players "
          "were rated 1450 or more on the March list, so a fall below the floor in one month explains few of them. The "
          "lists do not say why; this is recorded as a FIDE-side event for the architect.")
    f26 = floor["2026-10"]["one_point_bins_from_floor_20"]
    print(f"\nOn the published lists there is no excess of players at the floor: on the October 2026 standard list "
          f"{fmt(f26[0])} players are rated exactly 1400 against {fmt(min(f26[1:10]))} to {fmt(max(f26[1:10]))} at "
          "each of the next nine points, and the number per band rises from 1400 upwards in all three lists. The "
          "research report describes \"an artificial pile-up at 1400\" after the reform [R 3] [R 4]; a list cannot "
          "show players below the floor, who leave it (the exits above), so the two observations can both hold.\n")

    print("## (iii) Newcomers by age and rating\n")
    print("New IDs per calendar year with their median first rating (standard), by age in the list year:\n")
    ages = ["<10", "10-14", "15-19", "20-29", "30-49", "50+", "unknown"]
    print("| year | lists | newcomers | median first rating | below 1400 | " + " | ".join(ages) + " |")
    print("|---|---|---|---|---|" + "---|" * len(ages))
    for y, v in std["newcomers_by_year"].items():
        cells = []
        for a in ages:
            s = v["by_age"].get(a)
            cells.append(f"{fmt(s['n'])} ({frat(s['median'])})" if s else "-")
        print(f"| {y} | {v['lists']} | {fmt(v['n'])} | {frat(v['median_rating'])} | {fmt(v['below_1400'])} | "
              + " | ".join(cells) + " |")
    print("\nNewcomers per year and median first rating, rapid and blitz:\n")
    print("| year | rapid | rapid median | blitz | blitz median |")
    print("|---|---|---|---|---|")
    for y in std["newcomers_by_year"]:
        r, b = d["rapid"]["newcomers_by_year"].get(y), d["blitz"]["newcomers_by_year"].get(y)
        print(f"| {y} | {fmt(r['n']) if r else '-'} | {frat(r['median_rating']) if r else '-'} | "
              f"{fmt(b['n']) if b else '-'} | {frat(b['median_rating']) if b else '-'} |")
    ny = std["newcomers_by_year"]
    print(f"\nStandard newcomers' median first rating was {frat(ny['2023']['median_rating'])} in 2023 and "
          f"{frat(ny['2025']['median_rating'])} in 2025; since the floor became 1400 no first rating is below it "
          f"(2025: {fmt(ny['2025']['below_1400'])} of {fmt(ny['2025']['n'])}). 2026 covers {ny['2026']['lists']} "
          f"lists and includes the {fmt(mar_new)} newcomers of March 2026, most of whom left the list in April (section "
          "ii). 2020 and 2021 are the pandemic years.\n")

    print("## (iv) The K distribution\n")
    print("Players by published K on the October lists, standard (all rated players / those with rated games in "
          "the period):\n")
    print("| list | K 40 | K 20 | K 10 | other |")
    print("|---|---|---|---|---|")
    kd = {x["list"]: x for x in std["k_distribution"]}
    for y in range(2016, 2027):
        x = kd.get(f"{y}-10")
        if not x:
            continue
        a, p = x["all"], x["played_this_period"]
        other_a = sum(v for k, v in a.items() if k not in ("10", "20", "40"))
        other_p = sum(v for k, v in p.items() if k not in ("10", "20", "40"))
        print(f"| {y}-10 | {fmt(a.get('40', 0))} / {fmt(p.get('40', 0))} | {fmt(a.get('20', 0))} / "
              f"{fmt(p.get('20', 0))} | {fmt(a.get('10', 0))} / {fmt(p.get('10', 0))} | {fmt(other_a)} / {fmt(other_p)} |")
    print("\nOctober 2026, all three lists (all rated players):\n")
    print("| list | K 40 | K 20 | K 10 | other | share with K 40 |")
    print("|---|---|---|---|---|---|")
    for tc in TCS:
        a = {x["list"]: x for x in d[tc]["k_distribution"]}["2026-10"]["all"]
        tot = sum(a.values())
        other = sum(v for k, v in a.items() if k not in ("10", "20", "40"))
        print(f"| {tc} | {fmt(a.get('40', 0))} | {fmt(a.get('20', 0))} | {fmt(a.get('10', 0))} | {fmt(other)} | "
              f"{a.get('40', 0) / tot:.1%} |")
    print("\nWhich rule produces which K is measured in `analysis/OUTPUT_L0_k_rules.md` (SPEC-L0 R-22).\n")

    print("## Limits\n")
    print("- The lists carry no games: drift here is the movement of published ratings for a cohort whose strength "
          "is assumed stable (adults aged 25 to 45), not a measurement of strength. The anchor of annex T4.5 needs "
          "Layer 1.")
    print("- The cohort excludes players flagged inactive and requires ten games in each of two 12-month windows; "
          "2020 and 2021 have small cohorts.")
    print("- Newcomers are IDs new to the lists since February 2015, with a one-year burn-in: a returning player "
          "first rated before 2015 and absent since counts as new.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
