#!/usr/bin/env python3
"""E3: the 2026 U.S. Championships under FIDE's rules and under rung 2; prints docs/evidence/E3_us-championship-2026.md.

Runs tools/compare_event.py (docs/specs/SPEC-COMPARE_v1_0.md) on the committed event
files (tools/events/) with params/table_fit_2026-10.yaml, and prints the evidence page.
Rerun after each round (tools/README.md). Python standard library only.

Usage: python3 analysis/e3_us_championships.py > docs/evidence/E3_us-championship-2026.md
"""
from __future__ import annotations

import sys
from collections import Counter
from itertools import combinations
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
import compare_event  # noqa: E402

OPEN, WOMEN, Y2025 = ("tools/events/us_championship_2026.json", "tools/events/us_womens_championship_2026.json",
                      "tools/events/us_championship_2025.json")
PAGE = "https://saintlouischessclub.org/event/2026-us-chess-championships/"


def is_round_robin(event: dict) -> bool:
    ids = sorted(p["fide_id"] for p in event["players"])
    games = event["games"]
    pairs = Counter(frozenset((g["white"], g["black"])) for g in games)
    once = set(pairs) == {frozenset(c) for c in combinations(ids, 2)} and set(pairs.values()) == {1}
    rounds = sorted({g["round"] for g in games})
    per_round = all(sorted(p for g in games if g["round"] == r for p in (g["white"], g["black"])) == ids for r in rounds)
    whites = Counter(g["white"] for g in games)
    return once and per_round and set(whites.values()) <= {5, 6}


def status(event: dict) -> tuple[int, list[int]]:
    done = sum(1 for g in event["games"] if g["result"])
    complete = [r for r in sorted({g["round"] for g in event["games"]})
                if all(g["result"] for g in event["games"] if g["round"] == r)]
    return done, complete


def table(path: str) -> tuple[str, compare_event.Comparison]:
    event = compare_event.load_event(path)
    c = compare_event.compare(event, compare_event.load_params(compare_event.DEFAULT_PARAMS, event["event"]["chapter"]))
    return compare_event.to_markdown(c), c


def main() -> int:
    o_md, o = table(OPEN)
    w_md, w = table(WOMEN)
    y_md, y = table(Y2025)
    print("# E3 — The 2026 U.S. Championships under FIDE's rules and under rung 2\n")
    print("Status: DRAFT — not for publication; the event is in progress (session ELO-3, Phase 5.3). Generated by "
          "`analysis/e3_us_championships.py` with `tools/compare_event.py` (`docs/specs/SPEC-COMPARE_v1_0.md`) from "
          "the event files in `tools/events/` and `params/table_fit_2026-10.yaml`; do not edit by hand. Licence: CC BY "
          "4.0 (`docs/LICENSE-docs.md`).\n")
    print("## The event, confirmed\n")
    print(f"- Source: the Saint Louis Chess Club's official event page ({PAGE}), read on 2026-10-09 at about 19:53 UTC "
          "through a web reader; a direct download was refused with HTTP 403. Published sources disagreed on the "
          "dates (8–23, 9–22 and 10–24 October, per the ELO-3 brief).")
    print("- Dates on the official page: 7 to 23 October 2026 in all; rounds 1–4 on 9–12 October, a rest day on 13 "
          "October, rounds 5–8 on 14–17 October, a rest day on 18 October, rounds 9–11 on 19–21 October, a playoff on "
          "22 October if necessary.")
    for name, c in (("U.S. Championship", o), ("U.S. Women's Championship", w)):
        print(f"- {name}: {len(c.event['players'])} players, 11 rounds; the official pairings form a complete round "
              f"robin (each pair once, every player once a round, 5 or 6 Whites each): {is_round_robin(c.event)}.")
    print("- Players are identified by FIDE ID, with the rating and K of FIDE's October 2026 standard list, the list in "
          "force at the start (SPEC-L0 R-11a). Their names are on the official page; the repository does not store "
          "them. Both events end by 22 October and are rated on the November 2026 list (R-09).\n")
    print("## Status of play\n")
    for name, c in (("U.S. Championship", o), ("U.S. Women's Championship", w)):
        done, complete = status(c.event)
        print(f"- {name}: {done} of {len(c.event['games'])} games have a result; complete rounds: "
              f"{', '.join(map(str, complete)) or 'none yet'}.")
    print("\n## The check: the 2025 U.S. Championship\n")
    print(f"Column (a) must equal FIDE's per-event calculation (SPEC-COMPARE §4); `tests/test_compare_event.py` asserts "
          f"it for all {len(y.rows)} players against `tests/fixtures/validation/us_championship_2025.json`, the "
          "fixture of E0.\n")
    print(y_md)
    diffs = [r["difference"] for r in y.rows]
    print(f"In 2025, rung 2 would have changed the twelve players' gains from the event by {min(diffs):+.2f} to "
          f"{max(diffs):+.2f} points against FIDE's rules, with the same K and the same results.\n")
    print("## 2026 U.S. Championship\n")
    print(o_md)
    print("## 2026 U.S. Women's Championship\n")
    print(w_md if w.counted else "No game has a result yet; the table fills as rounds are recorded.\n")
    print("## Reminder\n")
    print("FIDE's official changes for both events will appear on the 1 November 2026 standard list. Layer 0, column "
          "(a), must match them for every player once the players' other events in the October period are added, as "
          "E0 does for 2025 (`docs/evidence/E0_l0-validation.md`). A mismatch is a finding about Layer 0 or about "
          "FIDE's data (SPEC-L0 §8), never a reason to edit column (a).\n")
    print("## Rerun after each round\n")
    print("Enter the round's results from the official page, board by board, then regenerate this page "
          "(`tools/README.md`):\n")
    print("```")
    print("python3 tools/set_results.py tools/events/us_championship_2026.json ROUND R1 R2 R3 R4 R5 R6 && "
          "python3 analysis/e3_us_championships.py > docs/evidence/E3_us-championship-2026.md")
    print("```")
    return 0


if __name__ == "__main__":
    sys.exit(main())
