#!/usr/bin/env python3
"""E4 report: the community register (ELO-4, Phase 2) from analysis/community/register.json.

The register holds what was read, January 2023 to September 2026: every source
item (thread, article, statement, book) with the themes it raises, coded on a
fixed list, each with a one-line paraphrase (no quotation over 15 words), the
number of distinct authors raising it where visible, and its stance; every fetch
attempted, including refusals; and the project's disposition of each theme.
This script counts and prints; it adds no judgement of its own. Python standard
library only.

Usage: python3 analysis/e4_community_report.py > docs/evidence/E4_community-register.md
"""
from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
REG = ROOT / "analysis" / "community" / "register.json"
POPULAR_SHARE = 0.10      # a theme is popular when at least 10 % of coded items raise it (PROVISIONAL)
LINKS_PER_THEME = 10


def domain(url: str) -> str:
    host = urlparse(url).netloc.lower()
    return host[4:] if host.startswith("www.") else host


def longest_quote(text: str) -> int:
    quotes = re.findall(r"[\"“]([^\"”]+)[\"”]", text)
    return max((len(q.split()) for q in quotes), default=0)


def main() -> None:
    reg = json.loads(REG.read_text(encoding="utf-8"))
    tax = reg["taxonomy"]
    items = reg["items"]
    disp = reg["dispositions"]
    coded = [it for it in items if it["themes"]]
    n_coded = len(coded)
    by_theme: dict[str, list] = defaultdict(list)
    for it in coded:
        for th in it["themes"]:
            by_theme[th["code"]].append((it, th))
    for code, lst in by_theme.items():
        for it, th in lst:
            assert longest_quote(th["paraphrase"]) <= 15, (it["id"], code)
    stats = []
    for code in tax:
        lst = by_theme.get(code, [])
        ids = {it["id"] for it, _ in lst}
        fams = sorted({it["family"] for it, _ in lst})
        authors = sum(th["authors"] for _, th in lst if isinstance(th.get("authors"), int))
        stance = Counter(th["stance"] for _, th in lst)
        stats.append({"code": code, "items": len(ids), "families": fams, "authors": authors, "stance": stance})
    stats.sort(key=lambda s: (-s["items"], -s["authors"], s["code"]))
    popular = {s["code"] for s in stats if s["items"] >= POPULAR_SHARE * n_coded}

    P = []
    p = P.append
    p("# E4 — The community register: suggestions and complaints about the FIDE rating system, 2023–2026")
    p("")
    p("Status: REVIEW — evidence for the proposal (§2, the headline ranking) and annex T8, session ELO-4, Phase 2. Generated by "
      "`analysis/e4_community_report.py` from `analysis/community/register.json`; do not edit by hand. Licence: CC BY 4.0 "
      "(`docs/LICENSE-docs.md`). Every statement below is a paraphrase in our words; no quotation is longer than 15 words. "
      "Sources are linked, not copied; no commenter is named.")
    p("")
    fams = Counter(it["family"] for it in items)
    for fam in reg["searches"]:
        fams.setdefault(fam, 0)
    p("## Method")
    p("")
    p(f"- **Window.** {reg['window'][0]} to {reg['window'][1]}.")
    p("- **Sources.** " + "; ".join(f"{f}: {fams[f]} item{'s' if fams[f] != 1 else ''}" for f in sorted(fams)) + " (counted items; "
      f"{len(reg['not_counted'])} more are listed but not counted, section 4). "
      "Each family was searched with the queries recorded in the register; every page read or attempted is in its access log "
      "(section 5).")
    p("- **Coding.** Each item (a thread, an article with its comments, an official document, an interview, a book) is coded on "
      f"a fixed list of {len(tax)} themes, fixed before reading. For each theme an item raises, the register records a one-line "
      "paraphrase, the stance (complaint, suggestion, defence of the current system, mixed) and, where the page shows authors, "
      "the number of distinct authors raising it. No username is recorded.")
    p("- **Counting.** A theme's recurrence is the number of items that raise it; the authors column sums distinct authors per "
      "item where countable, so a person active in two threads counts twice. Items read only through a search snippet, or "
      "whose comments did not load, carry no author count.")
    p(f"- **Popular.** A theme raised in at least {int(POPULAR_SHARE * 100)} % of the {n_coded} coded items (PROVISIONAL rule).")
    p("")
    p("## 1 Themes ranked by recurrence, with our disposition")
    p("")
    p("| rank | theme | items | authors (where visible) | complaint / suggestion / defence / mixed | disposition | where in the design |")
    p("|---|---|---|---|---|---|---|")
    for rank, s in enumerate(stats, 1):
        if not s["items"]:
            continue
        d = disp.get(s["code"], {})
        st = s["stance"]
        flag = " **(popular, not addressed)**" if s["code"] in popular and d.get("disposition") in ("out of scope", "rejected") else ""
        p(f"| {rank} | {tax[s['code']]} (`{s['code']}`) | {s['items']} | {s['authors']} | {st['complaint']} / {st['suggestion']} / "
          f"{st['defence']} / {st['mixed']} | {d.get('disposition', '—')}{flag} | {d.get('where', '—')} |")
    p("")
    absent = [s["code"] for s in stats if not s["items"]]
    if absent:
        p("Themes on the list that no item raised: " + ", ".join(f"{tax[c]} (`{c}`)" for c in absent) + ".")
        p("")
    p("## 2 Each theme: what people say, and what the design does")
    p("")
    for s in stats:
        if not s["items"]:
            continue
        code = s["code"]
        d = disp.get(code, {})
        lst = by_theme[code]
        p(f"### {tax[code]} (`{code}`) — {s['items']} items, {s['authors']} authors where visible")
        p("")
        p(f"**What is said.** {d.get('statement', '')}")
        p("")
        p(f"**Disposition: {d.get('disposition', '—')}.** {d.get('reason', '')}")
        p("")
        seen, links = set(), []
        for it, th in sorted(lst, key=lambda x: (x[0]["date"], x[0]["id"])):
            if it["id"] in seen:
                continue
            seen.add(it["id"])
            links.append(f"[{it['id']}]({it['url']}) {it['date'][:7]}, {th['paraphrase']}")
        for line in links[:LINKS_PER_THEME]:
            p(f"- {line}")
        if len(links) > LINKS_PER_THEME:
            p(f"- … and {len(links) - LINKS_PER_THEME} more items (section 4).")
        p("")
    p("## 3 Popular themes the design does not address")
    p("")
    flagged = [s for s in stats if s["code"] in popular and disp.get(s["code"], {}).get("disposition") in ("out of scope", "rejected")]
    if flagged:
        for s in flagged:
            d = disp[s["code"]]
            p(f"- **{tax[s['code']]}** ({s['items']} items): {d['disposition']}. {d.get('reason', '')}")
    else:
        p("- None: every popular theme is adopted or partly adopted by a rung.")
    partly = [s for s in stats if s["code"] in popular and disp.get(s["code"], {}).get("disposition") == "partly adopted"]
    if partly:
        p("")
        p("Popular themes only partly addressed: " + "; ".join(f"{tax[s['code']]} ({s['items']} items)" for s in partly) + ".")
    p("")
    p("## 4 Every item")
    p("")
    p("| id | date | source | title | themes | access |")
    p("|---|---|---|---|---|---|")
    for it in sorted(items, key=lambda x: (x["family"], x["date"], x["id"])):
        title = it["title"].replace("|", "/")
        codes = ", ".join(th["code"] for th in it["themes"]) or "—"
        p(f"| [{it['id']}]({it['url']}) | {it['date']} | {it['platform']} | {title} | {codes} | {it['access']} |")
    p("")
    if reg["not_counted"]:
        p("Listed but not counted:")
        p("")
        p("| id | date | source | title | reason |")
        p("|---|---|---|---|---|")
        for it in reg["not_counted"]:
            p(f"| [{it['id']}]({it['url']}) | {it['date']} | {it['platform']} | {it['title'].replace('|', '/')} | {it['reason']} |")
        p("")
    log = reg["access_log"]
    p("## 5 Sources visited, including those that refused access")
    p("")
    per = defaultdict(Counter)
    for e in log:
        ok = str(e["outcome"]).upper().startswith("OK")
        per[domain(e["url"]) if e["url"].startswith("http") else e["url"]]["ok" if ok else "other"] += 1
    p(f"{len(log)} fetches were attempted. By site (read / refused, failed or partial):")
    p("")
    p("| site | read | refused, failed or partial |")
    p("|---|---|---|")
    for dom, c in sorted(per.items(), key=lambda kv: (-(kv[1]["ok"] + kv[1]["other"]), kv[0])):
        p(f"| {dom} | {c['ok']} | {c['other']} |")
    p("")
    refused = [e for e in log if not str(e["outcome"]).upper().startswith("OK")]
    p("Every attempt that was not read in full:")
    p("")
    for e in refused:
        p(f"- {e['utc']} — {e['url']} — {e['outcome']}{(' — ' + e['note']) if e.get('note') else ''}")
    p("")
    for note in reg.get("family_notes", []):
        p(f"- {note}")
    if reg.get("family_notes"):
        p("")
    p("## 6 Limits")
    p("")
    for line in reg["limits"]:
        p(f"- {line}")
    print("\n".join(P))


if __name__ == "__main__":
    main()
