#!/usr/bin/env python3
"""E5 report: turns analysis/aggregates/E5_deflation.json into docs/evidence/E5_deflation.md.

Reads only committed aggregates (E5, and E1 for the K scheme of the rapid and
blitz lists and the anchor sizes E1 printed); no data/ needed. Ghita's figures
are cited from his book with page numbers [R 5], paraphrased; none of his tables
is reproduced.

Usage: python3 analysis/e5_deflation_report.py > docs/evidence/E5_deflation.md
"""
from __future__ import annotations

import json
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AGG = ROOT / "analysis" / "aggregates"
BANDS = ["<1600", "1600-1999", "2000-2199", "2200-2399", "2400-2599", "2600+"]
PRE = [f"{y}-02" for y in range(2016, 2024)]
POST = ["2024-03", "2025-03", "2025-10"]
# broadcast calendar year -> the list window it is compared with (the window that holds most of that year)
YEAR_WINDOW = {"2023": "2023-02", "2024": "2024-03", "2025": "2025-03", "2026": "2025-10"}


def sg(x, nd: int = 0) -> str:
    """Signed number, ASCII minus, '+' for positives; None -> '—'."""
    if x is None:
        return "—"
    if nd == 0:
        v = round(x)
        if abs(x - v) < 1e-9:
            x = int(v)
            return f"{x:+d}" if x else "0"
        return f"{x:+.1f}"
    return f"{x:+.{nd}f}" if round(x, nd) != 0 else f"{0:.{nd}f}"


def num(x) -> str:
    """Unsigned magnitude: whole numbers without decimals, otherwise one decimal."""
    x = abs(x)
    return f"{x:.0f}" if abs(x - round(x)) < 1e-9 else f"{x:.1f}"


def rng(vals: list[float]) -> str:
    """'a to b' over magnitudes, smallest first."""
    a, b = sorted((abs(v) for v in vals))[0], sorted((abs(v) for v in vals))[-1]
    return f"{num(a)} to {num(b)}" if num(a) != num(b) else num(a)


def rng2(vals: list[float]) -> str:
    a, b = sorted(abs(v) for v in vals)[0], sorted(abs(v) for v in vals)[-1]
    return f"{a:.2f} to {b:.2f}"


def srng(vals: list[float]) -> str:
    """Signed range, lowest first: '+2 to +3', '-6 to -2'."""
    lo, hi = min(vals), max(vals)
    return sg(lo) if sg(lo) == sg(hi) else f"{sg(lo)} to {sg(hi)}"


def sgl(vals: list[float]) -> str:
    return ", ".join(sg(v) for v in vals)


def n0(x) -> str:
    return "—" if x is None else f"{x:,}"


def med(g: dict) -> str:
    return sg(g.get("median")) if g.get("n") else "—"


def win_label(s: str, e: str) -> str:
    return f"{s} to {e}"


def main() -> None:
    d = json.loads((AGG / "E5_deflation.json").read_text(encoding="utf-8"))
    e1 = {tc: json.loads((AGG / f"E1_{tc}.json").read_text(encoding="utf-8")) for tc in ("standard", "rapid", "blitz")}
    S = d["by_tc"]["standard"]
    L = {w["start"]: w for w in S["longitudinal"]}
    wins = [(w["start"], w["end"]) for w in S["longitudinal"]]
    P = []

    def p(line: str = "") -> None:
        P.append(line)

    # ------------------------------------------------------------------ derived figures used in the verdict
    anchor_pre = [L[s]["groups"]["anchor_e1"]["median"] for s in PRE]
    anchor_post = [L[s]["groups"]["anchor_e1"]["median"] for s in POST]
    dec = {x["start"]: x for x in S["cross_section"]["decomposition"]}
    med_pre = [dec[s]["percentiles"]["p50"]["change"] for s in PRE if s != "2020-02"]
    med_post = [dec[s]["percentiles"]["p50"]["change"] for s in POST]
    comp_pre = [dec[s]["percentiles"]["p50"]["composition"] for s in PRE if s != "2020-02"]
    within_all = [dec[s]["percentiles"]["p50"]["within"] for s in PRE + POST]
    mean_within_all = [dec[s]["mean_within_stayers"] for s in PRE + POST]
    G = S["ghita"]
    gs = G["slopes"]
    top = S["top_and_spread"]
    M = S["mechanism"]
    bby = M["by_band_year"]
    mar = S["march_2024"]
    last = L["2025-03"]["groups"]

    def list_per_game(window: str, b: str) -> float | None:
        g = L[window]["groups"].get(f"band:{b}", {})
        return g.get("per_game")

    first_k40 = {}
    for tc in ("rapid", "blitz"):
        first_k40[tc] = next((x["list"] for x in e1[tc]["k_distribution"] if "40" in x["all"]), None)

    # ------------------------------------------------------------------ header
    p("# E5 — The deflation question")
    p()
    p("Status: REVIEW — evidence for the proposal (§1, §2, §10) and annex (T4.5, T8.1, rung 6), session ELO-4, Phase 1. "
      "Generated by `analysis/e5_deflation_report.py` from `analysis/aggregates/E5_deflation.json`, which "
      "`analysis/e5_deflation_extract.py` computes from FIDE's monthly lists (analysed, never committed or redistributed [V 3]) "
      "and the Lichess broadcast archive (https://database.lichess.org/broadcast/, CC BY-SA 4.0, attributed; aggregates only) [V 4]. "
      "Do not edit by hand. Licence: CC BY 4.0 (`docs/LICENSE-docs.md`). Ghita's book, *The Rating Revolution* (v1.0, February 2026) [R 5], "
      "is cited by page and paraphrased; none of its tables is reproduced. Every definition below is PROVISIONAL.")
    p()

    # ------------------------------------------------------------------ verdict
    t_rank100 = (top["2015-10"]["active_rank_100"], top["2026-10"]["active_rank_100"])
    t_2600 = (top["2015-10"]["active_2600"], top["2021-01"]["active_2600"], top["2026-10"]["active_2600"])
    sd = (top["2024-02"]["active_adults_25_45"]["sd"], top["2024-03"]["active_adults_25_45"]["sd"],
          top["2026-10"]["active_adults_25_45"]["sd"])
    imp = {b: bby[f"{b}|all"]["implied_per_game"] for b in BANDS}
    lpg = {b: list_per_game("2025-03", b) for b in BANDS}
    std_mar_share = 100 * mar["equal_to_formula"] / mar["no_game_below_2000"]
    band_post = {bn: [L[s]["groups"][f"band:{bn}"]["median"] for s in POST] for bn in BANDS}
    band_pre2 = {bn: [L[s]["groups"][f"band:{bn}"]["median"] for s in ("2022-02", "2023-02")] for bn in BANDS}
    top3 = ["2200-2399", "2400-2599", "2600+"]
    mid2 = ["1600-1999", "2000-2199"]
    fall_windows = [s for s in PRE + POST if dec[s]["percentiles"]["p50"]["change"] < 0]
    comp_bigger = sum(1 for s in fall_windows if dec[s]["percentiles"]["p50"]["composition"] < dec[s]["percentiles"]["p50"]["change"])
    rapid_anchor_post = [w["groups"]["anchor_e1"]["median"] for w in d["by_tc"]["rapid"]["longitudinal"] if w["start"] in POST]
    blitz_anchor_post = [w["groups"]["anchor_e1"]["median"] for w in d["by_tc"]["blitz"]["longitudinal"] if w["start"] in POST]
    post_years = ["2024", "2025", "2026"]
    agree_post = sum(1 for bn in BANDS for y in post_years
                     if (bby[f"{bn}|{y}"]["implied_per_game"] > 0) == ((list_per_game(YEAR_WINDOW[y], bn) or 0) > 0))
    act_hi = [last[f"adult_games:{k}"]["median"] for k in ("20-49", "50+")]
    act_lo = [last[f"adult_games:{k}"]["median"] for k in ("1-4", "5-9", "10-19")]
    p("## Verdict")
    p()
    def implied_share(bn: str) -> float:
        c, g = bby[f"{bn}|all"], last.get(f"band:{bn}", {})
        return c["implied_per_game"] * g["games"] / g["n"] / g["mean"]
    share_low = implied_share("2200-2399")
    p(f"**In three sentences.** Since March 2024 the published ratings of steadily active adults have stopped falling in standard "
      f"({srng(anchor_post)} points a year) and rapid ({srng(rapid_anchor_post)}), after falling {rng(anchor_pre)} a year in standard from 2016 to "
      f"February 2024; blitz is still slightly negative ({sgl(blitz_anchor_post)}). What still slides is the top of the list: players rated 2200 "
      f"or more lose {rng([v for bn in top3 for v in band_post[bn]])} points a year; at 2400 and above that is about the transfer table 8.1.2's "
      f"over-prediction of favourites implies, at 2200–2399 about {'a third' if share_low < 0.42 else 'half'} of it (section 5), and active 2600+ "
      f"players fell from {t_2600[0]} in 2015 to {t_2600[2]}. The median of the active list also keeps "
      f"falling, {rng(med_post)} points a year, but only because entrants arrive below the players who stop (continuing players gain), and that "
      "cross-sectional median is what Ghita's −26 and −16 a year measure.")
    p()
    p("**What is sliding, where, since when, by how much.**")
    p()
    p(f"1. **The cross-section of the active list.** The median rating of players with a rated standard game in the last 12 months fell "
      f"{rng(med_pre)} points a year in the windows from 2016 to February 2024 (the pandemic window 2020–21 aside, when it rose) and "
      f"{rng(med_post)} a year since March 2024. In all {len(fall_windows)} windows in which it fell, the composition term (entrants rated below "
      f"the players who stopped) is larger than the whole fall, while the median of the players present at "
      f"both ends rose by {rng(within_all)} points (section 3). The statistic records who is on the list, not points lost by anyone.")
    p(f"2. **The top of the list.** Every band from 1600 up has a negative median in every window since 2016. The reform relieved the middle: "
      f"the medians of players rated 1600–1999 and 2000–2199 were {sgl(band_pre2['1600-1999'])} and {sgl(band_pre2['2000-2199'])} points a "
      f"year in the two windows of 2022–24 and {sgl(band_post['1600-1999'])} and {sgl(band_post['2000-2199'])} in the three since. It did not "
      f"relieve the top: 2200–2399 {sgl(band_pre2['2200-2399'])}, then {sgl(band_post['2200-2399'])}; 2400–2599 {sgl(band_pre2['2400-2599'])}, "
      f"then {sgl(band_post['2400-2599'])}; 2600+ {sgl(band_pre2['2600+'])}, then {sgl(band_post['2600+'])} (section 2).")
    p(f"3. **Why the top keeps paying.** On broadcast games, table 8.1.2's over-prediction of the favourite [E2] alone costs players rated "
      f"2400–2599 {abs(imp['2400-2599']):.2f} points a game and players rated 2600 or more {abs(imp['2600+']):.2f}, while the lists show them losing "
      f"{abs(lpg['2400-2599']):.2f} and {abs(lpg['2600+']):.2f} a game in 2025–26 (section 5). Since 2024 the over-prediction's implied transfer has the "
      f"lists' sign in {agree_post} of {len(BANDS) * len(post_years)} band-years. It is a transfer down the list: a problem of spread, not of level.")
    p(f"4. **The elite.** Active players rated 2600 or more fell from {t_2600[0]} (October 2015) and {t_2600[1]} (January 2021) to "
      f"{t_2600[2]} (October 2026); the 100th active player's rating fell from {t_rank100[0]} to {t_rank100[1]} (section 4).")
    p(f"5. **Older and less active adults.** In 2025–26 players aged 46–64 and 65 or more had median changes of "
      f"{med(last['age:46-64'])} and {med(last['age:65+'])} points; adults aged 25–45 with 20 or more games gained {rng(act_hi)} and those with "
      f"fewer lost {rng(act_lo)} (section 2). Ageing and activity sort these groups as much as the scale does; the lists cannot separate them.")
    p()
    mid_gap = [list_per_game(YEAR_WINDOW[y], bn) - bby[f"{bn}|{y}"]["implied_per_game"] for bn in mid2 for y in post_years]
    top_gap = [list_per_game(YEAR_WINDOW[y], "2200-2399") - bby[f"2200-2399|{y}"]["implied_per_game"] for y in post_years]
    p(f"**Before the reform there was a second drain.** In the 2023–24 window the bands from 1600 to 2399 lost "
      f"{rng2([list_per_game('2023-02', bn) for bn in ['1600-1999', '2000-2199', '2200-2399']])} points a game on the lists, against an implied "
      f"over-prediction transfer of {rng2([bby[bn + '|2023']['implied_per_game'] for bn in ['1600-1999', '2000-2199', '2200-2399']])} in their "
      "favour (section 5): something else drained them, consistent with the research report's channel of under-rated newcomers and juniors [R 5] "
      f"[R 39]. Since 2024 the 1600–2199 bands are within {abs(min(mid_gap)):.2f} points a game of the implied transfer or above it, while the "
      f"2200–2399 band still loses {rng2([g for g in top_gap if g < 0])} a game more than the transfer implies.")
    p()
    p(f"**What the 2024 reform changed.** On the March 2024 list, {std_mar_share:.2f} % of standard players rated below 2000 with no game in that "
      f"period moved by exactly round(0.4 × (2000 − R)), and {100 * mar['unchanged'] / mar['no_game_from_2000']:.2f} % of those rated 2000 or more "
      f"did not move; rapid and blitz show the same (section 4). The SD of active adults' ratings fell from {sd[0]:.0f} to {sd[1]:.0f} points in one "
      f"list and has stayed near {sd[2]:.0f}. The anchor cohort's drift turned from negative to positive. The second drain closed below 2200 and narrowed "
      f"above it, and the cross-sectional slide slowed because entrants now arrive higher (newcomers' median first rating 1272 in 2023, 1564 in 2025 [E1]).")
    p()
    p("**What remains.** The table that over-predicts favourites is unchanged, so the top bands keep paying; the number of active 2600+ players keeps "
      "falling; the median of the active list keeps sliding by composition while continuing players gain; blitz has not turned. Deflation in the "
      "sense of a falling level for steadily active adults stopped in March 2024 in standard and rapid; what continues is a transfer from the top of "
      "the list to the bottom and a shrinking elite.")
    p()
    p("**Ghita's figures.** The −26 and −16 points a year in the book are the change of the median of the active rating list, before and after "
      "March 2024 ([R 5], p. 21), measured on the monthly lists of January 2021 to December 2025 (p. 63), not on its 954,805-game sample, which "
      "serves the federation measures (p. 63). The research report attributes them to the games [R 5]. Our closest equivalent "
      f"gives falls of {abs(gs['month']['p50']['pre']):.1f} to {abs(gs['calendar_year']['p50']['pre']):.1f} points a year before and "
      f"{abs(gs['month']['p50']['post']):.1f} to {abs(gs['calendar_year']['p50']['post']):.1f} after, depending on how \"active\" is read: his "
      "figures lie inside both ranges. The statistic is "
      "real; it describes the changing composition of the active list (section 6).")
    p()

    # ------------------------------------------------------------------ 1 data
    p("## 1 Data and definitions")
    p()
    b = S["r11_batch"]
    p(f"- **Lists.** FIDE's monthly standard, rapid and blitz lists, {S['first_list']} to {S['last_list']} [V 3]; the converted files of "
      "`tools/data/convert_fide_lists.py`. Ratings, games in the period, K, year of birth, federation and the inactive flag.")
    p(f"- **The April 2026 list event (D-0008, R11).** List membership is an input to Layer 0. Every analysis below excludes the IDs first rated on the "
      f"March 2026 list and absent from the April 2026 list: {n0(b['n'])} in standard, {n0(d['by_tc']['rapid']['r11_batch']['n'])} in rapid and "
      f"{n0(d['by_tc']['blitz']['r11_batch']['n'])} in blitz (section 7).")
    p("- **Windows.** E1's twelve-month windows: February to February up to 2024, March to March after the reform, and October 2025 to October 2026. "
      "No window contains the March 2024 list as an interior point; the 2024-03 window starts on it.")
    p("- **Per-player change (\"survivors\").** R(s + 12) − R(s) for players rated on both lists of a window with at least one rated game on the "
      "12 lists after s. Groups: all of them; without players whose K on list s is 40; adults aged 25–45 (calendar year of s minus year of birth); "
      "E1's anchor cohort (adults 25–45, not flagged inactive on either list, at least 10 games in the window and 10 in the year before); six bands of "
      "R(s); age groups; adults by games in the window. Banding on R(s) builds in regression to the mean (players who reached a band partly by luck "
      "fall back), so a variant bands on R(s − 12).")
    p("- **Cross-section.** Players rated on a list with at least one rated game on the 12 lists up to it. The change of a percentile between two lists "
      "is split in two: the composition part is the change obtained by replacing the leavers with the entrants while keeping the stayers at their "
      "starting ratings; the within part is the rest, the stayers' own movement. Percentiles are nearest-rank.")
    p("- **Year of birth.** The latest non-zero year of birth on any list. 157 IDs whose latest list prints a zero year keep their earlier year here; E1 "
      "treats them as unknown, so the anchor cohort sizes below differ from E1's by a few players while its medians are identical.")
    anchor_diff = []
    e1_drift = {x["start"]: x for x in e1["standard"]["anchor_drift"]}
    for s, _e in wins:
        if s in e1_drift:
            anchor_diff.append((L[s]["groups"]["anchor_e1"]["n"] - e1_drift[s]["all"]["n"],
                                L[s]["groups"]["anchor_e1"]["median"] == e1_drift[s]["all"]["median"]))
    p(f"  Measured: cohort sizes differ from E1's by {min(x[0] for x in anchor_diff)} to {max(x[0] for x in anchor_diff)} players; medians equal in "
      f"{sum(1 for x in anchor_diff if x[1])} of {len(anchor_diff)} windows.")
    p(f"- **Broadcast games.** The E2 sample (SPEC-TABLE-FIT §1): standard-chess games with a result between two players rated on the list of the time "
      f"control in force at the tour's start, January 2023 to September 2026, duplicates removed. ELO-4 data cutoff: no game dated after "
      f"{d['broadcast']['cutoff']} ({d['broadcast']['dropped_after_cutoff']} dropped) and no file after 2026-09. K is each player's K on that list; "
      "FIDE's expected score is Layer 0's (`src/layer0`). Broadcast events are stronger and more international than the rated pool [E2].")
    p()

    # ------------------------------------------------------------------ 2 longitudinal
    p("## 2 Per-player change of published ratings (1.1)")
    p()
    p("Standard. Median annual change, points (mean in brackets); players rated on both lists with at least one rated game in the window:")
    p()
    p("| window | all | without K 40 | adults 25–45 | adults 25–45 without K 40 | anchor cohort [E1] (size) |")
    p("|---|---|---|---|---|---|")
    for s, e in wins:
        g = L[s]["groups"]

        def cell(k: str) -> str:
            x = g.get(k, {})
            return f"{med(x)} ({sg(x.get('mean'), 1)})" if x.get("n") else "—"
        a = g["anchor_e1"]
        p(f"| {win_label(s, e)} | {cell('all_active')} | {cell('all_active_no_k40')} | {cell('adults_25_45')} | "
          f"{cell('adults_25_45_no_k40')} | {med(a)} ({n0(a['n'])}) |")
    p()
    p("The mean of all players is positive in every window and the median negative: a minority of fast risers, mostly juniors, gains many points, "
      "while most players lose a few. The adult rows turn from about −5 before the reform to about −2 after it.")
    p()
    p("Standard, median annual change by band of R(s), all players with a rated game in the window (first row of each band) and without K 40 "
      "(second row):")
    p()
    head = " | ".join(s for s, _e in wins)
    p(f"| band | {head} |")
    p("|---|" + "---|" * len(wins))
    for bn in BANDS:
        p(f"| {bn} | " + " | ".join(med(L[s]["groups"].get(f"band:{bn}", {})) for s, _e in wins) + " |")
        p(f"| {bn}, no K 40 | " + " | ".join(med(L[s]["groups"].get(f"band_no_k40:{bn}", {})) for s, _e in wins) + " |")
    p()
    p("Regression to the mean, measured for the last full window (2025-03 to 2026-03): median (mean) by band of R(s) against the band of the rating a "
      "year earlier, R(s − 12), and the mean change per game on the lists:")
    p()
    p("| band | by R(s) | by R(s − 12) | players | change per game, by R(s) |")
    p("|---|---|---|---|---|")
    for bn in BANDS:
        a, c = last.get(f"band:{bn}", {}), last.get(f"band_prev_year:{bn}", {})
        p(f"| {bn} | {med(a)} ({sg(a.get('mean'), 1)}) | {med(c)} ({sg(c.get('mean'), 1)}) | {n0(a.get('n'))} | {sg(a.get('per_game'), 3)} |")
    p()
    p("Banding a year earlier changes the top bands by a few points, not their sign: the loss at the top is not an artefact of the banding.")
    p()
    p("Standard, by age and, for adults 25–45, by games in the window; median (mean):")
    p()
    sel = ["2019-02", "2023-02", "2024-03", "2025-03"]
    p("| group | " + " | ".join(win_label(s, L[s]["end"]) for s in sel) + " |")
    p("|---|" + "---|" * len(sel))
    for k, lab in [("age:<=18", "aged 18 or less"), ("age:19-24", "19–24"), ("age:25-45", "25–45"), ("age:46-64", "46–64"), ("age:65+", "65 or more"),
                   ("adult_games:1-4", "adults, 1–4 games"), ("adult_games:5-9", "adults, 5–9 games"), ("adult_games:10-19", "adults, 10–19 games"),
                   ("adult_games:20-49", "adults, 20–49 games"), ("adult_games:50+", "adults, 50 or more games")]:
        p(f"| {lab} | " + " | ".join(f"{med(L[s]['groups'].get(k, {}))} ({sg(L[s]['groups'].get(k, {}).get('mean'), 1)})" for s in sel) + " |")
    p()
    p("Before the reform every adult activity group lost points; since March 2024 adults with 20 or more games a year gain and adults with fewer than "
      "10 lose.")
    p()
    p(f"Rapid and blitz, median annual change (the lists print K = 20 for every rapid and blitz player until the {first_k40['rapid']} list, so "
      "\"without K 40\" is shown from the first window that starts after it):")
    p()
    p("| window | rapid: all | rapid: without K 40 | rapid: adults 25–45 | rapid: anchor | blitz: all | blitz: without K 40 | blitz: adults 25–45 | blitz: anchor |")
    p("|---|---|---|---|---|---|---|---|---|")
    LR = {w["start"]: w["groups"] for w in d["by_tc"]["rapid"]["longitudinal"]}
    LB = {w["start"]: w["groups"] for w in d["by_tc"]["blitz"]["longitudinal"]}
    for s, e in wins:
        def nk(Lx: dict, tc: str) -> str:
            return med(Lx[s].get("all_active_no_k40", {})) if s >= first_k40[tc] else "—"
        p(f"| {win_label(s, e)} | {med(LR[s]['all_active'])} | {nk(LR, 'rapid')} | {med(LR[s]['adults_25_45'])} | {med(LR[s]['anchor_e1'])} | "
          f"{med(LB[s]['all_active'])} | {nk(LB, 'blitz')} | {med(LB[s]['adults_25_45'])} | {med(LB[s]['anchor_e1'])} |")
    p()

    # ------------------------------------------------------------------ 3 cross-section
    p("## 3 The cross-section and its composition (1.1, survivors against everyone)")
    p()
    p("Standard. Players with a rated game in the 12 months up to each list. The change of the median over the window, split into composition "
      "(entrants against leavers, stayers held at their starting rating) and within (the stayers' own movement); the same for the mean:")
    p()
    p("| window | active players, start → end | median, start → end | change | composition | within | mean change | mean: composition | mean: within | entrants' mean | leavers' mean |")
    p("|---|---|---|---|---|---|---|---|---|---|---|")
    for s, e in wins:
        x = dec[s]
        m = x["percentiles"]["p50"]
        p(f"| {win_label(s, e)} | {n0(x['n_start'])} → {n0(x['n_end'])} | {m['start']} → {m['end']} | {sg(m['change'])} | {sg(m['composition'])} | "
          f"{sg(m['within'])} | {sg(x['mean_change'], 1)} | {sg(x['mean_composition'], 1)} | {sg(x['mean_within_weighted'], 1)} | "
          f"{x['entrants_mean_rating']} | {x['leavers_mean_rating']} |")
    p()
    p(f"The players present at both ends gained on average in every window ({min(mean_within_all):+.1f} to {max(mean_within_all):+.1f} points; mean of "
      "the stayers); the whole fall of the cross-section comes from entrants arriving below the players who stop. The 2020–21 window is the "
      "pandemic: few entrants, and the leavers were the weaker players.")
    p()
    p("Rapid and blitz, change of the median of the active list and its two parts:")
    p()
    p("| window | rapid: change | composition | within | blitz: change | composition | within |")
    p("|---|---|---|---|---|---|---|")
    DR = {x["start"]: x["percentiles"]["p50"] for x in d["by_tc"]["rapid"]["cross_section"]["decomposition"]}
    DB = {x["start"]: x["percentiles"]["p50"] for x in d["by_tc"]["blitz"]["cross_section"]["decomposition"]}
    for s, e in wins:
        p(f"| {win_label(s, e)} | {sg(DR[s]['change'])} | {sg(DR[s]['composition'])} | {sg(DR[s]['within'])} | {sg(DB[s]['change'])} | "
          f"{sg(DB[s]['composition'])} | {sg(DB[s]['within'])} |")
    p()

    # ------------------------------------------------------------------ 4 top and spread
    p("## 4 The top and the spread (1.2)")
    p()
    rows = [k for k in sorted(top) if k.endswith("-10")] + ["2021-01", "2024-02", "2024-03", "2025-12"]
    rows = sorted(set(rows))
    p("Standard. Players rated 2600, 2700 and 2800 or more (all listed / active, at least one rated game in the 12 months up to the list), "
      "ratings at ranks 10, 100 and 1000 of the active list, and the mean of its top 100:")
    p()
    p("| list | 2600+ | 2700+ | 2800+ | active rank 10 | rank 100 | rank 1000 | top-100 mean |")
    p("|---|---|---|---|---|---|---|---|")
    for k in rows:
        r = top[k]
        p(f"| {k} | {r['n_2600']} / {r['active_2600']} | {r['n_2700']} / {r['active_2700']} | {r['n_2800']} / {r['active_2800']} | "
          f"{r['active_rank_10']} | {r['active_rank_100']} | {r['active_rank_1000']} | {r['active_top100_mean']} |")
    p()
    p("Spread: active adults aged 25–45 (at least one rated game in the 12 months up to the list), SD and percentiles of their ratings:")
    p()
    p("| list | players | SD | p10 | p25 | median | p75 | p90 | p99 |")
    p("|---|---|---|---|---|---|---|---|---|")
    for k in rows:
        a = top[k]["active_adults_25_45"]
        p(f"| {k} | {n0(a['n'])} | {a['sd']:.0f} | {a['p10']} | {a['p25']} | {a['p50']} | {a['p75']} | {a['p90']} | {a['p99']} |")
    p()
    p("Before the reform the active adults' distribution widened, its lower half falling faster than its upper; the March 2024 compression cut the SD "
      "by about a third in one list; since then the SD is flat and the upper percentiles drift down by a few points a year.")
    p()
    p("The March 2024 list against the formula R + 0.4 × (2000 − R), rounded, for players with no rated game in that period [R §2]:")
    p()
    p("| list | players below 2000 | equal to the formula | players from 2000 | unchanged |")
    p("|---|---|---|---|---|")
    for tc in ("standard", "rapid", "blitz"):
        m = d["by_tc"][tc]["march_2024"]
        p(f"| {tc} | {n0(m['no_game_below_2000'])} | {n0(m['equal_to_formula'])} ({100 * m['equal_to_formula'] / m['no_game_below_2000']:.2f} %) | "
          f"{n0(m['no_game_from_2000'])} | {n0(m['unchanged'])} ({100 * m['unchanged'] / m['no_game_from_2000']:.2f} %) |")
    p()

    # ------------------------------------------------------------------ 5 mechanism
    p("## 5 The mechanism: the drain implied by the favourite's over-prediction (1.3)")
    p()
    bins = M["favourite_residual_by_gap_bin"]
    nb = M["favourite_games_by_gap_bin"]
    p("Broadcast games. The favourite's mean score minus FIDE's expected score (table 8.1.2 with the 400-point rule, Layer 0) by 50-point gap bin, "
      "all years, the same quantity as E2's descriptive table recomputed on this sample:")
    p()
    p("| gap | " + " | ".join(f"{50 * k}–{50 * k + 49}" for k in range(12)) + " |")
    p("|---|" + "---|" * 12)
    for tc in ("standard", "rapid", "blitz"):
        Mx = d["by_tc"][tc]["mechanism"]
        p(f"| {tc} | " + " | ".join(sg(v, 3) for v in Mx["favourite_residual_by_gap_bin"][:12]) + " |")
    p(f"| standard games | " + " | ".join(n0(v) for v in nb[:12]) + " |")
    p()
    p("For every player-game, the change FIDE's rules give, K × (S − E), and the part implied by the over-prediction alone: K times the bin's mean "
      "residual, taken with a minus sign for the favourite and a plus sign for the underdog. Standard, by the player's band, all years; and the lists "
      "(all players with a rated game in 2025-03 to 2026-03: mean change per game and games per player-year):")
    p()
    p("| band | broadcast player-games | mean K | implied per game | realised per game | lists: change per game | lists: games a year | implied per year | lists: mean change a year |")
    p("|---|---|---|---|---|---|---|---|---|")
    for bn in BANDS:
        c = bby[f"{bn}|all"]
        g = last.get(f"band:{bn}", {})
        gpy = g["games"] / g["n"] if g.get("n") else None
        p(f"| {bn} | {n0(c['player_games'])} | {c['mean_k']:.1f} | {sg(c['implied_per_game'], 3)} | {sg(c['realised_per_game'], 3)} | "
          f"{sg(g.get('per_game'), 3)} | {gpy:.1f} | {sg(c['implied_per_game'] * gpy, 1)} | {sg(g.get('mean'), 1)} |")
    p()
    p("By year (standard): implied change per game on broadcast games against the lists' change per game in the matching window:")
    p()
    yrs = ["2023", "2024", "2025", "2026"]
    p("| band | " + " | ".join(f"{y}: implied / lists" for y in yrs) + " |")
    p("|---|" + "---|" * len(yrs))
    for bn in BANDS:
        cells = []
        for y in yrs:
            c = bby.get(f"{bn}|{y}")
            cells.append(f"{sg(c['implied_per_game'], 3) if c else '—'} / {sg(list_per_game(YEAR_WINDOW[y], bn), 3)}")
        p(f"| {bn} | " + " | ".join(cells) + " |")
    p()
    p("2023 has few broadcast games (the archive grows from 2024). Rapid and blitz, all years, implied against realised per game:")
    p()
    p("| band | rapid: implied | rapid: realised | blitz: implied | blitz: realised |")
    p("|---|---|---|---|---|")
    for bn in BANDS:
        r_ = d["by_tc"]["rapid"]["mechanism"]["by_band_year"][f"{bn}|all"]
        b_ = d["by_tc"]["blitz"]["mechanism"]["by_band_year"][f"{bn}|all"]
        p(f"| {bn} | {sg(r_['implied_per_game'], 3)} | {sg(r_['realised_per_game'], 3)} | {sg(b_['implied_per_game'], 3)} | {sg(b_['realised_per_game'], 3)} |")
    p()
    p("Reading. The over-prediction is a property of the gap, not of the level: whoever is the favourite pays it. Because the higher-rated player is "
      "usually the favourite, it moves points down the list, from 2200 and above to below 2000. Since 2024 the lists' change per game has the sign of "
      "the implied transfer in every band, and at 2400 and above, where K is 10 for everyone, the implied drain per game is at least as large as the "
      "lists' whole decline per game. In 2023 (the last pre-reform window) the bands from 1600 to 2399 lost far more on the lists than the "
      "over-prediction implies: a second drain, which the reform closed. The broadcast sample is stronger and more international than the pool, so "
      "the sizes hold for broadcast events and are indicative for the pool.")
    p()

    # ------------------------------------------------------------------ 6 Ghita
    p("## 6 Ghita's figures: his definitions and our closest equivalents (1.4)")
    p()
    p("**How he defines and measures deflation.**")
    p()
    p("- *The median player's annual loss* ([R 5], p. 21): rating percentiles are tracked across the whole population; before the March 2024 "
      "compression the median active rated player lost 26 points a year, after it 16; the 10th percentile gained most from the reform, and the "
      "99th and 99.9th percentiles are said to have declined faster after it than before.")
    p("- *Data* (p. 63): 60 monthly standard lists, January 2021 to December 2025. *Active* (p. 65): at least one standard-rated game in the "
      "reference period, which is not specified further. Rapid and blitz are not analysed (p. 63).")
    p("- *Rating velocity* (p. 20): the mean rating change per game by age cohort, 2021–2025, with the February-to-March 2024 change excluded.")
    p("- *Deflation Index* (p. 50, following Milvang): the favourites' expected minus actual score, per game, in per cent, on an anonymised 2025 "
      "extract of about 954,805 FIDE games (p. 63): 1.67 % in domestic and 3.83 % in cross-border games (p. 50).")
    p("- *Global recalibration* (p. 49): on about one million 2025 games the logistic scale that best fits is S = 459 (95 % interval 455 to 462), "
      "against 400.")
    p("- *The June 2025 essay* (his \"FIDE Ratings Revisited\", republished by the Belgian federation): the shifting distribution of the standard list, "
      "March 2024 to June 2025, with the average rating falling by about one point a month; \"active\" is not defined there either [R 3] [R 4].")
    p()
    p("**Our closest equivalents** (standard lists, R11 batch excluded). Yearly slope (least squares on the monthly values) of percentiles of the "
      "active list, before (2021-01 to 2024-02) and after (2024-03 to 2025-12) the reform, under three readings of \"active\": a rated game on that "
      "month's list; at least one in the 12 months up to it; at least one on the lists of that calendar year:")
    p()
    p("| statistic | month: before | month: after | 12 months: before | 12 months: after | calendar year: before | calendar year: after |")
    p("|---|---|---|---|---|---|---|")
    for stat in ("mean", "p10", "p25", "p50", "p75", "p90", "p99", "p99.9"):
        lab = "median" if stat == "p50" else stat
        p(f"| {lab} | " + " | ".join(sg(gs[k][stat][era], 1) for k in ("month", "trailing_12", "calendar_year") for era in ("pre", "post")) + " |")
    p()
    ser = G["series"]
    june = [m for m in G["months"] if "2024-03" <= m <= "2025-06"]

    def slope(vals: list[float]) -> float:
        n = len(vals)
        xs = list(range(n))
        mx, my = sum(xs) / n, sum(vals) / n
        return sum((x - mx) * (y - my) for x, y in zip(xs, vals)) / sum((x - mx) ** 2 for x in xs)
    jm = {k: slope([ser[k][m]["mean"] for m in june]) for k in ("month", "trailing_12", "calendar_year")}
    p(f"The June 2025 essay's period (March 2024 to June 2025): the mean of the active list falls by {sg(jm['month'], 2)}, {sg(jm['trailing_12'], 2)} "
      f"and {sg(jm['calendar_year'], 2)} points a month under the three readings, against his \"about one\".")
    p()
    vel = G["velocity"]
    p("Rating velocity, points per rated game by age cohort (players rated on two consecutive lists with games in the period; March 2024 excluded):")
    p()
    p("| cohort | before: per game | before: player-months | after: per game | after: player-months |")
    p("|---|---|---|---|---|")
    for k in ("<=18", "19-34", "35-49", "50+"):
        a, c = vel["pre"][k], vel["post"][k]
        lab = {"<=18": "18 or less", "19-34": "19–34", "35-49": "35–49", "50+": "50 or more"}[k]
        p(f"| {lab} | {sg(a['per_game'], 2)} | {n0(a['player_months'])} | {sg(c['per_game'], 2)} | {n0(c['player_months'])} |")
    p()
    di = M["deflation_index"]
    p("Deflation Index on broadcast standard games, (sum of the favourites' expected scores − their scores) / games × 100, with FIDE's table "
      "(\"table\") and with the logistic curve on the full gap (\"logistic\"); domestic means both players' federations on the list in force are the "
      "same:")
    p()
    p("| year | games | all: table | all: logistic | domestic: games | domestic: table | domestic: logistic | cross-border: games | cross-border: table | cross-border: logistic |")
    p("|---|---|---|---|---|---|---|---|---|---|")
    for y in ("2024", "2025", "2026", "all"):
        a, dm, cb = di[f"{y}|all|all"], di.get(f"{y}|domestic|all"), di.get(f"{y}|cross_border|all")
        p(f"| {y if y != 'all' else '2023–2026'} | {n0(a['games'])} | {a['di_table']:.2f} | {a['di_logistic_400']:.2f} | {n0(dm['games'])} | "
          f"{dm['di_table']:.2f} | {dm['di_logistic_400']:.2f} | {n0(cb['games'])} | {cb['di_table']:.2f} | {cb['di_logistic_400']:.2f} |")
    p()
    sc = M["logistic_scale_least_squares"]
    p(f"Logistic scale S minimising the squared error of the expected score (White's view, colour ignored, full gap), broadcast standard games: "
      f"{sc['2024']} (2024), {sc['2025']} (2025), {sc['2026']} (2026 to September), {sc['all']} (all years); rapid {d['by_tc']['rapid']['mechanism']['logistic_scale_least_squares']['all']}, "
      f"blitz {d['by_tc']['blitz']['mechanism']['logistic_scale_least_squares']['all']}.")
    p()
    p("**Every difference explained.**")
    p()
    p("1. *Cross-section, not players.* His −26 and −16 are percentile slopes of the active list: they mix the movement of players with who is on the "
      "list. Section 3 splits them: entrants arriving below the players who stop account for more than the whole fall, and continuing players gained.")
    p("2. *\"Active\".* The book leaves the reference period open. Reading it as the month, the last 12 months or the calendar year changes the "
      f"median's slope from {sg(gs['month']['p50']['pre'], 1)} to {sg(gs['calendar_year']['p50']['pre'], 1)} before the reform and from "
      f"{sg(gs['month']['p50']['post'], 1)} to {sg(gs['calendar_year']['p50']['post'], 1)} after it; his figures lie inside both ranges, nearer the "
      "monthly reading before and the 12-month reading after, so no single reading reproduces both.")
    p("3. *The start.* January 2021 is the pandemic trough: the active list was small and stronger than usual, so any slope that starts there is steeper "
      "than one over normal years.")
    p("4. *The top percentiles.* Under every reading, the 99th and 99.9th percentiles fall more slowly after the reform than before; we do not "
      "reproduce the book's statement that they fell faster. The count of active 2600+ players and the top-100 mean do keep falling (section 4).")
    p("5. *Velocity* agrees in sign and order with his description (p. 20): juniors gain, the 19–34 cohort is near zero, 35–49 loses a little, 50 or "
      "more loses most, and the juniors' gain halved after the reform. Per game it mixes rating error with real ageing: older players' strength falls.")
    p("6. *The Deflation Index.* Our broadcast games give a higher domestic and a lower cross-border index than his whole-FIDE extract, and the same "
      "direction: cross-border above domestic in every year. Broadcast domestic games are stronger events than the average domestic game, and our "
      "cross-border games are mostly international opens and team events.")
    p("7. *The scale.* Our least-squares S is higher than his 459 because broadcast games are stronger and draw more, which flattens the curve; E2's "
      "fitted table shows the same through its level-dependent draw term (local scale 481 at level 1700 to 856 at 2700) [E2].")
    p("8. *The source of the −26/−16.* The research report attributes them to a 954,805-game study; the book computes them from the lists (p. 21, "
      "p. 63). The games serve the federation and Deflation Index measures.")
    p()

    # ------------------------------------------------------------------ 7 R11
    p("## 7 The April 2026 list event (D-0008, R11)")
    p()
    p(f"Standard: {n0(b['n'])} IDs first rated in March 2026 were absent in April; {n0(b['rated_again_on_a_later_list'])} of them appear on a later list. "
      f"Median rating {b['median_rating']:.0f}; by band " + ", ".join(f"{k} {n0(v)}" for k, v in sorted(b["by_band"].items())) +
      "; by age " + ", ".join(f"{k} {n0(v)}" for k, v in sorted(b["by_age"].items())) +
      f"; {b['n_federations']} federations, the largest holding {100 * b['share_top_federation']:.1f} %. Games on the March list (capped at 10): " +
      ", ".join(f"{k}: {n0(v)}" for k, v in sorted(b["games_on_march_list_capped_10"].items(), key=lambda kv: int(kv[0]))) + ".")
    p()
    p("Nearly all of them show 6 or 8 games on the March list, and they come from many federations and every age. That pattern fits a batch of "
      "events rated in March 2026 and withdrawn in April, but the lists do not say why. Layer 0 takes list membership as an input, and every cohort "
      "analysis here excludes the batch; its broadcast games (standard "
      f"{n0(M['skipped'].get('r11_batch', 0))}) are excluded too.")
    p()

    # ------------------------------------------------------------------ 8 limits
    p("## 8 Limits")
    p()
    p("- The lists carry no games. A change of published ratings is not a change of strength: a cohort can lose points because the scale moves, "
      "because its members age, or because they were over-rated. Separating these needs Layer 1 (Phase 3).")
    p("- Banding on the starting rating carries regression to the mean; the variant banded a year earlier bounds it (section 2).")
    p("- The broadcast sample is stronger and more international than the pool [E2]; the implied drain is exact for that sample and indicative "
      "for the pool. The formal test needs FIDE's game archive.")
    p("- Ghita's game extract is not public, so his Deflation Index and scale cannot be recomputed on his games; our equivalents use different games.")
    p("- \"Active\" in the book is not fully specified; section 6 shows how much the readings matter.")
    print("\n".join(P))


if __name__ == "__main__":
    main()
