#!/usr/bin/env python3
"""E7 report: turns analysis/aggregates/E7_cross_border.json into docs/evidence/E7_cross-border.md.

Reads only the committed aggregate; no data/ needed. Ghita's figures are cited
from his book with page numbers [R 5] and from his blog post of 17 February 2026
[VP 1], paraphrased; none of his tables is reproduced. Per-federation magnitudes
are not printed (annex T8.4): only the signs of the federations the book itself
names with a direction, and the distribution of the offsets without names.

Usage: python3 analysis/e7_cross_border_report.py > docs/evidence/E7_cross-border.md
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PERIODS = ("2025", "2023-2026")
SCALES = ("scale_400", "scale_459")
BANDS = ("<1600", "1600-1999", "2000-2199", "2200-2399", "2400+")
NAMES = {"PER": "Peru"}


def n0(x) -> str:
    return f"{x:,}"


def pct(x: float) -> str:
    return f"{100 * x:.0f} %"


def pval(p: float) -> str:
    return f"{p:.5f}".rstrip("0")


def main() -> None:
    d = json.loads((ROOT / "analysis" / "aggregates" / "E7_cross_border.json").read_text(encoding="utf-8"))
    smp = d["sample"]
    P: list[str] = []
    p = P.append
    y25, all_ = d["2025"], d["2023-2026"]
    t25, tall = y25["scale_400"]["direction_test"], all_["scale_400"]["direction_test"]
    same_scale = all(d[k]["scale_400"]["direction_test"]["agree_feds"] == d[k]["scale_459"]["direction_test"]["agree_feds"]
                     for k in PERIODS)
    disagree = sorted(set(t25["disagree_feds"]) | set(tall["disagree_feds"]))
    dis_names = ", ".join(NAMES.get(f, f) for f in disagree)

    p("# E7 — Ghita's federation residuals on broadcast games: the direction test")
    p("")
    p("Status: REVIEW — evidence for the proposal (prior work, the federation problem) and annex (T8.4, rung 7), session ELO-4, "
      "Phase 5.3. Generated by `analysis/e7_cross_border_report.py` from `analysis/aggregates/E7_cross_border.json`, which "
      "`analysis/e7_cross_border_extract.py` computes from the Lichess broadcast archive (https://database.lichess.org/broadcast/, "
      "CC BY-SA 4.0, attributed; aggregates only) [V 4] and FIDE's monthly standard lists (analysed, never committed or "
      "redistributed) [V 3]. Do not edit by hand. Licence: CC BY 4.0 (`docs/LICENSE-docs.md`). Ghita's book, *The Rating "
      "Revolution* (v1.0, February 2026) [R 5], is cited by page and paraphrased, and his blog post of 17 February 2026 from the "
      "verification record [VP 1]; none of his tables is reproduced. Per-federation estimates are not printed: while rung 7 is "
      "disabled they go to the QC only (annex T8.4), so this report gives the signs of the federations the book itself names "
      "with a direction, and the distribution of the rest without names.")
    p("")
    p(f"**In brief.** On {n0(y25['cross_border_games'])} cross-border standard games of 2025 between rated players in the "
      f"broadcast archive, the weighted, recursive federation offsets point the same way as Ghita's for {t25['agree']} of the "
      f"{t25['named_and_estimable']} federations he names with a direction that have enough games here (one-sided sign test "
      f"p = {pval(t25['binomial_p_one_sided'])}), and for {tall['agree']} of {tall['named_and_estimable']} on 2023–2026 "
      f"({n0(all_['cross_border_games'])} games, p = {pval(tall['binomial_p_one_sided'])})"
      + ("; the logistic scale 400 and his 459 give the same signs. " if same_scale else ". ")
      + f"The exception is {dis_names}, the weakest of his fifteen qualifying federations (recursive index +18 points, interval "
      "+10 to +26; [R 5], p. 53). The direction of his federation residuals is reproduced on games he did not use; their size is "
      "not compared, because the broadcast sample over-represents strong players (section 4) and because federation "
      "magnitudes are for the QC while rung 7 is disabled.")
    p("")

    p("## 1 What is tested")
    p("")
    p("- **Ghita's claim.** Ratings mean different strengths in different federations: in cross-border games players of some "
      "federations, mostly Asian, score well above the Elo expectation and players of several European federations below it "
      "([R 5], pp. 23–26). He measures it with a cross-border performance index, the mean of S − E over a federation's "
      "cross-border games (p. 24), refined by weighting near-even games more and by recursion over the opponents' federations "
      "(p. 25; Appendix A, pp. 66–67), with expectations at his calibrated scale S = 459 in Part V (pp. 49, 51).")
    p("- **The directions.** Taken from two of his tables, by sign only: the base cross-border residuals of 2025 (p. 26: five "
      "federations under-rated, six over-rated) and the fifteen federations that qualify for his repair on the recursive index "
      "(p. 53, all under-rated). Together, 16 named under-rated and 6 over-rated. Among the figures he states: Vietnam +101 and "
      "China +100 points, Switzerland and Austria −64 (p. 26).")
    p("- **The test.** For each of these federations with enough games in our sample, the sign of our offset is compared with "
      "his. Under the null hypothesis that our signs are unrelated to his, each agrees with probability ½, and the count of "
      "agreements is binomial; the p-value is one-sided.")
    p("")

    p("## 2 Method, and where it differs from his")
    p("")
    p("| | Ghita | E7 |")
    p("|---|---|---|")
    p(f"| games | FIDE's anonymised 2025 standard-game extract, about 954,805 games, about 189,000 cross-border after filtering "
      f"(pp. 24, 63) | broadcast standard games of the Lichess archive with both players rated on the list in force and a "
      f"federation on it: {n0(smp['standard_games'])} games 2023–2026, of which {n0(y25['cross_border_games'])} cross-border "
      f"in 2025 and {n0(all_['cross_border_games'])} in 2023–2026 |")
    p("| cross-border | the two players' federations differ; the extract records the host federation, and his estimates are "
      "described as travel-adjusted (pp. 24, 53, 63) | the two players' federations on the list in force differ; the archive does "
      "not record a host federation, so no travel adjustment is made |")
    p("| expectation | the Elo expectation; S = 459 in Part V and Appendix A (pp. 51, 66) | the logistic curve with scale 400 and "
      "with 459 |")
    p("| weight | informational: near-even games weigh more (pp. 25, 66); per game E(1 − E), with the odds capped at 90/10 [VP 1] "
      "| the same: E(1 − E) with E held within [0.1, 0.9] for the weight |")
    it = {k: {s: d[k][s]["iterations"] for s in SCALES} for k in PERIODS}
    p(f"| recursion | federation offsets updated jointly until the changes fall below a sub-point tolerance, about five iterations "
      f"on 2025 (p. 67; 0.1 point [VP 1]) | offsets updated one federation at a time (Gauss–Seidel; the simultaneous update "
      f"cycles on this sample) to a largest change below 0.1 point: {it['2025']['scale_400']} and {it['2025']['scale_459']} "
      f"passes on 2025, {it['2023-2026']['scale_400']} and {it['2023-2026']['scale_459']} on 2023–2026 (scales 400 and 459) |")
    p(f"| federations estimated | at least 1,000 cross-border games (pp. 24, 65) | at least 300 cross-border games: "
      f"{y25['federations_with_min_games']} federations on 2025 ({y25['federations_with_1000']} with 1,000 or more), "
      f"{all_['federations_with_min_games']} on 2023–2026 ({all_['federations_with_1000']} with 1,000 or more); games against "
      f"federations below the threshold count against an offset of 0 |")
    p("| level | not stated | offsets centred on their mean weighted by games, so a sign means above or below the "
      "estimated federations' average |")
    p("| exclusions | — | the batch first listed in March 2026 and removed in April (D-0008, R11) |")
    p("")

    p("## 3 Results")
    p("")
    p("| period | scale | cross-border games | federations estimated | named and estimable | agree | one-sided p | named, too few games | disagree |")
    p("|---|---|---|---|---|---|---|---|---|")
    for k in PERIODS:
        for s in SCALES:
            t = d[k][s]["direction_test"]
            p(f"| {k} | {s.split('_')[1]} | {n0(d[k]['cross_border_games'])} | {d[k]['federations_with_min_games']} | "
              f"{t['named_and_estimable']} | {t['agree']} | {pval(t['binomial_p_one_sided'])} | "
              f"{', '.join(t['not_estimable']) or '—'} | {', '.join(t['disagree_feds']) or '—'} |")
    p("")
    p("The offsets of all estimated federations, without names (points; their spread, not any federation's value, is public "
      "under annex T8.4):")
    p("")
    p("| period | scale | federations | min | p10 | median | p90 | max | SD | base index and recursive offset agree in sign |")
    p("|---|---|---|---|---|---|---|---|---|---|")
    for k in PERIODS:
        for s in SCALES:
            o = d[k][s]["offsets_distribution"]
            p(f"| {k} | {s.split('_')[1]} | {o['n']} | {o['min']:+.1f} | {o['p10']:+.1f} | {o['median']:+.1f} | {o['p90']:+.1f} | "
              f"{o['max']:+.1f} | {o['sd']:.1f} | {pct(d[k][s]['base_index_vs_recursive_sign_agreement'])} |")
    p("")
    p(f"- The {disagree[0] if disagree else ''} exception: his own estimate for {dis_names} is the smallest of the fifteen "
      "(p. 53), so it is where a sign flip on a different, smaller sample is most likely.")
    p("- Federations named in the book but below 300 cross-border games in 2025 here: "
      f"{', '.join(t25['not_estimable']) or 'none'}; all are estimable on 2023–2026.")
    p("- The cross-border games of each named federation, 2025 and 2023–2026: " +
      "; ".join(f"{f} {n0(y25['scale_400']['games_named_feds'].get(f, 0))} / {n0(all_['scale_400']['games_named_feds'].get(f, 0))}"
                for f in sorted(all_["scale_400"]["games_named_feds"])) + ".")
    p("")

    p("## 4 The sample's bias")
    p("")
    pr25, pool = y25["player_games_profile"], d["pool_2025_profile"]
    cb, dom = smp["cross_border_by_year"], smp["domestic_by_year"]
    p("| | player-games or players | median rating | " + " | ".join(BANDS) + " |")
    p("|---|---|---|" + "---|" * len(BANDS))
    p(f"| cross-border broadcast games, 2025 (player-games) | {n0(pr25['n'])} | {pr25['median']:.0f} | " +
      " | ".join(pct(pr25["share"][b]) for b in BANDS) + " |")
    pa = all_["player_games_profile"]
    p(f"| cross-border broadcast games, 2023–2026 (player-games) | {n0(pa['n'])} | {pa['median']:.0f} | " +
      " | ".join(pct(pa["share"][b]) for b in BANDS) + " |")
    p(f"| active rated pool, December 2025 list (players with a rated game in 2025) | {n0(pool['n'])} | {pool['median']:.0f} | " +
      " | ".join(pct(pool["share"][b]) for b in BANDS) + " |")
    p("")
    share25 = cb["2025"] / (cb["2025"] + dom["2025"])
    p(f"- **Who is in it.** Broadcast events are the stronger and more international end of rated chess [E2]: the median "
      f"player-game in the 2025 cross-border sample is rated {pr25['median']:.0f}, against {pool['median']:.0f} for the active "
      f"pool, and {pct(pr25['share']['<1600'])} of player-games are below 1600, against {pct(pool['share']['<1600'])} of active "
      f"players. Cross-border games are {pct(share25)} of the 2025 broadcast games between rated players with federations, "
      "where Ghita finds more than 80 % of FIDE's games domestic ([R 5], p. 23).")
    p("- **What it does to the test.** A federation's players in broadcast events are a selected part of it, stronger than "
      "its pool (the table above). Ghita's repair targets the lower bands, "
      "where he places most of the signal (pp. 51, 53, 55); our sample has few games there. Agreement in sign on this sample "
      "therefore shows that the pattern also holds for the players who play in broadcast events; it cannot show its size in "
      "the bands where he places it, and the two samples' magnitudes are not comparable.")
    p("- **Years.** Cross-border games by year: " + ", ".join(f"{y} {n0(n)}" for y, n in cb.items() if y >= "2023") +
      " (and " + ", ".join(f"{n0(n)} dated {y}" for y, n in cb.items() if y < "2023") + "); 2026 runs to the data cutoff of "
      f"{smp['broadcast']['cutoff']}, after which no game is read ({smp['broadcast']['dropped_after_cutoff']} later games dropped).")
    p(f"- **Exclusions.** Games without both players rated on the list in force: {n0(smp['skipped'].get('not_rated_on_list_in_force', 0))}; "
      f"games involving the R11 batch: {n0(smp['skipped'].get('r11_batch', 0))}.")
    p("")

    p("## 5 What it means for the proposal")
    p("")
    p("- The direction of Ghita's federation residuals stands on an independent sample and method: the federation problem is "
      "real for the broadcast population, not an artefact of his data. The proposal says so and credits him with the finding "
      "and the method.")
    p("- It does not decide rung 7 (federation offsets), which stays disabled: the evidence here is directional, the sample "
      "is biased toward the strong players, in whose bands Ghita places the least of the signal, and per-federation magnitudes "
      "would need FIDE's game archive. The monitoring "
      "of annex T8.4 (cross-federation residuals to the QC, their distribution in public) is the step this supports.")
    p("- Ghita's repair for these federations (an activity bonus and a calibrated reset, pp. 55–59) is compared with ours "
      "mechanism by mechanism in `docs/research/PRIOR-WORK_2026-10-10.md`, which the proposal's prior-work section draws on.")
    print("\n".join(P))


if __name__ == "__main__":
    main()
