#!/usr/bin/env python3
"""E8 report: turns analysis/aggregates/E8_k_activity.json into docs/evidence/E8_k-from-activity.md.

Reads only committed aggregates (E8, and E6 for the comparison with R6's K from broadcast games); no data/
needed. Applies rung 4's pre-registered decision rules (annex T8.1–T8.2; SPEC-K-ACTIVITY §6) exactly as
analysis/e6_rungs_report.py applies them, with its helper functions imported unchanged.

Usage: python3 analysis/e8_k_activity_report.py > docs/evidence/E8_k-from-activity.md
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
import e6_rungs_report as r6  # noqa: E402  (the decision helpers, unchanged)

AGG = ROOT / "analysis" / "aggregates"
TCS = ("standard", "rapid", "blitz")
BANDS = ("<1600", "1600-1999", "2000-2399", "2400-2599", "2600+")


def q3(d: dict) -> str:
    return "—" if not d.get("n") else f"{d['median']} ({d['p10']} to {d['p90']})"


def main() -> None:
    d = json.loads((AGG / "E8_k_activity.json").read_text(encoding="utf-8"))
    e6 = json.loads((AGG / "E6_rungs.json").read_text(encoding="utf-8"))["rung4"]
    t, ta = d["test"], d["test_all_rated_players"]
    P: list[str] = []
    p = P.append

    def verdict(x: dict) -> tuple[bool, bool, str]:
        top = x["log_loss_difference_top_quartile"]
        ok = bool(top.get("n")) and top["hi"] < 0
        hok, hwhy = r6.harm(x["log_loss_difference"], x["calibration"])
        return ok, hok, hwhy

    ok, hok, hwhy = verdict(t)
    oka, hoka, hwhya = verdict(ta)
    passes = ok and hok
    ch = d["chosen"]
    el, cl = d["established_oct2026"]["elite"], d["established_oct2026"]["club"]

    p("# E8 — K from FIDE's activity record: rung 4 redesigned")
    p("")
    p("Status: REVIEW — evidence for the proposal (§5, §9) and annex (T4.3, T8.1, T8.10), session ELO-5, Phase 1. Generated by "
      "`analysis/e8_k_activity_report.py` from `analysis/aggregates/E8_k_activity.json`, which "
      "`analysis/e8_k_activity_extract.py` computes under `docs/specs/SPEC-K-ACTIVITY_v1_0.md` from FIDE's monthly lists "
      "(analysed, never committed or redistributed) [V 3] and the Lichess broadcast archive "
      "(https://database.lichess.org/broadcast/, CC BY-SA 4.0, attributed; aggregates only) [V 4]; Layer 0 is `src/layer0/`. "
      "Do not edit by hand. Licence: CC BY 4.0 (`docs/LICENSE-docs.md`). Every parameter is PROVISIONAL.")
    p("")
    p(f"**In brief.** Rung 4 {'passes' if passes else 'does not pass'} with K built from FIDE's activity record. The "
      "certainty comes from the games field of every monthly list since February 2015, not from broadcast games, and K "
      "falls with the period's games (R16). On the months and rules E6 used, the forecasts of the players whose K changes "
      f"most are {'better' if t['log_loss_difference_top_quartile']['mean'] < 0 else 'worse'} by "
      f"{abs(t['log_loss_difference_top_quartile']['mean']):.5f} nats a game "
      f"(interval {t['log_loss_difference_top_quartile']['lo']:+.5f} to {t['log_loss_difference_top_quartile']['hi']:+.5f}), "
      f"which {'meets' if ok else 'does not meet'} the targeted rule, and the do-no-harm check is "
      f"{'met' if hok else 'not met'} (overall {r6.ci(t['log_loss_difference'], 5)}). "
      f"E6's version, with σ from broadcast games, was worse by {e6['log_loss_difference_top_quartile']['mean']:.5f} "
      f"(interval {e6['log_loss_difference_top_quartile']['lo']:+.5f} to {e6['log_loss_difference_top_quartile']['hi']:+.5f}) "
      f"and failed both. Established players rated 2600 or more receive a median K of "
      f"{t['k_elite_2600_standard']['median']} in the test months (E6: {e6['k_elite_2600_standard']['median']}; today 10); "
      f"established club adults rated 1600–1999, who play a median {cl['games_12_lists']['median']:.0f} rated games a "
      f"year, receive {cl['K_n1']['median']} for a one-game period and {cl['K_n9']['median']} for nine games (today 20). "
      + ("Rung 4 becomes the activity-record design (D-0009, reading 8)." if passes else
         "Rung 4 therefore joins TEST ON FIDE DATA (R22): it no longer harms forecasts, but it does not yet improve them "
         "measurably on broadcast games."))
    p("")

    # ---------------------------------------------------------------- 1
    p("## 1 What changed from E6")
    p("")
    p("- **Certainty from the lists.** σ_i is a Glicko-style variance in latent units built from FIDE's monthly lists alone: "
      "each period's rated games add q²·v_tc of information per game (v_tc the published table's score variance at equal "
      "ratings in the player's band), and every month adds c² = (c_K·p(age))², with p the age profile of SPEC-L1 §3.7, up "
      "to the newcomer's 250 (SPEC-K-ACTIVITY §3). Broadcast games never enter σ_i.")
    p("- **K falls with the period's games (R16).** K_i(n) = clip(q σ_i² / (κ_tc (1 + n q² σ_i² v_tc)), 10, 40), with n the "
      "period's rated games from the next list; in the test months n had a median of "
      f"{t['n_used']['median']:.0f} (p10 {t['n_used']['p10']:.0f}, p90 {t['n_used']['p90']:.0f}).")
    p("- **Everything else is E6's.** The months, the population (the players E6 could give a Layer 1 estimate), the carry and "
      "forecast steps, the targeted group, the bootstrap and the decision rules are E6 §3's; the harness functions are imported "
      "unchanged from `analysis/e6_rungs_extract.py` (SPEC-K-ACTIVITY §6).")
    p("")

    # ---------------------------------------------------------------- 2
    p("## 2 The growth scale, chosen before the test months")
    p("")
    p(f"c_K was chosen per time control on carry months {d['choice_months'][0]} to {d['choice_months'][-1]} (forecasts of the "
      "following month), before E6's first test month, by the mean three-outcome log-loss of every forecast game; the grid was "
      "fixed before the fit (SPEC-K-ACTIVITY §5). Mean log-loss, nats a game:")
    p("")
    p("| c_K | " + " | ".join(TCS) + " |")
    p("|---|---|---|---|")
    for ck in d["grid"]:
        row = d["choice"][str(float(ck))]["mean_log_loss"]
        p(f"| {ck} | " + " | ".join(f"{row[tc]:.6f}" + (" (chosen)" if ch[tc] == ck else "") for tc in TCS) + " |")
    games = d["choice"][str(float(d["grid"][0]))]["forecast_games"]
    p("")
    p("Forecast games in the choice months: " + ", ".join(f"{tc} {games[tc]:,}" for tc in TCS) + ". Chosen: "
      + ", ".join(f"{tc} {ch[tc]} (adult growth {12 * ch[tc]:g} latent points a month)" for tc in TCS)
      + "; " + ("none at an edge of the grid." if not any(d["chosen_at_grid_edge"].values()) else
                "at an edge of the grid: " + ", ".join(tc for tc in TCS if d["chosen_at_grid_edge"][tc]) + " (flagged)."))
    p("")

    # ---------------------------------------------------------------- 3
    p("## 3 The test (as E6 §3)")
    p("")
    p(f"Carry months {d['test_carry_months'][0]} to {d['test_carry_months'][-1]}; each player's rating carried through the "
      "month's broadcast games with FIDE's K and with K_i(n), the next month's games forecast from the carried ratings with "
      "Layer 0's expected score. Differences are the rung minus Layer 0 (negative is better).")
    p("")
    p("| metric | games | rung 4 (activity record) minus Layer 0 | E6: rung 4 (broadcast σ, R6) minus Layer 0 |")
    p("|---|---|---|---|")
    for name, key in (("log-loss, players whose K changes most (targeted)", "log_loss_difference_top_quartile"),
                      ("Brier, same games", "brier_difference_top_quartile"),
                      ("log-loss, every forecast game", "log_loss_difference"),
                      ("Brier, every forecast game", "brier_difference")):
        p(f"| {name} | {r6.n0(t[key].get('n'))} | {r6.ci(t[key], 5)} | {r6.ci(e6[key], 5)} |")
    p("")
    p("By time control (log-loss, every forecast game): " + "; ".join(
        f"{tc} {r6.ci(t['log_loss_difference_by_tc'][tc], 5)} ({r6.n0(t['log_loss_difference_by_tc'][tc]['n'])} games)"
        for tc in TCS) + ".")
    p("")
    p(f"- **Targeted rule** (log-loss better than Layer 0's with the interval excluding zero): {'met' if ok else 'not met'}.")
    p(f"- **Do no harm:** {hwhy}.")
    p(f"- **Verdict on broadcast data:** rung 4 {'passes' if passes else 'does not pass'}.")
    p(f"- **Robustness** (every rated player of the month's games, without E6's Layer 1 condition; {r6.n0(ta['log_loss_difference']['n'])} "
      f"forecast games): targeted {r6.ci(ta['log_loss_difference_top_quartile'], 5)}, overall "
      f"{r6.ci(ta['log_loss_difference'], 5)}; targeted rule {'met' if oka else 'not met'}, do no harm "
      f"{'met' if hoka else 'not met'}: the same reading.")
    p("")

    # ---------------------------------------------------------------- 4
    p("## 4 The K players receive")
    p("")
    p("In the test months (player-months with a broadcast game; K_i(n) median, p10 to p90), against R6's K from broadcast "
      "games in E6:")
    p("")
    p("| time control | band | player-months | K_i(n), activity record | E6: K_i, broadcast σ |")
    p("|---|---|---|---|---|")
    for tc in TCS:
        for b in BANDS:
            a = t["k_by_band"].get(f"{tc}|{b}", {})
            e = e6["k_by_band"].get(f"{tc}|{b}", {})
            p(f"| {tc} | {b} | {r6.n0(a.get('n'))} | {q3(a)} | {q3(e)} |")
    p("")
    p("| time control | FIDE's K | player-months | K_i(n), activity record | E6: K_i, broadcast σ |")
    p("|---|---|---|---|---|")
    for tc in TCS:
        for k in (10, 20, 40):
            a = t["k_by_fide_k"].get(f"{tc}|{k}", {})
            e = e6["k_by_fide_k"].get(f"{tc}|{k}", {})
            p(f"| {tc} | {k} | {r6.n0(a.get('n'))} | {q3(a)} | {q3(e)} |")
    p("")
    p(f"**Established players at the October 2026 list** (standard; the certainty for the period that the November 2026 list "
      "will rate):")
    p("")
    p("| group | players | rated games, 12 lists | σ_i (latent) | N_i (games of certainty) | K_i(1) | K_i(4) | K_i(9) | K_i(n) for their last period (n) | FIDE's K |")
    p("|---|---|---|---|---|---|---|---|---|---|")
    for name, g in (("elite: rated 2600+, aged 20+", el), ("club adults: rated 1600–1999, aged 25–60", cl)):
        p(f"| {name} | {r6.n0(g['K_n1']['n'])} | {q3(g['games_12_lists'])} | {q3(g['sigma'])} | {q3(g['N_certainty'])} | "
          f"{q3(g['K_n1'])} | {q3(g['K_n4'])} | {q3(g['K_n9'])} | {q3(g['K_last_period'])} ({g['last_period_games']['median']:.0f}) | "
          f"{q3(g['published_k'])} |")
    p("")
    p("Definitions: " + "; ".join(f"{k}: {v}" for k, v in sorted(d["established_definitions"].items())) + ". Medians, with the "
      "10th and 90th percentiles in brackets. N_i is D-0009's published form: K_i(n) = C/(N_i + n) before clipping.")
    p("")
    st = d["steady_state_standard"]
    p("**Steady states** (standard, the chosen growth, the same number of rated games every month; σ_i latent and K_i(n) for "
      "that month's games):")
    p("")
    p("| player | rating | 1 game a month | 2 games | 4 games | 8 games |")
    p("|---|---|---|---|---|---|")
    for label, name in (("adult_25_45", "adult aged 25–45"), ("junior_12_15", "junior aged 12–15")):
        for r in (1800, 2300, 2700):
            p(f"| {name} | {r} | " + " | ".join(f"K {st[f'{label}|{r}|{g}']['K']} (σ {st[f'{label}|{r}|{g}']['sigma']})"
                                                for g in (1, 2, 4, 8)) + " |")
    p("")
    s0, s4 = t["monthly_change_established"]["layer0"], t["monthly_change_established"]["rung4"]
    se0, se4 = e6["monthly_change_established"]["layer0"], e6["monthly_change_established"]["rung4"]
    p(f"- **Stability of established ratings** (adults with FIDE's K of 10 or 20, the absolute change from one month's "
      f"broadcast games): median {s0['median']} points with FIDE's K and {s4['median']} with K_i(n); p90 {s0['p90']} and "
      f"{s4['p90']} (E6, with broadcast σ: {se0['median']} and {se4['median']}; p90 {se0['p90']} and {se4['p90']}).")
    p("")

    # ---------------------------------------------------------------- 5
    p("## 5 Reading")
    p("")
    p("- **Why E6's rung 4 failed, and what the redesign fixes.** With σ from broadcast games most players looked uncertain and "
      "sat at K = 40; with σ from every rated game on FIDE's lists the K of established players falls to about today's level "
      f"or a little above it (elite median {t['k_elite_2600_standard']['median']} against E6's "
      f"{e6['k_elite_2600_standard']['median']}), monthly changes no longer double, and the forecasts are no worse than "
      "Layer 0's (do no harm met).")
    p("- **Why it does not pass.** The targeted rule asks for forecasts measurably better than today's for the players whose K "
      "changes most. The difference is within noise overall and in standard and rapid, and worse in blitz, where the chosen "
      "growth is largest. A K from activity alone cannot see whom a player met or how the results went: it rises for players "
      "who play rarely, such as most club adults, whatever their stability, and the lists cannot show whether that is "
      "warranted.")
    p("- **What would settle it.** FIDE's tournament reports (the TRF archive): opponents and results for every rated game, "
      "so that the certainty can count each game's information and be tested on the whole pool, juniors and club players "
      "included, rather than on the broadcast population (annex T8.6).")
    p("")

    # ---------------------------------------------------------------- 6
    p("## 6 Limits")
    p("")
    p("- The broadcast population is stronger and more international than the rated pool [E2]; the test covers it only.")
    p("- The lists count games, not opponents: each game is counted at equal strength, which overstates the information of "
      "games against much weaker or stronger opponents (SPEC-K-ACTIVITY §9).")
    p("- The recursion has no drift; juniors' improvement enters only through the larger growth of the young age bands.")
    p("- The games field counts games rated in a period, which can lag the games themselves.")
    p("- c_K was chosen on 2023–2024 broadcast months, which hold fewer games than 2025–2026 (the archive grows from 2024): "
      + ", ".join(f"{tc} {games[tc]:,}" for tc in TCS) + " forecast games, so the rapid and blitz growth rests on little data, "
      "and blitz, whose chosen growth is the largest, is where the rung's forecasts are worse.")
    sys.stdout.write("\n".join(P) + "\n")


if __name__ == "__main__":
    main()
