#!/usr/bin/env python3
"""Calculations for the v1.0 documents with the table calibrated by level (session ELO-6, Phase 5).

The v1.0 calculations (analysis/v10_calculations.py, output analysis/OUTPUT_v1_0.md) use Freeze 1's table. This script
recomputes, with the v2 table of params/table_fit_2026-10b.yaml (E11), the narrowed guard of
params/guard_2026-10b.yaml (E12) and the slope ratio m of R32, the figures the documents tie to rung 2's table: the
table's excerpt and band-edge steps, its local scale, rung 4's constant C and K under rulings R16, R25 and R36,
worked examples (i) and (ii), table 8.1.1 against the v2 table, colour, and the stake of one game under K × m.
Every parameter is PROVISIONAL (or PROVISIONAL-FITTED for the table's). Python standard library only; deterministic.

Usage: python3 analysis/elo6_calculations.py > analysis/OUTPUT_ELO6.md
"""
from __future__ import annotations

import math
import sys
from decimal import ROUND_DOWN, ROUND_HALF_UP, Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
import layer0  # noqa: E402
from layer2 import guard_v2 as gv2  # noqa: E402
from layer2 import table_v2 as t2  # noqa: E402

TEXT = (ROOT / "params" / "table_fit_2026-10b.yaml").read_text(encoding="utf-8")
V2 = {tc: t2.load(TEXT, tc) for tc in ("standard", "rapid", "blitz")}
PAR = V2["standard"]["par"]
ETA = t2.eta_whole(PAR[2])
Q = t2.Q
K_MIN, K_MAX, TAU, Z90, C_CAP = 10.0, 40.0, 25, Decimal("1.2816"), 300
out: list[str] = []
P = out.append


def nu0(par: tuple, mid: float) -> float:
    return math.exp(par[3] + par[4] * t2.ell(mid))


def v_of(par: tuple, rating: float) -> float:
    """The score variance at an even gap in the player's own level band, 1/(2(2 + ν₀)) (annex T4.3)."""
    return 1.0 / (2.0 * (2.0 + nu0(par, t2.band_mid(int(rating)))))


def c_of(par: tuple, rating: float) -> float:
    """C_tc(L) = 1/(κ_tc(L) q v_tc(L)) in the player's band: the inverse of the table's slope at an even gap."""
    return 1.0 / t2.slope_at_zero(par, t2.band_mid(int(rating)))


def k_raw(par: tuple, sigma: float, rating: float, n: int) -> float:
    """R16 before the clip: q σ² / (κ(L) (1 + n q² σ² v)); κ(L) the table's slope in the band."""
    kap = t2.kappa_at(par, t2.band_mid(int(rating)))
    v = v_of(par, rating)
    return Q * sigma * sigma / (kap * (1.0 + n * Q * Q * sigma * sigma * v))


def k_n(par: tuple, sigma: float, rating: float, n: int) -> Decimal:
    """R16: K_i(n) = clip(q σ² / (κ(L) (1 + n q² σ² v)), 10, 40), one decimal."""
    raw = k_raw(par, sigma, rating, n)
    return Decimal(repr(min(K_MAX, max(K_MIN, raw)))).quantize(Decimal("0.1"), rounding=ROUND_HALF_UP)


def k_bounded(par: tuple, sigma: float, rating: float, n: int) -> Decimal:
    """R25 and R36: n K(n) at most max(C, 700); K cut down to one decimal where the bound binds."""
    k = k_n(par, sigma, rating, n)
    bound = Decimal(repr(max(c_of(par, rating), 700.0))) / n
    return k if k <= bound else bound.quantize(Decimal("0.1"), rounding=ROUND_DOWN)


def e_pub(x: int, mid: int) -> Decimal:
    return t2.published(x, mid, PAR)


def band_label(mid: int) -> str:
    return "below 1500" if mid == 1450 else "2800 and above" if mid == 2850 else f"{mid - 50}–{mid + 49}"


# ------------------------------------------------------------------------------------------------ 0
P("# Calculations for the v1.0 documents with the table calibrated by level (ELO-6)\n")
P("Generated by `analysis/elo6_calculations.py` from `params/table_fit_2026-10b.yaml` and `params/guard_2026-10b.yaml`; do not "
  "edit by hand. Cited in the documents as \"script v2 §n\". Every parameter is PROVISIONAL, the table's PROVISIONAL-FITTED "
  "on broadcast games [E11].\n")
P("## 0 Parameters used\n")
P("| time control | κ | λ | η | α | β | γ | μ | m applies (R32) |")
P("|---|---|---|---|---|---|---|---|---|")
for tc, v in V2.items():
    P(f"| {tc} | " + " | ".join(f"{x:g}" for x in v["par"]) + f" | {v['k_scale_applies']} |")
P(f"\nη is used as {ETA} points in standard (whole points, annex T3.4).\n")

# ------------------------------------------------------------------------------------------------ 1
P("## 1 The v2 table, standard (every other band; the published entry at effective gap x, colour included; E to three decimals)\n")
mids = (1450, 1650, 1850, 2050, 2250, 2450, 2650, 2850)
P("| x | " + " | ".join(("<1500" if m == 1450 else "≥2800" if m == 2850 else f"{m - 50}–{m + 49}") for m in mids) + " |")
P("|---|" + "---|" * len(mids))
for x in range(0, 1001, 100):
    P(f"| {x} | " + " | ".join(f"{e_pub(x, m)}" for m in mids) + " |")
P("\nThe equal-strength draw probability ν₀/(2 + ν₀): " + ", ".join(
    f"{m}: {nu0(PAR, m) / (2 + nu0(PAR, m)):.3f}" for m in (1450, 2050, 2850)) + ".\n")

# ------------------------------------------------------------------------------------------------ 2
P("## 2 Band-edge steps: max over x in [0, 1500] of |E(x; band b) − E(x; band b+1)|\n")
P("| time control | unrounded: largest step (x, bands) | published three decimals | lowest two bands |")
P("|---|---|---|---|")
for tc, v in V2.items():
    par = v["par"]
    best, best_pub, low = (0.0, 0, 0), Decimal(0), 0.0
    for i in range(len(t2.BAND_MIDS) - 1):
        a, b = t2.BAND_MIDS[i], t2.BAND_MIDS[i + 1]
        for x in range(0, 1501):
            d = abs(t2.expected_effective(x, a, par) - t2.expected_effective(x, b, par))
            if d > best[0]:
                best = (d, x, a)
            dp = abs(t2.published(x, a, par) - t2.published(x, b, par))
            best_pub = max(best_pub, dp)
            if i == 0:
                low = max(low, d)
    P(f"| {tc} | {best[0]:.4f} (x = {best[1]}, {band_label(best[2])} to the next band) | {best_pub} | {low:.4f} |")
P("\nWith λ the slope itself changes from band to band, by a factor exp(λ/4); the steps are a table-resolution effect, the same "
  "for both players.\n")

# ------------------------------------------------------------------------------------------------ 3
P("## 3 The local scale near equal ratings (annex T3.2, item 4; T3.5)\n")
P("dE/dx at x = 0 is κ(L) q / (2(2 + ν₀(L))); the table behaves there like logistic Elo with a scale of 200 (2 + ν₀)/κ(L) points:\n")
P("| level | standard: κ(L) | v(L) = 1/(2(2 + ν₀)) | scale, points | E′(0) | Freeze 1's scale |")
P("|---|---|---|---|---|---|")
V1 = (1.2120, 35.91, 0.2860, 0.4985, 0.2915)
for lv in (1700, 2300, 2700):
    m = t2.band_mid(lv)
    kap = t2.kappa_at(PAR, m)
    n0 = nu0(PAR, m)
    n1 = math.exp(V1[2] + V1[3] * t2.ell(m))
    P(f"| {lv} | {kap:.3f} | {1 / (2 * (2 + n0)):.4f} | {200 * (2 + n0) / kap:.1f} | {t2.slope_at_zero(PAR, m):.5f} | "
      f"{200 * (2 + n1) / V1[0]:.1f} |")
P("")

# ------------------------------------------------------------------------------------------------ 4
P("## 4 Rung 4 with the v2 table: C, K and the period bound (R16, R25, R36)\n")
cs = {m: c_of(PAR, m) for m in t2.BAND_MIDS}
P("C_tc(L) = 1/(κ(L) q v(L)) by level band, standard, one decimal (the published form K_i(n) = clip(C/(N_i + n)), "
  "D-0009 reading 3):\n")
P("| band | " + " | ".join(str(m) for m in t2.BAND_MIDS) + " |")
P("|---|" + "---|" * len(t2.BAND_MIDS))
P("| C | " + " | ".join(f"{c:.1f}" for c in cs.values()) + " |")
P(f"\nC ranges from {min(cs.values()):.1f} to {max(cs.values()):.1f} in standard; " + "; ".join(
    f"{tc} {min(c_of(V2[tc]['par'], m) for m in t2.BAND_MIDS):.1f} to {max(c_of(V2[tc]['par'], m) for m in t2.BAND_MIDS):.1f}"
    for tc in ("rapid", "blitz")) + ". Where C exceeds today's 700 the period bound max(C, 700) of R36 is C.\n")
P("K_i(n) at level 1700, one decimal:\n")
P("| latent σ | N_i | K(1) | K(4) | K(9) | K(20) | K(30) | 30 × K(30) |")
P("|---|---|---|---|---|---|---|---|")
for s in (55, 70, 250):
    nn = 1.0 / (Q * Q * s * s * v_of(PAR, 1700))
    ks = [k_bounded(PAR, s, 1700, n) for n in (1, 4, 9, 20, 30)]
    P(f"| {s} | {nn:.1f} | " + " | ".join(str(k) for k in ks) + f" | {30 * ks[-1]} |")
P("")
k5, k14 = k_bounded(PAR, 70, 1700, 5), k_bounded(PAR, 70, 1700, 14)
P(f"- **R25, one K per event.** σ = 70 at level 1700: a five-game event keeps K(5) = {k5} once rated; a nine-game event later "
  f"in the period is rated with K(14) = {k14}. Under D-0009's reading 2 every game of the period took K(14), so a player "
  "who stopped after a good event and played on after a bad one gained in expectation (script §13.2, with Freeze 1's "
  "table); under R25 the first event's K no longer depends on what follows, and that lever is closed.")
tot = sum(10 * k_bounded(PAR, 250, 1700, n) for n in (10, 20, 30))
P(f"- **R36, the bound.** n K(n) ≤ max(C, 700) per event. A newcomer at the prior's σ = 250 in band 1700–1799 playing three "
  f"ten-game events in one period has K = {k_bounded(PAR, 250, 1700, 10)}, {k_bounded(PAR, 250, 1700, 20)} and "
  f"{k_bounded(PAR, 250, 1700, 30)}: the period's games can move the rating by up to {tot} points, against C = "
  f"{cs[1750]:.1f} and today's 700.\n")

# ------------------------------------------------------------------------------------------------ 5
P("## 5 Worked example (i) with the v2 table: a 1900 adult (White, latent σ 55) v a junior listed at 1500 (Black) whom "
  "Layer 1 rates at 1850 with σ̃ = 100\n")
th, sg, ra, rj = Decimal(1850), Decimal(100), 1900, 1500
craw = th - Z90 * sg - rj - TAU
cj = min(C_CAP, max(0, int(craw.quantize(Decimal(1), rounding=ROUND_HALF_UP))))
rx = rj + cj
mid = t2.band_mid((ra + rj) // 2)
x_a, x_a0, x_j = ra - rx + ETA, ra - rj + ETA, rj - ra - ETA
e_a, e_a0, e_j = e_pub(x_a, mid), e_pub(x_a0, mid), e_pub(x_j, mid)
ka, kj = k_n(PAR, 55, ra, 1), k_n(PAR, 1.212 * 100, rj, 1)
P(f"- c_J = min(300, max(0, 1850 − 1.2816 × 100 − 1500 − 25)) = {craw} → {cj}; RX_J = {rx}. Level {(ra + rj) // 2}, band "
  f"{mid - 50}–{mid + 49}.")
P(f"- x_A = {ra} − {rx} + {ETA} = {x_a}, E_A = {e_a}; without compensation x = {x_a0}, E_A0 = {e_a0}. x_J = {x_j}, E_J = {e_j} "
  f"(J's own update uses published ratings). Gap {ra - rj}, level {(ra + rj) / 2:g}: outside the guard's region.")
P(f"- With rung 4 (all rungs): K_A = {ka} (latent σ 55 at R = 1900), K_J = {kj} (latent σ 121.2). Today: .92 / .08 (row "
  "392–411 of table 8.1.2), K = 20 for A and 40 for J [V 1].\n")
P("| Result | A today: 20 × (S − .92) | J today: 40 × (S − .08) | A, all rungs: K_A × (S − E_A) | J, all rungs: K_J × (S − E_J) |")
P("|---|---|---|---|---|")
for lab, sa in (("A wins", Decimal(1)), ("Draw", Decimal("0.5")), ("J wins", Decimal(0))):
    ta, tj = 20 * (sa - Decimal("0.92")), 40 * ((1 - sa) - Decimal("0.08"))
    la, lj = ka * (sa - e_a), kj * ((1 - sa) - e_j)
    rnd = lambda v: v.quantize(Decimal(1), rounding=ROUND_HALF_UP)  # noqa: E731
    P(f"| {lab} | {ta:+.1f} → {rnd(ta):+} | {tj:+.1f} → {rnd(tj):+} | {la:+.4f} → {rnd(la):+} | {lj:+.4f} → {rnd(lj):+} |")
P(f"\nCompensation creates K_A × (E_A0 − E_A) = {ka * (e_a0 - e_a):+.4f} points in this game whatever the result (ledger line 3, "
  f"annex T6). E_A + E_J = {e_a + e_j}.\n")
P(f"Ledger lines for the game (annex T6), E_A0 = {e_a0}:\n")
P("| Result | transfer J → A, ½(K_A + K_J)(S_A − E_A0) | created by unequal K, (K_A − K_J)(S_A − E_A0) | created by compensation, K_A (E_A0 − E_A) | sum of both changes |")
P("|---|---|---|---|---|")
for lab, sa in (("A wins", Decimal(1)), ("Draw", Decimal("0.5")), ("J wins", Decimal(0))):
    tr = (ka + kj) / 2 * (sa - e_a0)
    cu = (ka - kj) * (sa - e_a0)
    cc = ka * (e_a0 - e_a)
    P(f"| {lab} | {tr:+.4f} | {cu:+.4f} | {cc:+.4f} | {ka * (sa - e_a) + kj * ((1 - sa) - e_j):+.4f} |")
P("")

# ------------------------------------------------------------------------------------------------ 6
P("## 6 Worked example (ii) with the v2 table and the narrowed guard: the strong player has White\n")
P("Today's K is 10 for both [V 1]. Rung 2 alone multiplies it by the printed m of the game's band (R32); with rung 4 K comes "
  f"from certainty instead (latent σ 45: raw {k_raw(PAR, 45, 2600, 1):.2f} at 2600 and {k_raw(PAR, 45, 2700, 1):.2f} at 2700, "
  f"clipped to K_min = {K_MIN}), without m.\n")
start = layer0.rules.AMENDMENT_2650


def row(rp: int, ro: int):
    d_used = layer0.effective_difference(rp, ro, "standard", start)
    pd = layer0.expected_score(d_used)
    mid = t2.band_mid((rp + ro) // 2)
    x = rp - ro + ETA
    e = e_pub(x, mid)
    w = gv2.weight(rp, ro)
    g, binds = gv2.guard_own(e, x, True, w)
    return d_used, pd, mid, x, e, w, g, binds, V2["standard"]["k_scale"][mid]


P("| Player | Opponent | Today: D used, PD | Today: win / draw / loss | v2: x, band, E | with the guard: w, E | rung 2 alone: K × m, win / draw / loss | rungs 2 and 4: K, win / draw / loss |")
P("|---|---|---|---|---|---|---|---|")
bound_rows = 0
for rp, ro in ((2600, 2100), (2700, 2100)):
    d_used, pd, mid, x, e, w, g, binds, m = row(rp, ro)
    bound_rows += binds
    today = " / ".join(f"{10 * (s - pd):+.1f}" for s in (Decimal(1), Decimal("0.5"), Decimal(0)))
    k2 = 10 * m
    k4 = k_n(PAR, 45, rp, 1)
    r2 = " / ".join(f"{k2 * (s - g):+.4f}" for s in (Decimal(1), Decimal("0.5"), Decimal(0)))
    r4 = " / ".join(f"{k4 * (s - g):+.4f}" for s in (Decimal(1), Decimal("0.5"), Decimal(0)))
    P(f"| {rp} | {ro} | {d_used}, {pd} | {today} | {x}, {band_label(mid)}, {e} | {w}, {g} | {k2}: {r2} | {k4}: {r4} |")
P("")
P("The cliff at 2650 today and under rung 2 v2 with the guard (each player beats a 2200 with White; today's K = 10, rung 2 at "
  "today's K times m):\n")
P("| Winner | Today: gap used, PD, gain at K = 10 | v2: x, band, E | with the guard: w, E | K × m, gain |")
P("|---|---|---|---|---|")
for rp in (2649, 2651, 2700, 2936):
    d_used, pd, mid, x, e, w, g, binds, m = row(rp, 2200)
    bound_rows += binds
    P(f"| {rp} | {d_used}, {pd}, {10 * (1 - pd):+.1f} | {x}, {band_label(mid)}, {e} | {w}, {g}"
      f"{'' if x <= gv2.X_MAX else ' (beyond 735: no guard)'} | {10 * m}, {10 * m * (1 - g):+.4f} |")
P(f"\nThe guard binds in {bound_rows} of the 6 rows and lifts the favourite towards table 8.1.2's entry at the colour-adjusted "
  "gap; the 2650 cliff of today's rule is gone (2649 and 2651 read the same table and gain the same); beyond a colour-adjusted "
  "gap of 735 the guard stops and the v2 table's own value applies, so no result is worth exactly nothing.")
# ------------------------------------------------------------------------------------------------ 7
P("\n## 7 Table 8.1.1 against the v2 table (§8.2.3 under rung 2 alone; annex T11)\n")
P("Rung 2 alone keeps table 8.1.1 for initial ratings (§8.2.3 [V 1]). The smallest whole-number effective gap at which "
  "the v2 table (standard, unrounded) reaches a score p, by band midpoint; 8.1.1's dp as transcribed in "
  "`analysis/v10_calculations.py` [V 1]:\n")
MIDS = (1650, 2050, 2450, 2850)
P("| p | 8.1.1 dp [V 1] | " + " | ".join(f"band midpoint {m}" for m in MIDS) + " |")
P("|---|---|" + "---|" * len(MIDS))
for pval, dp in ((0.75, 193), (0.92, 401)):
    gaps = []
    for m in MIDS:
        x = 0
        while t2.expected_effective(x, m, PAR) < pval and x < 2000:
            x += 1
        gaps.append(x)
    P(f"| {pval} | {dp} | " + " | ".join(str(g) for g in gaps) + " |")
# ------------------------------------------------------------------------------------------------ 8
P(f"\n## 8 Colour inside the expectation with the v2 table (standard, η = {ETA}; annex T3.2, item 6)\n")
for lv in (1700, 2000, 2500):
    mid = t2.band_mid(lv)
    ew = t2.expected_effective(ETA, mid, PAR)
    P(f"- Equal ratings in band {band_label(mid)}: E(White) = {ew:.4f} (published {e_pub(ETA, mid)}), E(Black) = "
      f"{1 - ew:.4f}; today's table gives .50 to each [V 1]; expected gain per extra White today at K = 20: "
      f"{20 * (ew - 0.5):+.2f} points; with colour in the table: 0.00 by construction.")
# ------------------------------------------------------------------------------------------------ 9
P("\n## 9 Rung 2 at today's K: the stake of one game under K × m (R32; annex T1, T3.4, P2)\n")
jr, op = 2290, 2780                                   # a junior with today's K = 40, Black, against a much stronger White
mid = t2.band_mid((jr + op) // 2)
x_fav = op - jr + ETA
e_fav = e_pub(x_fav, mid)
g_fav, binds = gv2.guard_own(e_fav, x_fav, True, gv2.weight(op, jr))
e_j = Decimal(1) - g_fav
km = 40 * V2["standard"]["k_scale"][mid]
P(f"- A junior rated {jr} with today's K = 40 beats a {op} with Black: level band {band_label(mid)}, m = "
  f"{V2['standard']['k_scale'][mid]}, so K × m = {km}; the favourite's expectation {e_fav}"
  f"{f', guarded to {g_fav}' if binds else ''}, the junior's {e_j}; the win is worth {km * (1 - e_j):+.2f} points "
  "(today's K_max of rung 4 is 40).")
step = Decimal("0.006")
m_lo = max(V2["standard"]["k_scale"][1450], V2["standard"]["k_scale"][1550])
P(f"- The published table's largest band-edge step in standard, {step} (§2, between the bands below 1500 and 1500–1599), "
  f"moves a game term at K = 20 by at most {20 * step:.2f} points, and by {20 * step * m_lo:.2f} with the m of those "
  f"bands (at most {m_lo}).")
print("\n".join(out))
