#!/usr/bin/env python3
"""SPEC-L0 R-18..R-22: summary of the published-K aggregates for SPEC-L0.

Reads analysis/aggregates/L0_k_rules.json (written by analysis/l0_k_rules_extract.py
from the FIDE standard lists, which are never committed) and prints the tables
that SPEC-L0 cites. Counts only. Python standard library only.

Usage: python3 analysis/l0_k_rules_report.py > analysis/OUTPUT_L0_k_rules.md
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AGG = ROOT / "analysis" / "aggregates" / "L0_k_rules.json"


def pct(a: int, n: int) -> str:
    return f"{100 * a / n:.2f} %"


def main() -> int:
    d = json.loads(AGG.read_text(encoding="utf-8"))
    print("# SPEC-L0 K rules against the published lists\n")
    print("Status: generated by `analysis/l0_k_rules_report.py` from `analysis/aggregates/L0_k_rules.json` "
          "(itself written by `analysis/l0_k_rules_extract.py` from the FIDE standard lists, February 2015 to "
          "October 2026, which are never committed); do not edit by hand.\n")
    print(f"Population: {d['population']}. One row per player and list (player-months).\n")
    print("## 1 Rule orders scored against the published K\n")
    print("| rule order | games counted | agree | player-months | share |")
    print("|---|---|---|---|---|")
    for key, label in (("variant_with_first_list_games", "including the first list's games"),
                       ("variant_without_first_list_games", "after the first list only")):
        a = d["agreement"][key]
        print(f"| text order: {d['rule_order']} | {label} | {a['agree']:,} | {a['n']:,} | {pct(a['agree'], a['n'])} |")
    r = d["refined_agreement"]
    print(f"| refined order: {d['refined_order']} | including the first list's games | {r['agree']:,} | {r['n']:,} | "
          f"{pct(r['agree'], r['n'])} |")
    print("\n## 2 Disagreements of the refined order\n")
    print("| games counted on the lists | predicted, published | player-months |")
    print("|---|---|---|")
    for g in ("<25", "25-34", "35+"):
        for k, v in d["refined_disagreements_by_games"].get(g, {}).items():
            print(f"| {g} | {k} | {v:,} |")
    tot = sum(v for g in d["refined_disagreements_by_games"].values() for v in g.values())
    big = d["residual_published20_predicted40_games_lt25_by_games"]
    print(f"\nTotal {tot:,}. The largest group, published 20 where the refined order predicts 40 with fewer than 25 "
          f"counted games ({sum(big.values()):,}), by games counted and by list year:\n")
    print("| games counted | player-months |")
    print("|---|---|")
    for k, v in sorted(big.items(), key=lambda kv: int(kv[0].split("-")[0])):
        print(f"| {k} | {v:,} |")
    print("\n| list year | player-months |")
    print("|---|---|")
    for k, v in d["residual_published20_predicted40_games_lt25_by_list_year"].items():
        print(f"| {k} | {v:,} |")
    print("\n## 3 Juniors at the turn of the year (R-21)\n")
    print("Players aged 19 by list year in January (18th birthday in the previous year), rated below 2300, with at "
          "least 30 counted games and never published at 2400 or more: published K on the December list and the "
          "following January list.\n")
    print("| transition | 40 -> 20 | 40 -> 40 | 20 -> 20 | other |")
    print("|---|---|---|---|---|")
    for k, v in d["turning_19_december_to_january"].items():
        other = sum(c for t, c in v.items() if t not in ("40->20", "40->40", "20->20"))
        print(f"| {k} | {v.get('40->20', 0):,} | {v.get('40->40', 0):,} | {v.get('20->20', 0):,} | {other:,} |")
    print("\n## 4 Published K by cell\n")
    print("Cell: junior by list year (R-21), rating band on the list, at least 30 counted games, ever published at "
          "2400 or more, ever published at 2300 or more.\n")
    print("| junior | band | games >= 30 | ever 2400 | ever 2300 | K published (player-months) |")
    print("|---|---|---|---|---|---|")
    for cell, ks in d["published_k_by_cell"].items():
        f = dict(x.split("=") for x in cell.split("|"))
        dist = ", ".join(f"K {k}: {v:,}" for k, v in sorted(ks.items(), key=lambda kv: -kv[1]))
        print(f"| {f['junior']} | {f['band']} | {f['games30']} | {f['ever2400']} | {f['ever2300']} | {dist} |")
    return 0


if __name__ == "__main__":
    sys.exit(main())
