#!/usr/bin/env python3
"""SPEC-L0 §8 Q-1: is a period's change rounded once, or each tournament's change? (D-0008, R10)

Reads the fixtures of FIDE's published calculations, the five of ELO-3
(tests/fixtures/fide_calculator/published_calculations.json, F-P01 to F-P05) and
the multi-event periods added under R10
(tests/fixtures/fide_calculator/published_multi_event_periods.json, F-Mnn), and
for every period computes the change rounded once (FIDE §8.3.4 applied to the
period, SPEC-L0 R-25 as written) and rounded per tournament, against the change
of the published list. A period discriminates when the two roundings differ.
Every value is recomputed here from the fixtures; nothing needs data/.

Usage: python3 analysis/l0_rounding_report.py > analysis/OUTPUT_L0_rounding.md
"""
from __future__ import annotations

import json
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIX = ROOT / "tests" / "fixtures" / "fide_calculator"


def rnd(x: Decimal) -> int:
    """§8.3.4: nearest whole number, 0.5 away from zero."""
    q = abs(x).quantize(Decimal(1), rounding=ROUND_HALF_UP)
    return int(q) if x >= 0 else -int(q)


def month_before(m: str) -> str:
    y, mo = map(int, m.split("-"))
    return f"{y - 1}-12" if mo == 1 else f"{y:04d}-{mo - 1:02d}"


def classify(case: dict, base_shift: int = 0) -> dict:
    k_chg = [Decimal(t["K_chg"]) for t in case["tournaments"]]
    per_period, per_tournament = rnd(sum(k_chg)), sum(rnd(x) for x in k_chg)
    lists = case["published_list_ratings"]
    period = case["rating_period"]
    change = lists[period] - lists[month_before(period)] - base_shift
    follows = ("both" if per_period == per_tournament == change else "period" if per_period == change
               else "tournament" if per_tournament == change else "neither")
    ro_diff = any(int(t["Ro"]) != lists.get(t["start"][:7], int(t["Ro"])) for t in case["tournaments"])
    # FIDE's own base: the Ro of an event that uses the previous list (R-11a); a base correction shows as Ro != that list
    base = next((int(t["Ro"]) for t in case["tournaments"] if t["start"][:7] == month_before(period)), None)
    from_base = None
    if follows == "neither" and base is not None:
        c = lists[period] - base
        from_base = ("both" if per_period == per_tournament == c else "period" if per_period == c
                     else "tournament" if per_tournament == c else "neither")
    return {"id": case["id"], "period": period, "events": len(k_chg), "games": sum(int(t["n"]) for t in case["tournaments"]),
            "total": sum(k_chg), "per_period": per_period, "per_tournament": per_tournament, "change": change,
            "follows": follows, "discriminates": per_period != per_tournament, "ro_differs": ro_diff, "from_base": from_base,
            "cross": any(t["start"][:7] < month_before(period) for t in case["tournaments"])}


def main() -> None:
    old = json.loads((FIX / "published_calculations.json").read_text(encoding="utf-8"))["cases"]
    new = json.loads((FIX / "published_multi_event_periods.json").read_text(encoding="utf-8"))
    rows = []
    for c in old:
        # F-P04: FIDE starts from Ro 2053 while the November list printed 2052 (R-11b); the change is taken from Ro
        shift = 1 if c["id"] == "F-P04" else 0
        rows.append(classify(c, shift) | {"set": "ELO-3"})
    for c in new["cases"]:
        r = classify(c)
        assert r["follows"] == c["list_follows"] and r["per_period"] == c["change_rounded_per_period"], c["id"]
        rows.append(r | {"set": "R10"})
    out = ["# OUTPUT — SPEC-L0 §8 Q-1: rounding per period or per tournament (D-0008, R10)", "",
           "Status: REVIEW — generated by `analysis/l0_rounding_report.py` from "
           "`tests/fixtures/fide_calculator/published_calculations.json` (F-P01 to F-P05, session ELO-3) and "
           "`tests/fixtures/fide_calculator/published_multi_event_periods.json` (F-Mnn, session ELO-4). Do not edit by hand.", "",
           f"New fixtures: {new['selection']}.", "",
           "For every period: the change rounded once (§8.3.4 applied to the period total, SPEC-L0 R-25 as written) and rounded "
           "per tournament, against the change of the player's published rating. A period discriminates when the two roundings "
           "differ. \"Ro differs\" marks a tournament whose starting rating Ro is not the rating on the list in force at its start "
           "(a base correction, R-11b).", "",
           "| case | period | events | games | sum of K x chg | rounded once | rounded per tournament | list change | list follows | discriminates | Ro differs | from FIDE's base |",
           "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        out.append(f"| {r['id']} | {r['period']} | {r['events']} | {r['games']} | {r['total']:+.2f} | {r['per_period']:+d} | "
                   f"{r['per_tournament']:+d} | {r['change']:+d} | {r['follows']} | {'yes' if r['discriminates'] else 'no'} | "
                   f"{'yes' if r['ro_differs'] else 'no'} | {r['from_base'] or ''} |")
    multi = [r for r in rows if r["events"] >= 2]
    disc = [r for r in multi if r["discriminates"]]
    clean = [r for r in disc if not r["ro_differs"]]
    tally = {k: sum(1 for r in disc if r["follows"] == k) for k in ("period", "tournament", "neither")}
    tally_clean = {k: sum(1 for r in clean if r["follows"] == k) for k in ("period", "tournament", "neither")}
    new_multi = [r for r in multi if r["set"] == "R10"]
    out += ["", "## Tally", "",
            f"- Multi-event periods: {len(multi)} ({len(new_multi)} added under R10, {len(multi) - len(new_multi)} from ELO-3).",
            f"- Periods in which the two roundings differ: {len(disc)}. The list follows rounding once in {tally['period']}, "
            f"rounding per tournament in {tally['tournament']}, neither in {tally['neither']}.",
            f"- Of those, without a base correction: {len(clean)}; rounding once {tally_clean['period']}, per tournament "
            f"{tally_clean['tournament']}, neither {tally_clean['neither']}.",
            f"- Periods in which both roundings agree with the list: {sum(1 for r in multi if r['follows'] == 'both')}; "
            f"neither: {sum(1 for r in multi if r['follows'] == 'neither')}, of which "
            f"{sum(1 for r in multi if r['follows'] == 'neither' and r['from_base'] in ('both', 'period'))} are reproduced exactly when "
            "the period's change is applied to FIDE's own starting rating Ro (base corrections, R-11b) and "
            f"{sum(1 for r in multi if r['follows'] == 'neither' and r['from_base'] not in ('both', 'period'))} stay unexplained.",
            f"- Games checked: every game of the {len(new_multi)} new periods "
            f"({sum(r['games'] for r in new_multi):,}) is reproduced by the Layer-0 engine, with each tournament's sum, K and "
            "K x sum (`tests/test_l0_rounding_periods.py`).", "",
            "## Reading", "",
            f"Rounding once per period, as §8.3.4 is written and SPEC-L0 R-25 reads it, reproduces FIDE's list in {tally['period']} of the "
            f"{len(disc)} discriminating periods; the exception, F-P02, is reproduced only by rounding each tournament, and neither its "
            f"events' starting ratings nor the lists show why. {sum(1 for r in disc if r['cross'] and r['follows'] == 'period')} of the "
            "discriminating periods that follow rounding once hold an event that started under an earlier list, so rounding such "
            "events separately is not FIDE's practice either. SPEC-L0 v1.1 records this evidence (D-0009, R21) and keeps "
            "rounding once per period; Q-1 stays NOT VERIFIED.", ""]
    print("\n".join(out))


if __name__ == "__main__":
    main()
