#!/usr/bin/env python3
"""SPEC-L0 ratification check: the pre-agreed rule of the ELO-3 brief, measured.

"The spec is ratified when every rule has a fixture or a verbatim citation and
every acceptance criterion is an executable test." This script reads
docs/specs/SPEC-L0_fide-reference-engine_v1_0.md and reports, for every rule of
§3, its evidence classes (CIT with a quotation, FIX with fixture identifiers
that exist in tests/fixtures/, DATA), whether it carries a NOT VERIFIED reading,
and which test modules mention it; and, for every acceptance criterion of §7,
whether its test module exists and how many test functions it defines. It reads
files only; it does not run the tests (check (b) does). Python standard library only.

Usage: python3 analysis/l0_ratification_check.py > analysis/OUTPUT_L0_ratification.md
"""
from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "docs" / "specs" / "SPEC-L0_fide-reference-engine_v1_0.md"
RULE = re.compile(r"^- \*\*(R-\d\d[a-z]?)(?: to (R-\d\d))?\b")
FIX_ID = re.compile(r"\bF-[CIPN]\d\d\b")
RANGE = re.compile(r"\bR-(\d\d)[a-z]? (?:to|\.\.) R-(\d\d)[a-z]?\b")
SINGLE = re.compile(r"\bR-\d\d[a-z]?\b")


def fixture_ids() -> set[str]:
    ids = set()
    for f in sorted((ROOT / "tests" / "fixtures").rglob("*.json")):
        for case in json.loads(f.read_text(encoding="utf-8")).get("cases", []):
            ids.add(case["id"])
    return ids


def mentioned_rules(text: str, all_rules: list[str]) -> set[str]:
    out = set(SINGLE.findall(text))
    for a, b in RANGE.findall(text):
        out |= {r for r in all_rules if a <= r[2:4] <= b}
    return out


def main() -> int:
    spec = SPEC.read_text(encoding="utf-8")
    section3 = spec[spec.index("## 3 Rules"):spec.index("## 4 Interfaces")]
    rules: list[tuple[str, str]] = []
    for line in section3.split("\n"):
        m = RULE.match(line)
        if m and m.group(2):                                  # "R-18 to R-21": one bullet, four rules
            for i in range(int(m.group(1)[2:4]), int(m.group(2)[2:4]) + 1):
                rules.append((f"R-{i:02d}", line))
        elif m:
            rules.append((m.group(1), line))
    ids = [r for r, _ in rules]
    tests = {f.name: f.read_text(encoding="utf-8") for f in sorted((ROOT / "tests").glob("test_l0_*.py"))}
    known = fixture_ids()
    print("# SPEC-L0 ratification check\n")
    print("Status: generated by `analysis/l0_ratification_check.py` from "
          "`docs/specs/SPEC-L0_fide-reference-engine_v1_0.md`, `tests/test_l0_*.py` and `tests/fixtures/`; "
          "do not edit by hand. Cited by `docs/decisions/D-0006_spec-l0-ratified.md`.\n")
    print("## 1 Every rule has a verbatim citation or a fixture\n")
    print("| rule | CIT (quoted) | FIX | DATA | fixtures cited, all present | NOT VERIFIED reading | test modules mentioning it |")
    print("|---|---|---|---|---|---|---|")
    ok_rules = 0
    untested = []
    for rid, text in rules:
        cit = "CIT" in text and '"' in text
        fixes = sorted(set(FIX_ID.findall(text)))
        fix = "FIX" in text and bool(fixes)
        data = "DATA" in text
        present = all(f in known for f in fixes)
        nv = "NOT VERIFIED" in text
        mods = [name for name, src in tests.items() if rid in mentioned_rules(src, ids)]
        if not mods:
            untested.append(rid)
        ok_rules += (cit or fix) and present
        print(f"| {rid} | {cit} | {', '.join(fixes) if fix else '-'} | {data} | {present} | {nv} | "
              f"{', '.join(m[:-3] for m in mods) or '-'} |")
    print(f"\nRules: {len(rules)}; with a verbatim citation or a fixture (all cited fixtures present): {ok_rules}; "
          f"mentioned by no test module: {len(untested)}{' (' + ', '.join(untested) + ')' if untested else ''}.\n")
    print("## 2 Every acceptance criterion is an executable test\n")
    section7 = spec[spec.index("## 7 Acceptance criteria"):spec.index("## 8 Open questions")]
    print("| criterion | test module | exists | test functions |")
    print("|---|---|---|---|")
    n_crit = ok_crit = 0
    for line in section7.split("\n"):
        m = re.match(r"^\| (A-\d+) \|.*\| (tests/\S+\.py) \|$", line)
        if not m:
            continue
        n_crit += 1
        path = ROOT / m.group(2)
        count = 0
        if path.exists():
            tree = ast.parse(path.read_text(encoding="utf-8"))
            count = sum(1 for node in tree.body if isinstance(node, ast.FunctionDef) and node.name.startswith("test_"))
        ok_crit += path.exists() and count > 0
        print(f"| {m.group(1)} | {m.group(2)} | {path.exists()} | {count} |")
    print(f"\nCriteria: {n_crit}; with an existing test module defining at least one test: {ok_crit}.\n")
    verdict = ok_rules == len(rules) and ok_crit == n_crit and n_crit > 0
    print(f"## 3 Verdict\n\nThe pre-agreed ratification rule is met: {verdict}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
