#!/usr/bin/env python3
"""Layer 1 on history: the report of analysis/aggregates/L1_history.json (SPEC-L1 §4.6, §5, §8).

Reads only the committed aggregates; no data/ needed.

Usage: python3 analysis/l1_history_report.py > analysis/OUTPUT_L1_history.md
"""
from __future__ import annotations

import json
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BANDS = ["<1600", "1600-1999", "2000-2199", "2200-2399", "2400-2599", "2600+", "unrated"]
AGES = ["<=18", "19-24", "25-45", "46-64", "65+", "unknown"]
AGE_BANDS = ("under 12", "12-15", "16-19", "20-24", "25-45", "46-60", "over 60")


def n0(x) -> str:
    return "—" if x is None else f"{x:,}"


def main() -> None:
    d = json.loads((ROOT / "analysis" / "aggregates" / "L1_history.json").read_text(encoding="utf-8"))
    f = d["fit"]
    P = []
    p = P.append
    p("# OUTPUT — Layer 1 on history: the fit, the anchor, the spread and the coverage")
    p("")
    p("Status: REVIEW — generated by `analysis/l1_history_report.py` from `analysis/aggregates/L1_history.json`, which "
      "`analysis/l1_history_extract.py` computes under `docs/specs/SPEC-L1_v1_0.md` from the Lichess broadcast archive "
      "(CC BY-SA 4.0, attributed; aggregates only) [V 4] and FIDE's lists (analysed, never redistributed) [V 3]. Do not edit by "
      "hand. Session ELO-4, Phase 3. Every value is PROVISIONAL-FITTED on broadcast games, which are stronger and more "
      "international than the rated pool [E2].")
    p("")
    dm = f["data"]
    p("## 1 The fit")
    p("")
    p(f"- **Games.** {n0(f['games'])} games between {n0(f['players'])} players with FIDE IDs, {d['window'][0]} to {d['window'][1]} "
      f"(read {n0(dm.get('read'))}, duplicates removed {n0(dm.get('duplicates_removed'))}, without both IDs or a classified tour "
      f"{n0(dm.get('no_tc_or_ids'))}, involving the R11 batch {n0(dm.get('r11_batch'))}, dated after the cutoff and dropped "
      f"{n0(dm.get('dropped_after_cutoff', 0))}).")
    p(f"- **Anchor panels** at {f['hyperparameters']['t_ref']} (SPEC-L1 §3.5): " +
      ", ".join(f"{tc} {n0(n)} players (published mean {f['m_ref'][tc]})" for tc, n in f["panels"].items()) + ".")
    p("- **Hyperparameters chosen on held-out games** (§4.6: fit 2023-01 to 2024-09, score 2024-10 to 2024-12, three-outcome "
      "log-loss):")
    p("")
    p("| c_θ | ω | log-loss (nats a game) | held-out games | sweeps |")
    p("|---|---|---|---|---|")
    for g in f["grid"]:
        mark = " (chosen)" if g == f["chosen"] else ""
        p(f"| {g['c_theta']} | {g['omega']} | {g['log_loss']:.6f}{mark} | {n0(g['games'])} | {g['sweeps']} |")
    p("")
    cs = sorted({g["c_theta"] for g in f["grid"]})
    ws = sorted({g["omega"] for g in f["grid"]})
    edge = [name for name, v, grid in (("c_θ", f["chosen"]["c_theta"], cs), ("ω", f["chosen"]["omega"], ws)) if v in (grid[0], grid[-1])]
    if edge:
        p(f"- **On the edge of the grid.** The chosen {' and '.join(edge)} lie{'s' if len(edge) == 1 else ''} at the end of the "
          "grid fixed before the fit (§3.7, §4.6), so the held-out optimum may lie beyond it; the grid is not widened after the "
          "fact, and a wider grid is for the next fit. The held-out log-loss spans "
          f"{max(g['log_loss'] for g in f['grid']) - min(g['log_loss'] for g in f['grid']):.4f} nats a game across the grid.")
    p(f"- **Convergence.** {f['sweeps']} sweeps, the largest move in the last sweep {f['max_move']} points, {f['drift_rounds']} drift "
      f"refits; the anchor's final common shift {f['anchor_shift_final']:+.3f} points (the list-based priors were that close to "
      f"the anchor). μ_rapid {f['mu'][1]:+.1f}, μ_blitz {f['mu'][2]:+.1f} latent points.")
    p(f"- **Outcome parameters** (the table's in latent units, §3.2): η^L {', '.join(str(v) for v in f['outcome_latent']['eta'])} "
      f"(standard, rapid, blitz).")
    p(f"- **In-sample log-loss:** " + ", ".join(f"{k} {v}" for k, v in f["in_sample_log_loss"].items()) +
      f". Game graph: {n0(f['components']['n'])} connected components, the largest holding {100 * f['components']['largest_share']:.1f} % of players.")
    p(f"- **Offsets.** Cov(θ, δ_tc): " + ", ".join(f"{k} {v}" for k, v in f["cov_theta_delta"].items()) +
      "; correlation of ŝ across time controls for players with 10 or more games in both: " +
      ", ".join(f"{k.replace('_', ' and ')} {v['correlation']} ({n0(v['players'])} players)" for k, v in f["cross_tc_correlation"].items()) + ".")
    p("")
    p("**Drift by age** (§3.3, fitted; latent points a month at θ = 2000, and the slope per 400 points of θ):")
    p("")
    p("| age band | " + " | ".join(AGE_BANDS) + " |")
    p("|---|" + "---|" * 7)
    p("| A_a, points a month | " + " | ".join(f"{a:+.2f}" for a in f["drift_A"]) + " |")
    p("| A_a × 12, points a year | " + " | ".join(f"{12 * a:+.0f}" for a in f["drift_A"]) + " |")
    p("| B_a, per 400 points | " + " | ".join(f"{b:+.2f}" for b in f["drift_B"]) + " |")
    p("")
    p("Ages 25–45 are fixed at zero by definition (T2.4): the other bands' drifts are relative to steadily active adults.")
    p("")
    p("**Calibration of σ on held-out games** (§5.5, standard; z = (S − E)/sqrt(Var S) at the plug-in forecast, by decile of "
      "the pair's combined σ):")
    p("")
    p("| decile | games | median combined σ | share with a player outside the fit | mean z | SD of z |")
    p("|---|---|---|---|---|---|")
    for r in f["calibration_held_out"]:
        p(f"| {r['decile']} | {n0(r['games'])} | {r['sigma_pair_median']} | {100 * r['outside_fit_share']:.0f} % | "
          f"{r['z_mean']:+.4f} | {r['z_sd']:.4f} |")
    p("")
    p("| players outside the fit (σ = s_0) | games | median combined σ | mean z | SD of z |")
    p("|---|---|---|---|---|")
    for r in f["calibration_by_players_outside_fit"]:
        p(f"| {r['players_outside_fit']} | {n0(r['games'])} | {r['sigma_pair_median']} | {r['z_mean']:+.4f} | {r['z_sd']:.4f} |")
    p("")
    p("An SD of z above 1 where σ is large is the plug-in forecast ignoring the players' uncertainty (§4.5): the forecast uses "
      "the posterior mode, so a pair whose strengths are uncertain scores further from it than a game's own variance allows. "
      "z is taken from White's side, so its mean tests the first-move term, not the direction of a newcomer's error.")
    p("")

    p("## 2 The anchor: the published level against Layer 1 (§5.2)")
    p("")
    p("d_t = m̂_t − m_t for the panel members present: a positive d_t means the panel's published ratings sit below its latent "
      "strength (deflation of the published scale since t_ref), negative the reverse. a_t is the monthly adjustment the "
      "controller of annex T4.5 would publish from that d_t. The panel is fixed at t_ref = 2025-01, after the March 2024 "
      "compression; before March 2024 its members below 2000 carried ratings 0.4 × (2000 − R) lower [E5], which is the jump "
      "in d_t between February and March 2024, a one-off change of the published scale rather than a drift.")
    p("")
    tcs = list(d["anchor_series"])
    p("| month | " + " | ".join(f"{tc}: d_t / a_t" for tc in tcs) + " |")
    p("|---|" + "---|" * len(tcs))
    series = {tc: {r["month"]: r for r in d["anchor_series"][tc]} for tc in tcs}
    months = [r["month"] for r in d["anchor_series"][tcs[0]]]
    show = [m for m in months if m[5:] in ("01", "04", "07", "10") or m in ("2024-02", "2024-03", months[-1])]
    for m in show:
        p(f"| {m} | " + " | ".join(f"{series[tc][m]['d_t']:+.1f} / {series[tc][m]['a_t']:+.1f}" for tc in tcs) + " |")
    p("")
    for tc in tcs:
        rows = d["anchor_series"][tc]
        pre = [r["d_t"] for r in rows if r["month"] <= "2024-02"]
        post = [r["d_t"] for r in rows if r["month"] >= "2024-03"]
        p(f"- {tc}: d_t from {min(pre):+.1f} to {max(pre):+.1f} before March 2024 and from {min(post):+.1f} to {max(post):+.1f} "
          f"since; panel members present {min(r['members'] for r in rows):,} to {max(r['members'] for r in rows):,}.")
    p("")

    p("## 3 The spread ratio (R1; §5.3)")
    p("")
    p("SD of published ratings ÷ SD of Layer 1's ŝ for active adults (25–45, rated, a game of the fit in the 12 months up to the "
      "month), and the same with the denominator corrected for the posterior variance. The threshold of R1 is to be set from "
      "this series' variation (D-0008, reading 1).")
    p("")
    p("| time control | months | ratio: first / last | ratio: min / max | corrected: first / last | SD of the month-to-month change | largest 12-month change | largest 12-month change from March 2024 |")
    p("|---|---|---|---|---|---|---|---|")
    for tc, rows in d["spread_series"].items():
        if len(rows) < 13:
            continue
        r = [x["ratio"] for x in rows]
        cr = [x["ratio_noise_corrected"] for x in rows]
        dif = [b - a for a, b in zip(r, r[1:])]
        d12 = [abs(r[k + 12] - r[k]) for k in range(len(r) - 12)]
        d12p = [abs(r[k + 12] - r[k]) for k in range(len(r) - 12) if rows[k]["month"] >= "2024-03"]
        p(f"| {tc} | {len(rows)} | {r[0]:.3f} / {r[-1]:.3f} | {min(r):.3f} / {max(r):.3f} | {cr[0]:.3f} / {cr[-1]:.3f} | "
          f"{statistics.pstdev(dif):.4f} | {max(d12):.3f} | {max(d12p):.3f} |")
    p("")

    p("## 4 Outputs at the list of October 2026 (§5.1)")
    p("")
    for tc, o in d["at_list"].items():
        a = o["anchor_at_list"]
        p(f"### {tc}")
        p("")
        p(f"- Players in the fit with games in {tc}: {n0(o['players_in_fit'])}; the panel at the list: {n0(a['members'])} members, "
          f"m_t {a['m_t']}, m̂_t {a['m_hat_t']}, d_t {a['d_t']:+.2f}.")
        sp = o["sigma_published"]
        p(f"- σ̃ (published scale): median {sp.get('median')}, p10 {sp.get('p10')}, p90 {sp.get('p90')}.")
        p("- K by R6 for players rated on the list with a game of the fit in the last 12 months:")
        p("")
        p("| band | players | p10 | median | p90 | mean |")
        p("|---|---|---|---|---|---|")
        for b in BANDS:
            k = o["k_by_band"].get(b)
            if k and k.get("n"):
                p(f"| {b} | {n0(k['n'])} | {k['p10']} | {k['median']} | {k['p90']} | {k['mean']} |")
        p("")
        if tc == "standard":
            ke = o["k_elite_2600"]
            p(f"- **Established 2600+ players** (rated 2600 or more, aged 20 or more, at least 10 standard games of the fit): "
              f"{n0(ke.get('n'))} players, K from {ke.get('min')} to {ke.get('max')}, median {ke.get('median')} (today's K is 10 "
              "for every player once rated 2400) (R6).")
        j = o["juniors"]
        p(f"- **Juniors** rated on the list (aged 19 or less): {n0(j.get('juniors', 0))}; passing the game, opponent and tour gates on "
          f"broadcast games: {n0(j.get('pass_game_gates', 0))}; eligible after R5's information share ≥ 0.5: {n0(j.get('eligible', 0))} "
          f"({n0(j.get('fail_share_only', 0))} fail on the share alone); compensated (c_j > 0): {n0(j.get('compensated', 0))}.")
        ce = o["compensation_eligible"]
        if ce.get("n"):
            p(f"  c_j among eligible juniors: median {ce['median']}, p90 {ce['p90']}, max {ce['max']}.")
        sd = o["seeds"]
        p(f"- **Unrated players** in the fit: {n0(sd['unrated_in_fit'])}; a seed would be published for {n0(sd['published'])}"
          + (f" (median {sd['values']['median']})." if sd["values"].get("n") else "."))
        p("")

    p("## 5 Coverage (Phase 3.3; §8)")
    p("")
    p("Players with a usable estimate (σ̃ ≤ 100 points on the published scale, PROVISIONAL) at the list of October 2026, against "
      "the active rated players on that list (at least one rated game in the 12 months up to it), by band of the list rating and "
      "age in 2026. \"In fit\" counts every player of the fit with a game in that time control.")
    p("")
    for tc, o in d["at_list"].items():
        cov = {(c["band"], c["age"]): c for c in o["coverage"]}
        p(f"**{tc}** — usable / active rated (share)")
        p("")
        p("| band | " + " | ".join(AGES) + " | all ages |")
        p("|---|" + "---|" * (len(AGES) + 1))
        for b in BANDS:
            cells, tu, tp_ = [], 0, 0
            for a in AGES:
                c = cov.get((b, a))
                if not c:
                    cells.append("—")
                    continue
                if b == "unrated":          # not on the list: no pool; usable of those in the fit
                    tu += c["usable"]
                    tp_ += c["in_fit"]
                    cells.append(f"{c['usable']:,} of {c['in_fit']:,} in the fit")
                    continue
                tu += c["usable"]
                tp_ += c["pool"]
                cells.append(f"{c['usable']:,} / {c['pool']:,}" + (f" ({100 * c['usable'] / c['pool']:.1f} %)" if c["pool"] else ""))
            if b == "unrated":
                p(f"| unrated (not on the list) | " + " | ".join(cells) + f" | {tu:,} of {tp_:,} in the fit |")
                continue
            p(f"| {b} | " + " | ".join(cells) + f" | {tu:,} / {tp_:,}" + (f" ({100 * tu / tp_:.1f} %)" if tp_ else "") + " |")
        tot_u = sum(c["usable"] for c in o["coverage"] if c["band"] != "unrated")
        tot_p = sum(c["pool"] for c in o["coverage"] if c["band"] != "unrated")
        p("")
        p(f"Rated players with a usable estimate: {tot_u:,} of {tot_p:,} active rated players ({100 * tot_u / tot_p:.1f} %).")
        p("")
    st = d["at_list"]["standard"]
    cov = {(c["band"], c["age"]): c for c in st["coverage"]}
    jun_u = sum(cov[(b, "<=18")]["usable"] for b in BANDS[:-1] if (b, "<=18") in cov)
    jun_p = sum(cov[(b, "<=18")]["pool"] for b in BANDS[:-1] if (b, "<=18") in cov)
    top_u = sum(cov[("2400-2599", a)]["usable"] + cov.get(("2600+", a), {"usable": 0})["usable"] for a in AGES if ("2400-2599", a) in cov)
    top_p = sum(cov[("2400-2599", a)]["pool"] + cov.get(("2600+", a), {"pool": 0})["pool"] for a in AGES if ("2400-2599", a) in cov)
    low_u = sum(cov[("<1600", a)]["usable"] for a in AGES if ("<1600", a) in cov)
    low_p = sum(cov[("<1600", a)]["pool"] for a in AGES if ("<1600", a) in cov)
    p("**What the strong-player bias means** (standard).")
    p("")
    p(f"- At 2400 and above the broadcast sample covers {100 * top_u / top_p:.0f} % of active rated players with a usable estimate; "
      f"below 1600, {100 * low_u / low_p:.1f} %. Juniors aged 18 or less: {jun_u:,} of {jun_p:,} ({100 * jun_u / jun_p:.1f} %).")
    p(f"- Rung 5 (junior compensation) can be tested only on the juniors who play broadcast events: {n0(st['juniors'].get('eligible', 0))} "
      "are eligible at the October 2026 list, most of them strong juniors whose ratings already move fast. The juniors the rung is "
      "meant for, improving players below 2000 in domestic events, are almost absent.")
    p(f"- Rung 3 (newcomer seeds): {n0(st['seeds']['unrated_in_fit'])} unrated players appear in the fit; newcomers enter FIDE's list "
      "through domestic events that are rarely broadcast, so seeds can be tested only on the few who first appear in broadcast events.")
    p("- The tests of E6 therefore hold for the broadcast population; FIDE's tournament reports (the TRF archive) settle them for the pool.")
    p("")
    p("## 6 Limits")
    p("")
    p("- Broadcast games only: most of a player's rated games are missing, so σ is larger and the gates of compensation and seeds are "
      "counted on fewer games than FIDE records.")
    p("- σ is conditional on the opponents' estimates (§4.3), and the plug-in forecasts ignore it (§4.5).")
    p("- Published ratings stand in for the previous fit at the window's start (§3.4).")
    print("\n".join(P))


if __name__ == "__main__":
    main()
